---
permalink: audit/asce-archive-object-store-end.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, ASCE, Archive Object Store End 
summary: このメッセージは、外部アーカイブストレージシステムへのコンテンツブロックの書き込みが終了したことを示します。 
---
= ASCE ：アーカイブオブジェクトストアの終了
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このメッセージは、外部アーカイブストレージシステムへのコンテンツブロックの書き込みが終了したことを示します。

[cols="1a,1a,4a"]
|===
| コード | フィールド | 説明 


 a| 
CBID
 a| 
Content Block Identifier の略
 a| 
外部アーカイブストレージシステムに格納されているコンテンツブロックの識別子。



 a| 
VLID
 a| 
ボリューム識別子
 a| 
オブジェクトデータの書き込み先のアーカイブボリュームの一意の識別子。



 a| 
VREN
 a| 
検証が有効です
 a| 
コンテンツブロックに対して検証が実行されるかどうかを示します。現在定義されている値は次のとおり

* VENA ：検証が有効になっています
* VDSA ：検証は無効です




 a| 
MCLS
 a| 
管理クラス
 a| 
コンテンツブロックが割り当てられている TSM 管理クラスを識別する文字列（該当する場合）。



 a| 
RSLT
 a| 
結果
 a| 
アーカイブプロセスの結果を示します。現在定義されている値は次のとおり

* SUCS ：成功（アーカイブプロセスが成功）
* OFFL ：失敗（アーカイブがオフライン）
* VRFL ：失敗（オブジェクトの検証に失敗）
* ARUN ：失敗（外部アーカイブストレージシステムを使用できない）
* GERR ：失敗（一般的なエラー）


|===
この監査メッセージは、指定されたコンテンツブロックが外部アーカイブストレージシステムに書き込まれたことを意味します。書き込みが失敗した場合は、どこで失敗したかを示す基本的なトラブルシューティング情報が結果として記録されます。より詳細な失敗原因については、 StorageGRID システムでアーカイブノードの属性を調べてください。
