---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: StorageGRID システム内でやり取りされる監査メッセージには、すべてのメッセージに共通の標準情報と、報告対象のイベントまたはアクティビティを説明する固有のコンテンツが含まれます。 
---
= 監査メッセージの形式：概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システム内でやり取りされる監査メッセージには、すべてのメッセージに共通の標準情報と、報告対象のイベントまたはアクティビティを説明する固有のコンテンツが含まれます。

によって提供された概要情報の場合 link:using-audit-explain-tool.html["監査-説明する"] および link:using-audit-sum-tool.html["audit-sumの略"] ツールで十分ではありません。すべての監査メッセージの一般的な形式を把握するには、このセクションを参照してください。

以下は、監査ログファイルに記録されている監査メッセージの例です。

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
各監査メッセージには、一連の属性要素で構成されます。文字列全体が角かっこで囲まれます (`[ ]`）、および文字列内の各属性要素には、次の特性があります。

* 角かっこで囲まれています `[ ]`
* 文字列で導入されます `AUDT`を指定します
* 前後に区切り記号（カンマやスペース）がない
* 改行文字で終了します `\n`


各要素には、次の形式で報告される属性コード、データ型、および値が含まれます。

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
メッセージ内の属性要素の数は、メッセージのイベントタイプによって異なります。属性要素は特定の順序でリストされません。

次に、属性要素について説明します。

* `ATTR` は、報告される属性の4文字のコードです。すべての監査メッセージに共通する属性とイベント固有の属性があります。
* `type` は、UI64、FC32など、値のプログラミングデータ型の4文字の識別子です。タイプはかっこで囲まれます `( )`。
* `value` は属性の内容で、通常は数値またはテキスト値です。値の前には常にコロンが付きます (`:`）。データ型CStrの値は二重引用符で囲まれます。

