---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: アップグレード時にStorageGRIDシステムがどのような影響を受けるかについて説明します。 
---
= アップグレード中にシステムが受ける影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレード時にStorageGRIDシステムがどのような影響を受けるかについて説明します。



== StorageGRID のアップグレードは無停止で実行されます

StorageGRID システムは、アップグレードプロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができます。同じタイプのすべてのノード（ストレージノードなど）のアップグレードを承認すると、ノードが一度に1つずつ停止されるため、すべてのグリッドノードまたは特定のタイプのすべてのグリッドノードが使用できなくなる時間はありません。

継続的な可用性を確保するには、各オブジェクトの複数のコピーを格納するように指定するルールをILMポリシーに含めるようにしてください。また、次のいずれかに要求を送信するようにすべての外部の S3 または Swift クライアントを設定する必要があります。

* ハイアベイラビリティ（HA）グループの仮想IPアドレス
* 高可用性のサードパーティ製ロードバランサ
* 各クライアントに複数のゲートウェイノードが必要
* クライアントごとに複数のストレージノード




== クライアントアプリケーションが短時間中断される可能性があります

StorageGRIDシステムは、アップグレードプロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができます。ただし、アップグレード中に個 々 のゲートウェイノードまたはストレージノードでサービスの再開が必要になった場合は、それらのノードへのクライアント接続が一時的に中断されることがあります。接続はアップグレードプロセスの完了後にリストアされ、個 々 のノードのサービスが再開されます。

接続の中断が短時間でも許容されない場合は、アップグレードを適用するためにダウンタイムのスケジュールが必要になることがあります。特定のノードが更新されるタイミングをスケジュールするには、選択的な承認を使用できます。


NOTE: 複数のゲートウェイとハイアベイラビリティ（HA）グループを使用して、アップグレードプロセス中の自動フェイルオーバーを実現できます。の手順を参照してください link:../admin/configure-high-availability-group.html["ハイアベイラビリティグループを設定する"]。



== アプライアンスファームウェアがアップグレードされている

StorageGRID 11.8へのアップグレード時：

* すべてのStorageGRIDアプライアンスノードは、StorageGRIDアプライアンスインストーラのファームウェアバージョン3.8に自動的にアップグレードされます。
* SG6060およびSGF6024アプライアンスは、BIOSファームウェアバージョン3B07.EXおよびBMCファームウェアバージョン3.99.07に自動的にアップグレードされます。
* SG100およびSG1000アプライアンスは、BIOSファームウェアバージョン3B12.ECおよびBMCファームウェアバージョン4.73.07に自動的にアップグレードされます。
* SGF6112アプライアンスは、BIOSファームウェア・バージョン3A10.QDおよびBMCファームウェア・バージョン3.15.07に自動的にアップグレードされます。
* SGF6112は、セキュアブートをイネーブルにした状態でレガシーブートモードからUEFIブートモードに変換されます。




== ILMポリシーはステータスに応じて処理が異なります。

* アップグレード後もアクティブポリシーは変わりません。
* アップグレード時に保持されるのは、最新の10個の履歴ポリシーだけです。
* ドラフトポリシーがある場合は、アップグレード時に削除されます。




== アラートがトリガーされる可能性があります

アラートは、サービスの開始と停止、および StorageGRID システムを複数バージョンが混在した環境で使用している場合（一部のグリッドノードで以前のバージョンを実行し、その他のノードはより新しいバージョンにアップグレードしている場合）にトリガーされることがあります。アップグレードの完了後にその他のアラートがトリガーされることがあります。

たとえば、サービスが停止しているときに* Unable to communicate with node *アラートが表示されたり、一部のノードがStorageGRID 11.8にアップグレードされ、他のノードで引き続きStorageGRID 11.7が実行されているときに* Cassandra communication error *アラートが表示されたりすることがあります。通常、これらのアラートはアップグレードが完了するとクリアされます。

StorageGRID 11.8へのアップグレード中にストレージノードが停止すると、* ILM placement unachievable *アラートがトリガーされることがあります。このアラートは、アップグレードの完了後 1 日続く場合があります。

アップグレードが完了したら、Grid Managerダッシュボードで*[最近解決されたアラート]*または*[現在のアラート]*を選択して、アップグレード関連のアラートを確認できます。



== 多数の SNMP 通知が生成されます

アップグレード中にグリッドノードが停止および再起動されると、多数の SNMP 通知が生成される場合があります。過剰な通知を回避するには、* SNMPエージェント通知を有効にする*チェックボックス（*設定*>*監視*>* SNMPエージェント*）をオフにして、アップグレードを開始する前にSNMP通知を無効にします。その後、アップグレードの完了後に通知を再度有効にします。



== 設定の変更は制限されています


NOTE: このリストは、特にStorageGRID 11.7からStorageGRID 11.8へのアップグレードに適用されます。別のStorageGRID リリースにアップグレードする場合は、そのリリースのアップグレード手順の制限された変更のリストを参照してください。

[ 新しい機能を有効にする *] タスクが完了するまで :

* グリッド設定を変更しないでください。
* 新しい機能を有効または無効にしないでください。
* ILM設定を更新しないでください。ILM の動作が不安定になり、正常に動作しない場合があります。
* ホットフィックスの適用やグリッドノードのリカバリは行わないでください。
+

NOTE: アップグレード中にノードのリカバリが必要な場合は、テクニカルサポートにお問い合わせください。

* StorageGRID 11.8へのアップグレード中は、HAグループ、VLANインターフェイス、またはロードバランサエンドポイントを管理しないでください。
* StorageGRID 11.8へのアップグレードが完了するまで、HAグループを削除しないでください。他のHAグループの仮想IPアドレスにアクセスできなくなる可能性があります。


[* Final Upgrade Steps * （最終アップグレード手順 * ） ] タスクが完了するまで：

* 拡張手順 を実行しないでください。
* 運用停止手順 は実行しないでください。




== Tenant Managerでは、バケットの詳細を表示したりバケットを管理したりすることはできません

StorageGRID 11.8へのアップグレード中（システムが複数のバージョンが混在した環境として動作している場合）は、テナントマネージャを使用してバケットの詳細を表示したりバケットを管理したりすることはできません。Tenant Manager のバケットページには、次のいずれかのエラーが表示されます。

* 11.8へのアップグレード中は、このAPIを使用できません。
* 11.8へのアップグレード中は、Tenant Managerでバケットのバージョン管理の詳細を表示できません。


このエラーは、11.8へのアップグレードが完了すると解決します。

.回避策
11.8へのアップグレードの実行中に、Tenant Managerを使用する代わりに、次のツールを使用してバケットの詳細を表示したりバケットを管理したりします。

* バケットに対して標準のS3処理を実行するには、を使用します link:../s3/operations-on-buckets.html["S3 REST API"] または link:../tenant/understanding-tenant-management-api.html["テナント管理 API"]。
* バケットに対してStorageGRIDのカスタム処理（バケットの整合性の表示と変更、最終アクセス日時の更新の有効化と無効化、検索統合の設定など）を実行するには、テナント管理APIを使用します。

