---
permalink: ubuntu/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: 各ホストにブロックストレージボリュームを割り当てる必要があります。 
---
= ホストストレージを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各ホストにブロックストレージボリュームを割り当てる必要があります。

.作業を開始する前に
以下のトピックで、このタスクを実行するために必要な情報を確認しておきます。

link:storage-and-performance-requirements.html["ストレージとパフォーマンスの要件"]

link:node-container-migration-requirements.html["ノードコンテナの移行要件"]

.このタスクについて
ブロックストレージボリューム（LUN）をホストに割り当てるときは、「ストレージ要件」の表を使用して次の項目を確認してください。

* 各ホストに必要なボリュームの数（そのホストに導入するノードの数とタイプに応じて異なる）
* 各ボリュームのストレージのカテゴリ（システムデータまたはオブジェクトデータ）
* 各ボリュームのサイズ


ホストに StorageGRID ノードを導入するときは、この情報に加え、各物理ボリュームに Linux から割り当てられた永続的な名前を使用します。


NOTE: これらのボリュームをパーティショニング、フォーマット、マウントする必要はありません。ボリュームがホストから認識できることを確認するだけで済みます。


NOTE: メタデータ専用ストレージノードに必要なオブジェクトデータLUNは1つだけです。

「raw」特殊デバイスファイルを使用しない (`/dev/sdb`たとえば、）ボリューム名のリストを作成する際に、これらのファイルはホストのリブート時に変わることがあり、システムの適切な運用に影響します。iSCSI LUNとDevice Mapperマルチパスを使用している場合は、でマルチパスエイリアスを使用することを検討してください `/dev/mapper` ディレクトリ、特にSANトポロジに共有ストレージへの冗長ネットワークパスが含まれている場合。または、システムで作成されたのソフトリンクをで使用することもできます `/dev/disk/by-path/` をクリックします。

例：

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
結果はインストールごとに異なります。

これらのブロックストレージボリュームのそれぞれにわかりやすい名前を割り当てると、 StorageGRID の最初のインストールや以降のメンテナンスの手順が簡単になります。デバイスマッパーマルチパスドライバを使用して共有ストレージボリュームへのアクセスを冗長化する場合は、を使用することができます `alias` フィールドに入力します `/etc/multipath.conf` ファイル。

例：

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
これにより、でブロックデバイスとして表示されるエイリアスが原因 されます `/dev/mapper` ホスト上のディレクトリ。設定処理やメンテナンス処理の際にブロックストレージボリュームの指定が必要となったときに、わかりやすい、検証が容易な名前を指定できます。


NOTE: StorageGRID ノードの移行およびDevice Mapperマルチパスの使用をサポートするために共有ストレージを設定する場合は、共通のを作成してインストールできます `/etc/multipath.conf` 共同配置されたすべてのホスト。各ホストで使用する Docker ストレージボリュームが異なる点に注意してください。エイリアスを使用し、各 Docker ストレージボリュームの LUN のエイリアスにターゲットのホスト名を含めると覚えやすいので、この方法で設定することを推奨します。

.関連情報
link:storage-and-performance-requirements.html["ストレージとパフォーマンスの要件"]

link:node-container-migration-requirements.html["ノードコンテナの移行要件"]
