---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download ubuntu or debian installation files 
summary: StorageGRID インストールアーカイブをダウンロードし、必要なファイルを展開する必要があります。 
---
= StorageGRID インストールファイルをダウンロードして展開します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID インストールアーカイブをダウンロードし、必要なファイルを展開する必要があります。

.手順
. にアクセスします https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップの StorageGRID ダウンロードページ"^]。
. 最新のリリースをダウンロードするボタンを選択するか、ドロップダウンメニューから別のバージョンを選択して、「 * Go * 」を選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. Caution/MustRead文が表示された場合は'その文を読み'チェックボックスをオンにします
+

CAUTION: StorageGRID リリースのインストール後に、必要な修正プログラムを適用する必要があります。詳細については、を参照してください link:../maintain/storagegrid-hotfix-procedure.html["リカバリとメンテナンスの手順の Hotfix 手順"]

. [End User License Agreement]を読み、チェックボックスをオンにして、*[Accept & Continue]*を選択します。
+
選択したバージョンのダウンロードページが表示されます。このページには 3 つの列があります。

. Install StorageGRID * 列で、 Ubuntu または Debian の .tgz ファイルまたは .zip ファイルを選択します。
+

NOTE: を選択します `.zip` ファイルサービスラップトップでWindowsを実行している場合。

. アーカイブファイルを保存して展開します。
. 次のリストから必要なファイルを選択します。
+
必要なファイルは、計画したグリッドトポロジおよび StorageGRID グリッドの導入方法によって異なります。

+

NOTE: 次の表に示すパスは、展開されたインストールアーカイブによってインストールされた最上位ディレクトリに対する相対パスです。



[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./debs/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./debs/NLF000000.txt  a| 
テスト環境およびコンセプトの実証環境に使用できる、非本番環境のネットアップライセンスファイル。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイルのMD5チェックサム `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ホストサービスをインストールするための DEB パッケージ。



| 導入スクリプトツール | 説明 


| ./debs/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./debs/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./debs/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。このスクリプトは、Pingフェデレーションにも使用できます。



| ./debs/configure -storagegrid-sample.json という形式で指定します  a| 
で使用する構成ファイルの例 `configure-storagegrid.py` スクリプト：



| ./debs/configure -storagegrid-bank.json という形式で実行します  a| 
で使用する空の構成ファイル `configure-storagegrid.py` スクリプト：



| ./debs/extras /Ansible を実行します  a| 
StorageGRID コンテナ導入用の Ubuntu ホストまたは Debian ホストを設定するためのサンプルの Ansible のロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./debs/ storagegrid-ssoauth-azure.py  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./debs/storagegrid-ssoauth-azure.js  a| 
仲間によって呼び出されたヘルパースクリプト `storagegrid-ssoauth-azure.py` AzureとのSSO対話を実行するPythonスクリプト。



| ./debs/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===