= ストレージノードのホスト名を探します
:allow-uri-read: 




== ストレージノードのホスト名を探します

. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. を使用します `/etc/hosts` リストアされたストレージボリュームのストレージノードのホスト名を特定するファイル。グリッド内のすべてのノードのリストを表示するには、次のように入力します。 `cat /etc/hosts`。




== すべてのボリュームで障害が発生した場合はデータを修復します

すべてのストレージボリュームで障害が発生した場合は、ノード全体を修復します。レプリケートデータ、イレイジャーコーディング（ EC ）データ、またはその両方を使用するかどうかに応じて、 * レプリケートデータ * 、 * イレイジャーコーディング（ EC ）データ * 、またはその両方の手順を実行します。

一部のボリュームだけで障害が発生した場合は、に進みます <<一部のボリュームのみで障害が発生した場合はデータを修復します>>。


NOTE: 逃げられない `repair-data` 複数のノードに対して同時に処理を実行すること。複数のノードをリカバリする場合は、テクニカルサポートにお問い合わせください。

[role="tabbed-block"]
====
.レプリケートデータ
--
グリッドにレプリケートデータがある場合は、を使用します `repair-data start-replicated-node-repair` コマンドにを指定します `--nodes` オプション、ここで `--nodes` は、ストレージノード全体を修復するホスト名（システム名）です。

次のコマンドは、 SG-DC-SN3 というストレージノードにあるレプリケートデータを修復します。

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: オブジェクトデータのリストア時に、StorageGRID システムがレプリケートされたオブジェクトデータを見つけられない場合は、* Objects lost *アラートがトリガーされます。システム全体のストレージノードでアラートがトリガーされることがあります。損失の原因 と、リカバリが可能かどうかを確認する必要があります。を参照してください link:../troubleshoot/investigating-lost-objects.html["損失オブジェクトを調査する"]。

--
.イレイジャーコーディング（EC）データ
--
グリッドにイレイジャーコーディングデータが含まれている場合は、を使用します `repair-data start-ec-node-repair` コマンドにを指定します `--nodes` オプション、ここで `--nodes` は、ストレージノード全体を修復するホスト名（システム名）です。

次のコマンドは、 SG-DC-SN3 というストレージノードにあるイレイジャーコーディングデータを修復します。

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

一意のが返されます `repair ID` これを識別します `repair_data` 操作。これを使用します `repair ID` をクリックして、の進捗状況と結果を追跡します `repair_data` 操作。リカバリプロセスが完了しても、それ以外のフィードバックは返されません。


NOTE: イレイジャーコーディングデータの修復は、一部のストレージノードがオフライン状態で開始できます。修復はすべてのノードが使用可能になったあとに完了します。

--
====


== 一部のボリュームのみで障害が発生した場合はデータを修復します

一部のボリュームだけで障害が発生した場合は、影響を受けたボリュームを修復します。レプリケートデータ、イレイジャーコーディング（ EC ）データ、またはその両方を使用するかどうかに応じて、 * レプリケートデータ * 、 * イレイジャーコーディング（ EC ）データ * 、またはその両方の手順を実行します。

すべてのボリュームで障害が発生した場合は、に進みます <<すべてのボリュームで障害が発生した場合はデータを修復します>>。

ボリューム ID を 16 進数で入力します。例： `0000` は、最初のボリュームとです `000F` 16番目のボリュームです。1つのボリューム、一連のボリューム、または連続していない複数のボリュームを指定できます。

すべてのボリュームが同じストレージノードにある必要があります。複数のストレージノードのボリュームをリストアする必要がある場合は、テクニカルサポートにお問い合わせください。

[role="tabbed-block"]
====
.レプリケートデータ
--
グリッドにレプリケートデータがある場合は、を使用します `start-replicated-volume-repair` コマンドにを指定します `--nodes` ノードを識別するオプション（ `--nodes` はノードのホスト名です）。次に、を追加します `--volumes` または `--volume-range` 次の例に示すように、オプションを指定します。

*単一ボリューム*：レプリケートされたデータをボリュームにリストアします `0002` SG-DC-SN3という名前のストレージノードで次のように設定します。

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*ボリューム範囲*：レプリケートされたデータを範囲内のすべてのボリュームにリストアします `0003` 終了： `0009` SG-DC-SN3という名前のストレージノードで次のように設定します。

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*複数のボリュームが連続していません*：このコマンドは、複製されたデータをボリュームにリストアします `0001`、 `0005`および `0008` SG-DC-SN3という名前のストレージノードで次のように設定します。

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: オブジェクトデータのリストア時に、StorageGRID システムがレプリケートされたオブジェクトデータを見つけられない場合は、* Objects lost *アラートがトリガーされます。システム全体のストレージノードでアラートがトリガーされることがあります。アラートの概要 と推奨される対処方法をメモして、損失の原因 を特定し、リカバリが可能かどうかを判断します。

--
.イレイジャーコーディング（EC）データ
--
グリッドにイレイジャーコーディングデータが含まれている場合は、を使用します `start-ec-volume-repair` コマンドにを指定します `--nodes` ノードを識別するオプション（ `--nodes` はノードのホスト名です）。次に、を追加します `--volumes` または `--volume-range` 次の例に示すように、オプションを指定します。

*単一ボリューム*：このコマンドは、イレイジャーコーディングデータをボリュームにリストアします `0007` SG-DC-SN3という名前のストレージノードで次のように設定します。

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*ボリュームの範囲*：このコマンドは、範囲内のすべてのボリュームにイレイジャーコーディングデータをリストアします `0004` 終了： `0006` SG-DC-SN3という名前のストレージノードで次のように設定します。

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*複数のボリュームが連続していません*：このコマンドは、イレイジャーコーディングデータをボリュームにリストアします `000A`、 `000C`および `000E` SG-DC-SN3という名前のストレージノードで次のように設定します。

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

。 `repair-data` 一意のが返されます `repair ID` これを識別します `repair_data` 操作。これを使用します `repair ID` をクリックして、の進捗状況と結果を追跡します `repair_data` 操作。リカバリプロセスが完了しても、それ以外のフィードバックは返されません。


NOTE: イレイジャーコーディングデータの修復は、一部のストレージノードがオフライン状態で開始できます。修復はすべてのノードが使用可能になったあとに完了します。

--
====