---
permalink: tenant/object-metadata-included-in-metadata-notifications.html 
sidebar: sidebar 
keywords: object metadata notification 
summary: 次の表に、検索統合が有効になっている場合にデスティネーションエンドポイントに送信される JSON ドキュメント内のすべてのフィールドを示します。 
---
= メタデータ通知に含まれているオブジェクトメタデータ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、検索統合が有効になっている場合にデスティネーションエンドポイントに送信される JSON ドキュメント内のすべてのフィールドを示します。

ドキュメント名には、バケット名、オブジェクト名、バージョン ID （存在する場合）が含まれます。

[cols="1a,2a"]
|===
| を入力します | 項目名と概要 


 a| 
バケットとオブジェクトの情報
 a| 
`bucket`：バケットの名前



 a| 
`key`:オブジェクトキー名



 a| 
`versionID`：バージョン管理されたバケット内のオブジェクトのオブジェクトバージョン



 a| 
`region`：バケットリージョンなど `us-east-1`



 a| 
システムメタデータ
 a| 
`size`: HTTPクライアントに表示されるオブジェクトのサイズ(バイト単位)



 a| 
`md5`:オブジェクトハッシュ



 a| 
ユーザメタデータ
 a| 
`metadata`：オブジェクトのすべてのユーザメタデータをキーと値のペアとして格納

`key:value`



 a| 
タグ
 a| 
`tags`:オブジェクトに定義されているすべてのオブジェクトタグをキーと値のペアとして使用します

`key:value`

|===

NOTE: タグとユーザメタデータの場合、 StorageGRID は文字列または S3 イベント通知として Elasticsearch に日付と番号を渡します。これらの文字列を日付または数値として解釈するように Elasticsearch を設定するには、動的フィールドマッピングおよびマッピング日付形式に関する Elasticsearch の手順に従ってください。検索統合サービスを設定する前に、インデックスの動的フィールドマッピングを有効にする必要があります。ドキュメントのインデックス作成後は、インデックス内のドキュメントのフィールドタイプを編集することはできません。
