---
permalink: vmware/deploying-storagegrid-node-as-virtual-machine.html 
sidebar: sidebar 
keywords: how to deploy grid nodes in vsphere or vsphere web client 
summary: VMware vSphere Web Client を使用して、各グリッドノードを仮想マシンとして導入します。導入時に、各グリッドノードが作成されて、 1 つ以上の StorageGRID ネットワークに接続されます。 
---
= StorageGRID ノードを仮想マシンとして導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere Web Client を使用して、各グリッドノードを仮想マシンとして導入します。導入時に、各グリッドノードが作成されて、 1 つ以上の StorageGRID ネットワークに接続されます。

StorageGRID アプライアンスストレージノードを導入する必要がある場合は、を参照してください https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/deploying-appliance-storage-node.html["アプライアンスストレージノードを導入する"^]。

必要に応じて、ノードポートを再マッピングしたり、ノードの CPU やメモリの設定を増やしたりして、電源をオンにすることができます。

.作業を開始する前に
* 方法を確認しました link:index.html["設置を計画して準備"]では、ソフトウェア、 CPU 、 RAM 、ストレージとパフォーマンスの要件について理解しています。
* VMware vSphere ハイパーバイザーについて理解し、この環境で仮想マシンの導入を経験している必要があります。
+

NOTE: 。 `open-vm-tools` パッケージはVMware Toolsに似たオープンソースの実装で、StorageGRID 仮想マシンに含まれています。VMware Toolsを手動でインストールする必要はありません。

* VMware 用の正しいバージョンの StorageGRID インストールアーカイブをダウンロードして展開しておきます。
+

CAUTION: 拡張またはリカバリ処理の一環として新しいノードを導入する場合は、グリッドで現在実行されているバージョンの StorageGRID を使用する必要があります。

* StorageGRID 仮想マシンディスクが必要です (`.vmdk`）ファイル：


[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
----
* を使用することができます `.ovf` および `.mf` 導入するグリッドノードのタイプごとに、次のファイルを用意します。
+
[cols="1a,1a"]
|===
| ファイル名 | 説明 


| vsphere-primary-admin.ovf

vsphere-primary-admin.mf  a| 
プライマリ管理ノードのテンプレートファイルとマニフェストファイル。



| vsphere-non-primary-admin.ovf

vsphere-non-primary-admin.mf  a| 
非プライマリ管理ノードのテンプレートファイルとマニフェストファイル。



| vSphere-storage.ovf

vsphere-storage.mf  a| 
ストレージノードのテンプレートファイルとマニフェストファイル。



| vSphere-gateway.ovf

vsphere-gateway.mf  a| 
ゲートウェイノードのテンプレートファイルとマニフェストファイル。



| vsphere-archive.ovf

vsphere-archive.mf  a| 
アーカイブノードのテンプレートファイルとマニフェストファイル。

|===
* 。 `.vdmk`、 `.ovf`および `.mf` ファイルはすべて同じディレクトリにあります。
* 障害ドメインを最小限に抑えるための計画が必要です。たとえば、すべてのゲートウェイノードを 1 台の仮想マシンサーバに導入することは避けてください。
+

CAUTION: 本番環境では、1台の仮想マシンサーバで複数のストレージノードを実行しないでください。各ストレージノードに専用の仮想マシンホストを使用すると、分離された障害ドメインが提供されます。

* 拡張またはリカバリ処理の一環としてノードを導入する場合は、を使用します link:../expand/index.html["StorageGRID システムの拡張手順"] または link:../maintain/index.html["リカバリとメンテナンスの手順"]。
* NetApp ONTAP システムからストレージが割り当てられた仮想マシンとしてStorageGRID ノードを導入する場合は、ボリュームでFabricPool 階層化ポリシーが有効になっていないことを確認しておきます。たとえば、 StorageGRID ノードが VMware ホスト上の仮想マシンとして実行されている場合は、ノードのデータストアの作成元のボリュームで FabricPool 階層化ポリシーが有効になっていないことを確認します。StorageGRID ノードで使用するボリュームで FabricPool による階層化を無効にすることで、トラブルシューティングとストレージの処理がシンプルになります。
+

NOTE: StorageGRID を使用して StorageGRID に関連するデータを FabricPool 自体に階層化しないでください。StorageGRID データを StorageGRID に階層化すると、トラブルシューティングと運用がより複雑になります。



.このタスクについて
最初に VMware ノードを導入するとき、拡張時に新しい VMware ノードを追加するとき、またはリカバリ処理の一環として VMware ノードを交換するときは、次の手順に従います。手順でメモした場合を除き、ノード導入手順 は管理ノード、ストレージノード、ゲートウェイノード、アーカイブノードなど、すべてのタイプのノードで同じです。

新しい StorageGRID システムを設置する場合は、次の手順を実行します。

* プライマリ管理ノードは、他のグリッドノードを導入する前に導入する必要があります。
* 各仮想マシンがグリッドネットワーク経由でプライマリ管理ノードに接続できることを確認する必要があります。
* グリッドを設定する前に、すべてのグリッドノードを導入する必要があります。


拡張またはリカバリ処理を実行する場合は、次の手順を実行します。

* 新しい仮想マシンがグリッドネットワーク経由でプライマリ管理ノードに接続できることを確認する必要があります。


ノードのポートを再マッピングする必要がある場合は、ポートの再マッピングの設定が完了するまで新しいノードの電源をオンにしないでください。

.手順
. vCenter を使用して OVF テンプレートを導入
+
URL を指定する場合は、次のファイルを含むフォルダを指定します。それ以外の場合は、ローカルディレクトリから各ファイルを選択します。

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-_node_.ovf
vsphere-_node_.mf
----
+
たとえば、導入する最初のノードがこのファイルに含まれている場合は、次のファイルを使用して StorageGRID システムのプライマリ管理ノードを導入します。

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-primary-admin.ovf
vsphere-primary-admin.mf
----
. 仮想マシンの名前を指定します。
+
標準的には、仮想マシンとグリッドノードに同じ名前を使用します。

. 仮想マシンを適切な vApp またはリソースプールに配置します。
. プライマリ管理ノードを導入する場合は、エンドユーザライセンス契約を読んで同意します。
+
vCenter のバージョンによっては、使用する手順の順序は、エンドユーザライセンス契約を承諾し、仮想マシンの名前を指定し、データストアを選択する場合とで異なります。

. 仮想マシンのストレージを選択します。
+
リカバリ処理の一環としてノードを導入する場合は、の手順を実行します <<step_recovery_storage,ストレージリカバリ手順>> 新しい仮想ディスクを追加するには、障害が発生したグリッドノードから仮想ハードディスクを再接続するか、その両方を実行します。

+
ストレージノードを導入する際は、ストレージボリュームを 3 個以上使用し、各ストレージボリュームのサイズを 4TB 以上にします。ボリューム 0 に少なくとも 4TB 割り当てる必要があります。

+

NOTE: ストレージノードの .ovf ファイルは、ストレージ用の複数の VMDK を定義します。これらの VMDK がストレージ要件を満たしていない場合は、ノードの電源を入れる前に、それらの VMDK を削除し、ストレージに適切な VMDK または RDM を割り当てる必要があります。VMware 環境で一般に使用され、管理も容易であるのは VMDK ですが、大きなオブジェクトサイズ（たとえば 100MB 超）を使用するワークロードのパフォーマンスは RDM の方が高くなります。

+

NOTE: 一部の StorageGRID 環境では、一般的な仮想ワークロードよりも大容量のアクティブなストレージボリュームを使用する場合があります。ハイパーバイザーパラメータの調整が必要になる場合があります。 `MaxAddressableSpaceTB`をクリックすると、最適なパフォーマンスが得られます。パフォーマンスが低下する場合は、仮想化のサポートリソースに問い合わせて、ワークロード固有の構成調整によって環境がメリットを受けるかどうかを確認してください。

. ネットワークを選択します。
+
各ソースネットワークのデスティネーションネットワークを選択して、ノードで使用する StorageGRID ネットワークを決定します。

+
** グリッドネットワークは必須です。vSphere 環境でデスティネーションネットワークを選択する必要があります。
** 管理ネットワークを使用する場合は、 vSphere 環境で別のデスティネーションネットワークを選択します。管理ネットワークを使用しない場合は、グリッドネットワークに対して選択したデスティネーションと同じデスティネーションを選択します。
** クライアントネットワークを使用する場合は、 vSphere 環境で別のデスティネーションネットワークを選択します。クライアントネットワークを使用しない場合は、グリッドネットワークに対して選択したデスティネーションと同じデスティネーションを選択します。


. [テンプレートのカスタマイズ]*で、必要なStorageGRIDノードプロパティを構成します。
+
.. ノード名 * を入力します。
+

NOTE: グリッドノードをリカバリする場合は、リカバリするノードの名前を入力する必要があります。

.. 新しいノードがグリッドに追加される前にVMコンソールにアクセスしたりSSHを使用したりできるように、* Temporary installation password *ドロップダウンを使用して一時的なインストールパスワードを指定します。
+

NOTE: 一時インストールパスワードは、ノードのインストール時にのみ使用されます。グリッドに追加されたノードには、 link:../admin/change-node-console.html["ノードのコンソールパスワード"]が表示されます。 `Passwords.txt` リカバリパッケージ内のファイル。

+
*** *ノード名を使用*：*ノード名*フィールドに入力した値は、一時的なインストールパスワードとして使用されます。
*** *カスタムパスワードを使用*：カスタムパスワードを一時的なインストールパスワードとして使用します。
*** *パスワードを無効にする*:一時的なインストールパスワードは使用されません。インストールの問題をデバッグするためにVMにアクセスする必要がある場合は、を参照してください。 link:troubleshooting-installation-issues.html["インストールに関する問題のトラブルシューティング"]。


.. *カスタムパスワードを使用*を選択した場合は、*カスタムパスワード*フィールドで使用する一時インストールパスワードを指定します。
.. * グリッドネットワーク（ eth0 ） * セクションで、 * グリッドネットワーク IP 設定 * に静的または DHCP を選択します。
+
*** 静的を選択した場合は、 * グリッドネットワーク IP * 、 * グリッドネットワークマスク * 、 * グリッドネットワークゲートウェイ * 、 * グリッドネットワーク MTU * を入力します。
*** DHCP を選択した場合は、 * グリッドネットワーク IP * 、 * グリッドネットワークマスク * 、 * グリッドネットワークゲートウェイ * が自動的に割り当てられます。


.. 「 * Primary Admin IP * 」フィールドに、グリッドネットワークのプライマリ管理ノードの IP アドレスを入力します。
+

NOTE: この手順は、導入するノードがプライマリ管理ノードの場合は必要ありません。

+
プライマリ管理ノードの IP アドレスを省略すると、プライマリ管理ノードまたは ADMIN_IP が設定された少なくとも 1 つのグリッドノードが同じサブネットにある場合は、 IP アドレスが自動的に検出されます。ただし、ここでプライマリ管理ノードの IP アドレスを設定することを推奨します。

.. 「 * Admin Network （ eth1 ） * 」セクションで、「 * Admin network IP configuration * 」に対して「 static 」、「 dhcp 」、または「 disabled 」を選択します。
+
*** 管理ネットワークを使用しない場合は、[DISABLED]を選択し、[Admin Network IP]に「* 0.0.0.0 *」と入力します。他のフィールドは空白のままにすることができます。
*** 静的を選択した場合は、 * 管理ネットワーク IP * 、 * 管理ネットワークマスク * 、 * 管理ネットワークゲートウェイ * 、 * 管理ネットワーク MTU * を入力します。
*** 静的を選択した場合は、 * 管理ネットワークの外部サブネットリスト * を入力します。ゲートウェイも設定する必要があります。
*** DHCP を選択した場合は、 * 管理ネットワーク IP * 、 * 管理ネットワークマスク * 、および * 管理ネットワークゲートウェイ * が自動的に割り当てられます。


.. クライアントネットワーク（ eth2 ） * セクションで、 * クライアントネットワーク IP 構成 * の静的、 DHCP 、または無効を選択します。
+
*** クライアントネットワークを使用しない場合は、[DISABLED]を選択し、[Client Network IP]に「* 0.0.0.0 *」と入力します。他のフィールドは空白のままにすることができます。
*** 静的を選択した場合は、 * クライアントネットワーク IP * 、 * クライアントネットワークマスク * 、 * クライアントネットワークゲートウェイ * 、および * クライアントネットワーク MTU * を入力します。
*** DHCP を選択した場合は、 * クライアントネットワーク IP * 、 * クライアントネットワークマスク * 、および * クライアントネットワークゲートウェイ * が自動的に割り当てられます。




. 仮想マシンの設定を確認し、必要な変更を行います。
. 完了する準備ができたら、 [ 完了 ] を選択して仮想マシンのアップロードを開始します。
. [[step_recovery_storage] - リカバリ処理の一環としてこのノードを導入し、フルノードリカバリではない場合は、導入の完了後に次の手順を実行します。
+
.. 仮想マシンを右クリックし、 * 設定の編集 * を選択します。
.. ストレージに指定されている各デフォルト仮想ハードディスクを選択し、 * 削除 * を選択します。
.. データリカバリの状況に応じて、ストレージ要件に従って新しい仮想ディスクを追加し、以前に削除した障害グリッドノードから保存した仮想ハードディスクを再接続するか、またはその両方を実行します。
+
次の重要なガイドラインに注意してください。

+
*** 新しいディスクを追加する場合は、ノードのリカバリ前に使用していたものと同じタイプのストレージデバイスを使用する必要があります。
*** ストレージノードの .ovf ファイルは、ストレージ用の複数の VMDK を定義します。これらの VMDK がストレージ要件を満たしていない場合は、ノードの電源を入れる前に、それらの VMDK を削除し、ストレージに適切な VMDK または RDM を割り当てる必要があります。VMware 環境で一般に使用され、管理も容易であるのは VMDK ですが、大きなオブジェクトサイズ（たとえば 100MB 超）を使用するワークロードのパフォーマンスは RDM の方が高くなります。




. このノードで使用されるポートを再マッピングする必要がある場合は、次の手順を実行します。
+
ポートの再マッピングが必要となるのは、 StorageGRID で使用される 1 つ以上のポートへのアクセスがエンタープライズネットワークポリシーによって制限される場合です。を参照してください link:../network/index.html["ネットワークのガイドライン"] StorageGRID で使用されるポート用。

+

NOTE: ロードバランサエンドポイントで使用されるポートは再マッピングしないでください。

+
.. 新しい VM を選択します。
.. [ 構成 ] タブで、 [ * 設定 * > * vApp オプション * ] を選択します。vapp Options * の場所は、 vCenter のバージョンによって異なります。
.. プロパティ * テーブルで、 PORT_REMAP_INBOUND および PORT_REMAP を確認します。
.. ポートのインバウンド通信とアウトバウンド通信の両方を対称的にマッピングするには、 * PORT_REMAP * を選択します。
+

NOTE: PORT_REMAP のみを設定すると、インバウンド通信とアウトバウンド通信の両方で環境 を指定したマッピングが適用されます。PORT_REMAP_INBOUND を併せて指定した場合は、 PORT_REMAP がアウトバウンド通信のみに適用されます。

+
... 表の一番上までスクロールし、 * Edit * を選択します。
... [ タイプ ] タブで、 [ ユーザー設定可能 *] を選択し、 [ 保存 *] を選択します。
... 「 * 値の設定 * 」を選択します。
... ポートマッピングを入力します。
+
`<network type>/<protocol>/<default port used by grid node>/<new port>`

+
`<network type>` は、grid、admin、client、およびです `<protocol>` は、tcpまたはudpです。

+
たとえば、 ssh トラフィックをポート 22 からポート 3022 に再マッピングするには、次のように入力します。

+
`client/tcp/22/3022`

... 「 * OK 」を選択します。


.. ノードへのインバウンド通信に使用するポートを指定するには、 * port_remap_inbound * を選択します。
+

NOTE: PORT_REMAP_INBOUNDを指定し、PORT_REMAPに値を指定しなかった場合、ポートのアウトバウンド通信は変更されません。

+
... 表の一番上までスクロールし、 * Edit * を選択します。
... [ タイプ ] タブで、 [ ユーザー設定可能 *] を選択し、 [ 保存 *] を選択します。
... 「 * 値の設定 * 」を選択します。
... ポートマッピングを入力します。
+
`<network type>/<protocol>/<remapped inbound port>/<default inbound port used by grid node>`

+
`<network type>` は、grid、admin、client、およびです `<protocol>` は、tcpまたはudpです。

+
たとえば、ポート 3022 に送信されるインバウンドの SSH トラフィックを再マッピングしてグリッドノードがポート 22 で受信するようにするには、次のように入力します。

+
`client/tcp/3022/22`

... 「 * OK 」を選択します




. ノードの CPU またはメモリをデフォルトの設定から増やす場合は、次の手順を実行します。
+
.. 仮想マシンを右クリックし、 * 設定の編集 * を選択します。
.. CPU の数またはメモリの容量を必要に応じて変更します。
+
[ メモリ予約 * ] を、仮想マシンに割り当てられた * メモリ * と同じサイズに設定します。

.. 「 * OK 」を選択します。


. 仮想マシンの電源をオンにします。


.完了後
このノードを拡張またはリカバリ用手順 の一部として導入した場合は、その手順に戻って手順 を完了します。
