---
permalink: vmware/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッドノードごとに仮想マシンが1つ必要です。 
---
= VMwareのソフトウェア要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンを使用して、あらゆるタイプのStorageGRIDノードをホストできます。グリッドノードごとに仮想マシンが1つ必要です。



== VMware vSphere ハイパーバイザー

準備が整った物理サーバに VMware vSphere ハイパーバイザーをインストールする必要があります。VMware ソフトウェアをインストールする前に、ハードウェアが正しく設定されている必要があります（ファームウェアバージョンと BIOS 設定を含む）。

* インストールする StorageGRID システムのネットワークをサポートできるように、ハイパーバイザーのネットワークを設定します。
+
link:../network/index.html["ネットワークのガイドライン"]

* データストアが、グリッドノードをホストするために必要な仮想マシンと仮想ディスクに十分な大きさであることを確認します。
* 複数のデータストアを作成する場合は、仮想マシン作成時に各グリッドノードに使用するデータストアを簡単に識別できるよう、各データストアに名前を付けます。




== ESX ホストの設定要件


CAUTION: 各 ESX ホストでネットワークタイムプロトコル（ NTP ）を適切に設定する必要があります。ホストの時刻が正しくないと、データ損失などのマイナスの影響が生じる可能性があります。



== VMware の設定要件

StorageGRIDノードを導入する前に、VMware vSphereとvCenterをインストールして設定する必要があります。

サポートされるVMware vSphere HypervisorおよびVMware vCenter Serverソフトウェアのバージョンについては、を参照してください https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool で確認できます"^]。

これらの VMware 製品をインストールするために必要な手順については、 VMware のドキュメントを参照してください。



== その他の必要なソフトウェア

VMwareにStorageGRIDをインストールするには、いくつかのサードパーティソフトウェアパッケージをインストールする必要があります。一部のサポートされているLinuxディストリビューションには、デフォルトでこれらのパッケージが含まれていません。StorageGRIDのインストールがテストされているソフトウェアパッケージのバージョンには、このページに記載されているバージョンも含まれます。


NOTE: これらのパッケージのいずれかを必要とするLinuxディストリビューションおよびコンテナランタイムインストールオプションを選択し、それらがLinuxディストリビューションによって自動的にインストールされない場合は、プロバイダまたはLinuxディストリビューションのサポートベンダーから入手可能な場合は、ここに記載されているいずれかのバージョンをインストールします。それ以外の場合は、ベンダーが提供しているデフォルトのパッケージバージョンを使用します。


NOTE: すべてのインストールオプションには、PodmanまたはDockerのいずれかが必要です。両方のパッケージをインストールしないでください。インストールオプションに必要なパッケージのみをインストールします。



=== テスト対象のPythonバージョン

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




=== テスト済みのPodmanバージョン

* 3.2.3-0
* 3.4.4 + DS1
* 4.1.1-7
* 4.2.0-11
* 4.3.1 + DS1-8 + B1
* 4.4.1-8
* 4.4.1-12




=== テスト済みのDockerバージョン


IMPORTANT: Dockerのサポートは廃止され、今後のリリースで削除される予定です。

* Docker - CE 20.10.7
* Docker - CE 20.10.20-3
* Docker - CE 23.0.6-1
* Docker - CE 24.0.2-1
* Docker - CE 24.0.4-1
* Docker - CE 24.0.5-1
* Docker - CE 24.0.7-1
* 1.5-2

