---
permalink: admin/adding-nfs-audit-client-to-audit-share.html 
sidebar: sidebar 
keywords: nfs, audit client, audit share 
summary: NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。新しい NFS 監査クライアントに監査共有へのアクセスを許可するには、そのクライアントの IP アドレスを監査共有に追加します。 
---
= 監査共有に NFS 監査クライアントを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。新しい NFS 監査クライアントに監査共有へのアクセスを許可するには、そのクライアントの IP アドレスを監査共有に追加します。


NOTE: NFSのサポートは廃止され、今後のリリースで削除される予定です。

.作業を開始する前に
* を使用することができます `Passwords.txt` root / adminアカウントのパスワードが設定されたファイル。
* これで、 `Configuration.txt` ファイル（リカバリパッケージに含まれています）。
* 監査クライアントが NFS バージョン 3 （ NFSv3 ）を使用している。


.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. NFS設定ユーティリティを起動します。 `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 入力するコマンド `add-ip-to-share`
+
管理ノードで有効になっている NFS 監査共有のリストが表示されます。監査共有はのように表示されます。 `/var/local/log`

. 監査共有の番号を入力します。 `_audit_share_number_`
. プロンプトが表示されたら、監査共有用の監査クライアントのIPアドレスまたはIPアドレス範囲を入力します。 `_client_IP_address_`
+
監査クライアントが監査共有に追加されます。

. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

. 監査共有に追加する監査クライアントごとに、この手順を繰り返します。
. 必要に応じて、設定を確認します。 `validate-config`
+
サービスがチェックされて表示されます。

+
.. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。



. NFS設定ユーティリティを閉じます。 `exit`
. StorageGRID 環境が単一サイトの場合は、次の手順に進みます。
+
StorageGRID 環境で他のサイトに管理ノードが含まれている場合は、必要に応じてこれらの監査共有を有効にします。

+
.. サイトの管理ノードにリモートからログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。


.. 同じ手順を繰り返して、管理ノードごとに監査共有を設定します。
.. リモート管理ノードへのリモートのSecure Shellログインを終了します。 `exit`


. コマンドシェルからログアウトします。 `exit`

