---
permalink: admin/archiving-to-tape-through-tsm-middleware.html 
sidebar: sidebar 
keywords: tivoli storage manager, tsm server, archive node, tape 
summary: Tivoli Storage Manager サーバ（ TSM ）をターゲットとするようにアーカイブノードを構成できます。 TSM サーバは、テープライブラリを含むランダムまたはシーケンシャルアクセスのストレージデバイスとの間でオブジェクトデータを格納および読み出すための論理インターフェイスです。 
---
= TSM ミドルウェア経由でのテープへのアーカイブ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tivoli Storage Manager （ TSM ）サーバをターゲットとするようにアーカイブノードを構成できます。 TSM サーバは、テープライブラリを含むランダムまたはシーケンシャルアクセスのストレージデバイスとの間でオブジェクトデータを格納および読み出すための論理インターフェイスです。

アーカイブノードの ARC サービスは TSM サーバに対するクライアントとして機能し、 Tivoli Storage Manager をアーカイブストレージシステムと通信するためのミドルウェアとして使用します。

[CAUTION]
====
アーカイブノードのサポートは廃止され、今後のリリースで削除される予定です。S3 API を使用してアーカイブノードから外部のアーカイブストレージシステムにオブジェクトを移動する処理は、より多くの機能を提供する ILM Cloud Storage Pools に置き換えられました。

[Cloud Tiering - Simple Storage Service（S3）]オプションも廃止されました。このオプションのアーカイブノードを現在使用している場合は、 link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["オブジェクトをクラウドストレージプールに移行します"] 代わりに、

また、StorageGRID 11.7以前では、アクティブなILMポリシーからアーカイブノードを削除する必要があります。アーカイブノードに格納されているオブジェクトデータを削除すると、将来のアップグレードが簡単になります。を参照してください link:../ilm/working-with-ilm-rules-and-ilm-policies.html["ILMルールおよびILMポリシーの操作"]。

====


== TSM 管理クラス

TSM ミドルウェアによって定義された管理クラスは、 TSM のバックアップおよびアーカイブ処理がどのように機能するかを示します。この管理クラスを使用して、 TSM サーバによって適用されるコンテンツ用のルールを指定できます。これらのルールは StorageGRID システムの ILM ポリシーとは独立して機能します。オブジェクトは永続的に格納され、アーカイブノードによっていつでも読み出し可能であるという StorageGRID システムの要件と矛盾しないことが必要です。アーカイブノードから TSM サーバにオブジェクトデータが送信されたあと、 TSM サーバが管理するテープにオブジェクトデータが格納される間、 TSM のライフサイクルと保持のルールが適用されます。

TSM 管理クラスは、アーカイブノードから TSM サーバにオブジェクトデータが送信されたあと、データの場所または保持のルールを適用するために TSM サーバで使用されます。たとえば、データベースのバックアップとして識別されたオブジェクト（新しいデータで上書き可能な一時的コンテンツ）を、アプリケーションデータ（無期限に保持する必要のある固定コンテンツ）とは別の方法で処理できます。
