---
permalink: admin/archive-node-configuration-and-operation.html 
sidebar: sidebar 
keywords: archive node configuration 
summary: StorageGRID システムは、オブジェクトが無期限に保存され、常にアクセス可能な場所として、アーカイブノードを管理します。 
---
= アーカイブノードの設定と処理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムは、オブジェクトが無期限に保存され、常にアクセス可能な場所として、アーカイブノードを管理します。

オブジェクトが取り込まれると、StorageGRIDシステムに定義されている情報ライフサイクル管理（ILM）ルールに基づいて、アーカイブノードを含む必要なすべての場所にコピーが作成されます。アーカイブノードは TSM サーバに対するクライアントとして機能し、 StorageGRID ソフトウェアのインストール時に TSM クライアントライブラリがアーカイブノードにインストールされます。ストレージ用にアーカイブノードに転送されたオブジェクトデータは、 TSM サーバに直接保存されます。TSM サーバへの保存前にアーカイブノードがオブジェクトデータをステージングしたり、オブジェクトを集約したりすることはありません。ただし、データ速度が保証されれば、アーカイブノードから TSM サーバに 1 回のトランザクションで複数のコピーを送信できます。

アーカイブノードから TSM サーバに保存されたオブジェクトデータは、ライフサイクル / 保持ポリシーに従って TSM サーバで管理されます。これらの保持ポリシーは、アーカイブノードの処理に対応するように定義する必要があります。つまり、アーカイブノードによって保存されたオブジェクトデータは、アーカイブノードによって削除されないかぎり、無期限に保存されていつでもアーカイブノードからアクセスできる必要があります。

StorageGRID システムの ILM ルールと TSM サーバのライフサイクル / 保持ポリシーの間に接続は確立されていません。それぞれが互いに独立して動作します。ただし、各オブジェクトが StorageGRID システムに取り込まれる際に、そのオブジェクトに TSM 管理クラスを割り当てることができます。この管理クラスは、オブジェクトデータとともに TSM サーバに渡されます。オブジェクトタイプごとに異なる管理クラスを割り当てると、オブジェクトデータを別々のストレージプールに配置したり、必要に応じて異なる移行ポリシーや保持ポリシーを適用したりするように TSM サーバを設定できます。たとえば、データベースのバックアップとして識別されたオブジェクト（新しいデータで上書き可能な一時的コンテンツ）を、アプリケーションデータ（無期限に保持する必要のある固定コンテンツ）とは別の方法で処理できます。

アーカイブノードは新規または既存の TSM サーバと統合でき、専用の TSM サーバは必要ありません。TSM サーバは、サイズが予想される最大負荷に対応していれば、他のクライアントと共有できます。TSM は、アーカイブノードとは別のサーバまたは仮想マシンにインストールする必要があります。

複数のアーカイブノードから同じ TSM サーバに書き込むように設定できますが、この設定が推奨されるのは、アーカイブノードが異なるデータセットを TSM サーバに書き込む場合のみです。各アーカイブノードが同じオブジェクトデータのコピーをアーカイブに書き込む場合は、複数のアーカイブノードを同じ TSM サーバに書き込む設定は推奨されません。後者のシナリオでは、本来ならばオブジェクトデータの独立した、冗長コピーとなるはずが、両方のコピーが単一点障害（ TSM サーバ）となります。

アーカイブノードはTSMのHierarchical Storage Management（HSM；階層型ストレージ管理）コンポーネントを使用しません。
