---
permalink: admin/configuration-best-practices.html 
sidebar: sidebar 
keywords: tsm configuration, tivoli storage manager, archive to tape 
summary: TSM サーバをサイジングおよび設定する場合、アーカイブノードとの連携を最適化するベストプラクティスがあります。 
---
= 構成のベストプラクティス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
TSM サーバをサイジングおよび設定する場合、アーカイブノードとの連携を最適化するベストプラクティスがあります。

TSM サーバをサイジングおよび設定する際には、次の点を考慮する必要があります。

* アーカイブノードは TSM サーバに保存する前にオブジェクトを集約しないため、アーカイブノードに書き込まれるすべてのオブジェクトへの参照を格納できるように TSM データベースをサイジングする必要があります。
* アーカイブノードソフトウェアでは、テープやその他のリムーバブルメディアにオブジェクトを直接書き込む際のレイテンシを許容できません。したがって TSM サーバには、リムーバブルメディアが使用されるたびにアーカイブノードが最初にデータを保存する初期ストレージ用のディスクストレージプールを設定する必要があります。
* イベントベースの保持を使用するには、 TSM の保持ポリシーを設定する必要があります。アーカイブノードでは、作成ベースの TSM 保持ポリシーはサポートされません。保持ポリシーでは、推奨設定である retmin=0 および retver=0 （アーカイブノードが保持イベントをトリガーしたときに保持が開始され、その後 0 日間保持される）を使用してください。ただし、これらの retmin 値および retver 値はオプションです。


ディスクプールは、テーププールにデータを移行するように設定する必要があります（つまり、テーププールをディスクプールの NXTSTGPOOL に設定します）。テーププールは、両方のプールに同時に書き込みを行うディスクプールのコピープールとして設定しないでください（つまり、テーププールをディスクプールのCOPYSTGPOOLにすることはできません）。アーカイブノードデータを含むテープのオフラインコピーを作成するには、 TSM サーバの 2 つ目のテーププールとして、アーカイブノードのデータ用に使用されるテーププールのコピープールを設定します。
