---
permalink: admin/configuring-audit-client-access.html 
sidebar: sidebar 
keywords: audit client, ams, audit management service 
summary: 管理ノードは、 Audit Management System （ AMS ）サービスを介して、監査対象のすべてのシステムイベントを、監査共有からアクセス可能なログファイルに記録します。監査共有はインストール時に各管理ノードに追加されます。監査共有は読み取り専用の共有として自動的に有効になります。 
---
= NFSの監査クライアントアクセスを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ノードは、 Audit Management System （ AMS ）サービスを介して、監査対象のすべてのシステムイベントを、監査共有からアクセス可能なログファイルに記録します。監査共有はインストール時に各管理ノードに追加されます。監査共有は読み取り専用の共有として自動的に有効になります。


NOTE: NFSのサポートは廃止され、今後のリリースで削除される予定です。

監査ログにアクセスするには、NFSの監査共有へのクライアントアクセスを設定します。または、できます link:../monitor/considerations-for-external-syslog-server.html["外部syslogサーバを使用します"]。

StorageGRID システムは、確認応答を使用して、ログファイルに書き込まれる前に監査メッセージが失われないようにします。AMS サービスまたは中間の監査リレーサービスがメッセージの制御を確認するまで、メッセージはサービスのキューに残ります。詳細については、を参照してください link:../audit/index.html["監査ログを確認します"]。

.作業を開始する前に
* を使用することができます `Passwords.txt` root / adminパスワードが設定されたファイル。
* を使用することができます `Configuration.txt` ファイル（リカバリパッケージに含まれています）。
* 監査クライアントが NFS バージョン 3 （ NFSv3 ）を使用している。


.このタスクについて
この手順 は、監査メッセージの取得先である StorageGRID 環境内の管理ノードごとに実行します。

.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. すべてのサービスの状態が「 Running 」または「 Verified 」であることを確認します。入力するコマンド `storagegrid-status`
+
「Running」または「Verified」と表示されないサービスがある場合は、問題を解決してから続行してください。

. コマンドラインに戻ります。Ctrl キーを押しながら * C キーを押します。
. NFS 設定ユーティリティを起動します。入力するコマンド `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 監査クライアントを追加します。 `add-audit-share`
+
.. プロンプトが表示されたら、監査共有用の監査クライアントのIPアドレスまたはIPアドレス範囲を入力します。 `client_IP_address`
.. プロンプトが表示されたら、 * Enter * を押します。


. 複数の監査クライアントに監査共有へのアクセスを許可する場合は、ユーザのIPアドレスを追加します。 `add-ip-to-share`
+
.. 監査共有の番号を入力します。 `_audit_share_number_`
.. プロンプトが表示されたら、監査共有用の監査クライアントのIPアドレスまたはIPアドレス範囲を入力します。 `_client_IP_address_`
.. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

.. 監査共有に追加する監査クライアントごとに、上記の手順を繰り返します。


. 必要に応じて、設定を確認します。
+
.. 次のように入力します。 `validate-config`
+
サービスがチェックされて表示されます。

.. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

.. NFS設定ユーティリティを閉じます。 `exit`


. 他のサイトで監査共有を有効にする必要があるかどうかを確認します。
+
** StorageGRID 環境が単一サイトの場合は、次の手順に進みます。
** StorageGRID 環境で他のサイトに管理ノードが含まれている場合は、必要に応じてこれらの監査共有を有効にします。
+
... サイトの管理ノードにリモートからログインします。
+
.... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.... に記載されているパスワードを入力します `Passwords.txt` ファイル。
.... 次のコマンドを入力してrootに切り替えます。 `su -`
.... に記載されているパスワードを入力します `Passwords.txt` ファイル。


... 同じ手順を繰り返して、追加の管理ノードごとに監査共有を設定します。
... リモート管理ノードへのリモートの Secure Shell ログインを終了します。入力するコマンド `exit`




. コマンドシェルからログアウトします。 `exit`
+
NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。新しい NFS 監査クライアントに共有に IP アドレスを追加して監査共有へのアクセスを許可するか、または IP アドレスを削除して既存の監査クライアントを削除します。


