---
permalink: admin/defining-domain-policy-and-registering-node.html 
sidebar: sidebar 
keywords: domain policy, tsm, tivoli storage manager 
summary: アーカイブノードから保存されたデータ用に TSM 管理クラスを使用するドメインポリシーを定義し、そのドメインポリシーを使用するようにノードを登録する必要があります。 
---
= ドメインポリシーを定義し、ノードを登録します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アーカイブノードから保存されたデータ用に TSM 管理クラスを使用するドメインポリシーを定義し、そのドメインポリシーを使用するようにノードを登録する必要があります。


NOTE: Tivoli Storage Manager （ TSM ）でアーカイブノードのクライアントパスワードの期限が切れると、アーカイブノードのプロセスでメモリリークが発生する可能性があります。アーカイブノードのクライアントユーザ名 / パスワードの期限が切れないように TSM サーバを設定してください。

アーカイブノードとして使用するノードを TSM サーバに登録する（または既存のノードを更新する）場合は、そのノードが書き込み処理に使用できるマウントポイントの数を指定する必要があります。そのためには、 REGISTER NODE コマンドで MAXNUMMP パラメータを指定します。通常、マウントポイントの数は、アーカイブノードに割り当てられているテープドライブのヘッド数と同じです。TSMサーバ上のMAXNUMMPに指定する数は、アーカイブノードの* ARC *>* Target *>* Configuration *>* Main *>* Maximum Store Sessions *に設定されている値以上である必要があります。 アーカイブノードでは同時格納セッションはサポートされないため、この値は0または1に設定されています。

TSM サーバ用に設定した MAXSESSIONS の値によって、すべてのクライアントアプリケーションが TSM サーバに対して開くことのできる最大セッション数が制御されます。TSM で指定する MAXSESSIONS の値は、アーカイブノードの Grid Manager で * ARC * > * Target * > * Configuration * > * Main * > * Sessions * に指定されている値以上である必要があります。アーカイブノードは、最大でマウントポイントごとに 1 つのセッションと少数（ 5 つ未満）の追加セッションを同時に作成します。

アーカイブノードに割り当てられているTSMノードは、カスタムドメインポリシーを使用します `tsm-domain`。。 `tsm-domain` ドメインポリシーは、「標準」ドメインポリシーの変更されたバージョンであり、テープに書き込むように設定され、アーカイブ先がStorageGRIDシステムのストレージプールに設定されています。 (`_SGWSDiskPool_`）。


NOTE: ドメインポリシーを作成およびアクティブ化するには、管理者権限を使用して TSM サーバにログインし、 dsmadmc ツールを使用する必要があります。
