---
permalink: admin/guidelines-for-storagegrid-networks.html 
sidebar: sidebar 
keywords: admin network, client network, grid network, access interface, trunk interface 
summary: StorageGRID では、グリッドノードあたり最大 3 つのネットワークインターフェイスがサポートされ、各グリッドノードのネットワークをセキュリティやアクセスの要件に応じて設定することができます。 
---
= StorageGRID ネットワークのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドマネージャを使用して、 StorageGRID のネットワークと接続を設定および管理できます。

を参照してください link:configuring-client-connections.html["S3 および Swift クライアント接続を設定します"] を参照して、 S3 または Swift クライアントを接続する方法を確認してください。



== デフォルトの StorageGRID ネットワーク

StorageGRID では、デフォルトでグリッドノードあたり 3 つのネットワークインターフェイスがサポートされ、各グリッドノードのネットワークをセキュリティやアクセスの要件に応じて設定することができます。

ネットワークトポロジの詳細については、を参照してください link:../network/index.html["ネットワークのガイドライン"]。



=== Grid ネットワーク

必須グリッドネットワークは、すべての内部 StorageGRID トラフィックに使用されます。このネットワークによって、グリッド内のすべてのノードが、すべてのサイトおよびサブネットにわたって相互に接続されます。



=== 管理ネットワーク

任意。通常、管理ネットワークはシステムの管理とメンテナンスに使用されます。クライアントプロトコルアクセスにも使用できます。管理ネットワークは通常はプライベートネットワークであり、サイト間でルーティング可能にする必要はありません。



=== クライアントネットワーク

任意。クライアントネットワークはオープンネットワークで、主に S3 および Swift クライアントアプリケーションへのアクセスに使用されます。そのため、グリッドネットワークを分離してセキュリティを確保できます。クライアントネットワークは、ローカルゲートウェイ経由でアクセス可能なすべてのサブネットと通信できます。



== ガイドライン

* StorageGRIDノードには、割り当て先のネットワークごとに専用のネットワークインターフェイス、IPアドレス、サブネットマスク、およびゲートウェイが必要です。
* 1つのグリッドノードに複数のインターフェイスを設定することはできません。
* 各ネットワークのグリッドノードごとに、単一のゲートウェイがサポートされます。このゲートウェイはノードと同じサブネット上に配置する必要があります。必要に応じて、より複雑なルーティングをゲートウェイに実装できます。
* 各ノードでは、各ネットワークが特定のネットワークインターフェイスにマッピングされます。
+
[cols="1a,1a"]
|===
| ネットワーク | インターフェイス名 


 a| 
グリッド（ Grid ）
 a| 
eth0



 a| 
管理（オプション）
 a| 
Eth1



 a| 
クライアント（オプション）
 a| 
eth2

|===
* ノードが StorageGRID アプライアンスに接続されている場合は、ネットワークごとに特定のポートが使用されます。詳細については、使用しているアプライアンスのインストール手順を参照してください。
* デフォルトルートはノードごとに自動的に生成されます。eth2 が有効な場合、 0.0.0.0/0 は eth2 のクライアントネットワークを使用します。eth2 が無効な場合、 0.0.0.0/0 は eth0 のグリッドネットワークを使用します。
* クライアントネットワークは、グリッドノードがグリッドに参加するまで動作状態になりません
* グリッドが完全にインストールされる前にインストールユーザインターフェイスにアクセスできるように、グリッドノード導入時に管理ネットワークを設定できます。




== オプションのインターフェイス

必要に応じて、ノードにインターフェイスを追加できます。たとえば、を使用できるように、管理ノードまたはゲートウェイノードにトランクインターフェイスを追加できます link:../admin/configure-vlan-interfaces.html["VLANインターフェイス"] 異なるアプリケーションまたはテナントに属するトラフィックを分離する。または、で使用するアクセスインターフェイスを追加することもできます link:../admin/configure-high-availability-group.html["ハイアベイラビリティ（ HA ）グループ"]。

トランクインターフェイスまたはアクセスインターフェイスを追加するには、次の項を参照してください。

* * VMware （ノードのインストール後） * ： link:../maintain/vmware-adding-trunk-or-access-interfaces-to-node.html["VMware ：ノードにトランクインターフェイスまたはアクセスインターフェイスを追加します"]
+
** * Red Hat Enterprise Linux（ノードのインストール前）*： link:../rhel/creating-node-configuration-files.html["ノード構成ファイルを作成"]
** * Ubuntu または Debian （ノードをインストールする前） * ： link:../ubuntu/creating-node-configuration-files.html["ノード構成ファイルを作成"]
** * RHEL、Ubuntu、またはDebian（ノードのインストール後）*： link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux ：ノードにトランクインターフェイスまたはアクセスインターフェイスを追加します"]



