---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: グリッド管理者は、S3およびSwiftクライアントがオブジェクトの格納と読み出しに使用するテナントアカウントを作成および管理します。 
---
= テナントの管理：概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者は、S3およびSwiftクライアントがオブジェクトの格納と読み出しに使用するテナントアカウントを作成および管理します。


NOTE: Swiftクライアントアプリケーションのサポートは廃止され、今後のリリースで削除される予定です。



== テナントアカウントとは

テナントアカウントでは、 Simple Storage Service （ S3 ） REST API または Swift REST API を使用して、 StorageGRID システムでオブジェクトの格納や読み出しを行うことができます。

各テナントアカウントには、フェデレーテッドグループまたはローカルグループ、ユーザ、S3バケットまたはSwiftコンテナ、およびオブジェクトがあります。

テナントアカウントを使用すると、格納されているオブジェクトをエンティティごとに分離できます。たとえば、次のようなユースケースでは複数のテナントアカウントを使用できます。

* * エンタープライズのユースケース：エンタープライズアプリケーションで StorageGRID システムを管理する場合は、組織内の部門ごとにグリッドのオブジェクトストレージを分離する必要があります。この場合は、マーケティング部門、カスタマーサポート部門、人事部門などのテナントアカウントを作成できます。
+

NOTE: S3クライアントプロトコルを使用する場合は、S3バケットとバケットポリシーを使用してエンタープライズ内の部門間でオブジェクトを分離できます。テナントアカウントを使用する必要はありません。実装の手順を参照してください link:../s3/bucket-and-group-access-policies.html["S3バケットとバケットポリシー"] を参照してください。

* * サービスプロバイダのユースケース：サービスプロバイダとして StorageGRID システムを管理する場合は、グリッド上のストレージをリースするエンティティごとにグリッドのオブジェクトストレージを分離できます。この場合は、 A 社、 B 社、 C 社などのテナントアカウントを作成します。


詳細については、を参照してください link:../tenant/index.html["テナントアカウントを使用する"]。



== テナントアカウントを作成するにはどうすればよいですか？

テナントアカウントを作成する際には次の情報を指定します。

* テナント名、クライアントタイプ（S3またはSwift）、オプションのストレージクォータなどの基本情報。
* テナントアカウントに対する権限（テナントアカウントがS3プラットフォームサービスを使用できるか、独自のアイデンティティソースを設定できるか、S3 Selectを使用できるか、グリッドフェデレーション接続を使用できるかなど）。
* テナントの初期ルートアクセス（StorageGRID システムがローカルグループとユーザ、アイデンティティフェデレーション、シングルサインオン（SSO）のいずれを使用しているかに基づく）。


また、S3テナントアカウントが規制要件に準拠する必要がある場合は、StorageGRID システムでS3オブジェクトロック設定を有効にすることができます。S3 オブジェクトのロックを有効にすると、すべての S3 テナントアカウントで準拠バケットを作成、管理できます。



== Tenant Managerの用途

テナントアカウントを作成したら、テナントユーザはTenant Managerにサインインして次のタスクを実行できます。

* アイデンティティフェデレーションを設定する（グリッドとアイデンティティソースを共有する場合を除く）
* グループとユーザを管理します
* アカウントのクローン作成とグリッド間レプリケーションにグリッドフェデレーションを使用します
* S3 アクセスキーを管理します
* S3バケットを作成、管理します
* S3プラットフォームサービスを使用する
* S3 Select を使用する
* ストレージの使用状況を監視



TIP: S3テナントユーザはTenant Managerを使用してS3アクセスキーとバケットを作成、管理できますが、オブジェクトを取り込み、管理するにはS3クライアントアプリケーションを使用する必要があります。を参照してください link:../s3/index.html["S3 REST APIを使用する"] を参照してください。


TIP: Swift ユーザが Tenant Manager にアクセスするには、 Root Access 権限が必要です。ただし Root Access 権限では、 Swift REST API に認証してコンテナを作成したりオブジェクトを取り込んだりすることはできません。Swift REST API に認証するには、 Swift 管理者の権限が必要です。
