---
permalink: admin/migrating-data-into-storagegrid.html 
sidebar: sidebar 
keywords: data migration, move data into storagegrid 
summary: 日常業務に StorageGRID システムを使用しながら、同時に StorageGRID システムに大量のデータを移行できます。 
---
= データを StorageGRID に移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
日常業務に StorageGRID システムを使用しながら、同時に StorageGRID システムに大量のデータを移行できます。

このガイドは、StorageGRID システムへの大量のデータの移行を計画する際に使用します。データ移行の一般的なガイドではなく、移行を実行するための詳細な手順も記載されていません。このセクションのガイドラインと手順に従って、日常業務を中断せずに StorageGRID システムにデータを効率的に移行し、移行したデータが StorageGRID システムによって適切に処理されるようにしてください。



== StorageGRID システムの容量を確認

StorageGRID システムに大量のデータを移行する前に、予想されるボリュームを処理できるディスク容量が StorageGRID システムにあることを確認します。

StorageGRID システムにアーカイブノードが含まれていて、移行されたオブジェクトのコピーがニアラインストレージ（テープなど）に保存されている場合は、アーカイブノードのストレージに予想される移行データボリュームに対応する十分な容量があることを確認します。

容量評価の一環として、移行を計画しているオブジェクトのデータプロファイルを確認し、必要なディスク容量を計算します。StorageGRID システムのディスク容量の監視の詳細については、を参照してください link:managing-storage-nodes.html["ストレージノードを管理します"] の説明を参照してください link:../monitor/index.html["StorageGRID の監視"]。



== 移行データの ILM ポリシーを決定します

StorageGRID システムの ILM ポリシーは、作成されるコピーの数とその格納先、および保持期間を決定します。ILM ポリシーは、オブジェクトをフィルタリングする方法、および一定の期間にわたってオブジェクトデータを管理する方法を記述した一連の ILM ルールで構成されます。

移行データの使用方法およびその要件によっては、日常業務に使用する ILM ルールとは別の、移行データに固有の ILM ルールを定義することができます。たとえば、日常的なデータ管理と移行対象のデータに異なる規制要件が適用される場合、異なるグレードのストレージに異なる数の移行データのコピーが必要となる可能性があります。

移行データと日常業務で保存されるオブジェクトデータを一意に区別できる場合は、移行データにのみ適用されるルールを設定できます。

いずれかのメタデータ条件を使用してデータのタイプを確実に識別できる場合は、この条件を使用して移行データにのみ適用される ILM ルールを定義できます。

データ移行を開始する前に、 StorageGRID システムの ILM ポリシーとそのポリシーが移行データにどのように適用されるかを確認し、 ILM ポリシーへの変更があればテストしておく必要があります。を参照してください link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]。


CAUTION: ILM ポリシーが正しく指定されていないと、原因 によるリカバリ不能なデータ損失が発生する可能性があります。ポリシーを想定どおりに機能させるには、 ILM ポリシーをアクティブ化する前に、 ILM ポリシーに加えたすべての変更をよく確認してください。



== 移行が運用に与える影響を評価

StorageGRID システムは、オブジェクトを効率的に格納して読み出せるようにすること、およびオブジェクトデータとメタデータの冗長コピーをシームレスに作成することでデータ損失に対する優れた保護を提供することを目的に設計されています。

ただし、データ移行は、日常的なシステム処理に影響を与えないように、または極端な場合にはStorageGRID システムに障害が発生した場合にデータが失われる危険性がないように、このガイドの手順に従って慎重に管理する必要があります。

大量のデータを移行すると、システムに新たな負荷がかかります。StorageGRID システムの負荷が高い場合は、オブジェクトの格納および読み出し要求への応答が遅くなります。その結果、日常業務に不可欠な格納および読み出し要求が影響を受ける可能性があります。移行は、原因 のその他の運用上の問題にもなります。たとえば、ストレージノードの容量が上限に近づい原因 ている場合は、一括取り込みによって断続的に大きな負荷がかかると、ストレージノードが読み取り専用と読み書き可能の間で何度も切り替わり、そのたびに通知が生成されます。

負荷の高い状態が続く場合、オブジェクトデータとメタデータの完全な冗長性を確保するために StorageGRID システムが実行する必要のあるさまざまな処理がキューに溜まっていきます。

移行中に StorageGRID システムを安全かつ効率的に運用するためには、本書のガイドラインに従ってデータ移行を慎重に管理する必要があります。データの移行にあたっては、オブジェクトを複数のバッチで取り込むか、または取り込み量を常に調整します。その後、StorageGRID システムを継続的に監視して、さまざまな属性値を超えないようにします。



== データ移行のスケジュール設定と監視

所定の期間内に ILM ポリシーに従ってデータが配置されるよう、必要に応じてデータ移行をスケジュールし、監視する必要があります。



=== データ移行をスケジュール

主要な業務時間中はデータを移行しないでください。データの移行は、夕方や週末など、システムの使用率が低い時間帯にのみ実施してください。

アクティビティの多い時間帯には、データ移行のスケジュールを設定しないでください。ただし、アクティビティレベルが高い期間を完全に回避することが現実的でない場合はそのまま進めてかまいません。その場合は、関連する属性を注意深く監視し、許容値を超えた場合に対処する必要があります。



=== データ移行を監視

次の表に、データ移行中に監視する必要がある属性とその内容を示します。

取り込み速度を抑制するためにレート制限を指定したトラフィック分類ポリシーを使用する場合は、次の表に示す統計情報とともに、観察されたレートを監視し、必要に応じて制限を減らすことができます。

[cols="1a,2a"]
|===
| モニタ | 説明 


 a| 
ILM による評価を待機しているオブジェクトの数
 a| 
. サポート * > * ツール * > * グリッドトポロジ * を選択します。
. [*_deployment_*>*Overview*>*Main*] を選択します。
. ILM アクティビティセクションで、次の属性について表示されるオブジェクトの数を監視します。
+
** * Awaiting - All （ XQUZ ） * ： ILM による評価を待機しているオブジェクトの合計数です。
** * Awaiting - Client （ XCQZ ） * ：クライアント処理（取り込みなど）から ILM による評価を待機しているオブジェクトの合計数です。


. これらの属性のどちらかに対して表示されるオブジェクトの数が 100 、 000 を超えた場合は、オブジェクトの取り込み速度を調整して、 StorageGRID システムへの負荷を軽減してください。




 a| 
ターゲットアーカイブシステムのストレージ容量
 a| 
ILM ポリシーによって、移行対象データのコピーがターゲットアーカイブストレージシステム（テープまたはクラウド）に保存される場合は、ターゲットアーカイブストレージシステムの容量を監視して、移行対象データ用の十分な容量が確保されていることを確認してください。



 a| 
* アーカイブノード * > * ARC * > * Store *
 a| 
「 Store Failures （ ARVF ） * 」属性のアラームがトリガーされた場合、対象のアーカイブストレージシステムの容量が上限に達している可能性があります。ターゲットアーカイブストレージシステムをチェックして、アラームをトリガーした問題を解決してください。

|===