---
permalink: admin/removing-nfs-audit-client-from-audit-share.html 
sidebar: sidebar 
keywords: nfs audit client, remove audit client 
summary: NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。既存の監査クライアントを削除するには、その IP アドレスを削除します。 
---
= 監査共有から NFS 監査クライアントを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 監査クライアントは、 IP アドレスに基づいて監査共有へのアクセスが許可されます。既存の監査クライアントを削除するには、その IP アドレスを削除します。

.作業を開始する前に
* を使用することができます `Passwords.txt` root / adminアカウントのパスワードが設定されたファイル。
* を使用することができます `Configuration.txt` ファイル（リカバリパッケージに含まれています）。


.このタスクについて
監査共有へのアクセスを許可した最後のIPアドレスは削除できません。

.手順
. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. NFS設定ユーティリティを起動します。 `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 監査共有からIPアドレスを削除します。 `remove-ip-from-share`
+
サーバで設定されている監査共有に番号が振られ、リストに表示されます。監査共有はのように表示されます。 `/var/local/log`

. 監査共有に対応する番号を入力します。 `_audit_share_number_`
+
監査共有へのアクセスを許可している IP アドレスに番号が振られ、リストに表示されます。

. 削除する IP アドレスに対応する番号を入力します。
+
監査共有が更新され、この IP アドレスの監査クライアントからのアクセスは許可されなくなります。

. プロンプトが表示されたら、 * Enter * を押します。
+
NFS 設定ユーティリティが表示されます。

. NFS設定ユーティリティを閉じます。 `exit`
. StorageGRID 環境が複数データセンターサイトの環境であり、他のサイトにも管理ノードが含まれている場合は、必要に応じてこれらの監査共有を無効にします。
+
.. 各サイトの管理ノードにリモートからログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。


.. 同じ手順を繰り返して、追加の管理ノードごとに監査共有を設定します。
.. リモート管理ノードへのリモートのSecure Shellログインを終了します。 `exit`


. コマンドシェルからログアウトします。 `exit`

