---
permalink: admin/storage-node-configuration-settings.html 
sidebar: sidebar 
keywords: storage node, configuration settings, counters 
summary: 各ストレージノードでは、複数の設定とカウンタを使用します。アラームをクリアするために、現在の設定の表示やカウンタのリセットが必要になる場合があります（レガシーシステム）。 
---
= ストレージノード設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各ストレージノードでは、複数の設定とカウンタを使用します。アラーム（従来のシステム）をクリアするには、現在の設定の表示またはカウンタのリセットが必要になる場合があります。


CAUTION: ドキュメントで特に指示された場合を除き、ストレージノード設定を変更する前にテクニカルサポートにお問い合わせください。必要に応じて、イベントカウンタをリセットしてレガシーアラームをクリアできます。

ストレージノードの設定とカウンタにアクセスするには、次の手順を実行します。

.手順
. サポート * > * ツール * > * グリッドトポロジ * を選択します。
. 「 * _site * > * _ Storage Node_* 」を選択します。
. ストレージノードを展開し、サービスまたはコンポーネントを選択します。
. [* 構成 *] タブを選択します。


次の表に、ストレージノードの構成設定をまとめます。



== LDR

[cols="2a,1a,3a"]
|===
| 属性名（ Attribute Name ） | コード | 説明 


 a| 
HTTPの状態
 a| 
HSTE
 a| 
S3、Swift、およびその他の内部StorageGRID トラフィックのHTTPの現在の状態。

* Offline ：処理は許可されず、クライアントアプリケーションが LDR サービスへの HTTP セッションを開こうとするとエラーメッセージが表示されます。アクティブなセッションは正常終了します。
* Online ：処理は正常に続行されます




 a| 
HTTP を自動起動します
 a| 
HTAS
 a| 
* このオプションを選択すると、再起動時のシステムの状態は * LDR * > * Storage * コンポーネントの状態によって異なります。再起動時に * ldr*>* Storage* コンポーネントが読み取り専用の場合、 HTTP インターフェイスも読み取り専用です。LDR * > * Storage * コンポーネントが Online の場合、 HTTP も Online になります。それ以外の場合は、 HTTP インターフェイスは Offline 状態のままです。
* 選択しない場合、 HTTP インターフェイスは明示的に有効にするまで Offline のままです。


|===


== LDR> データストア

[cols="2a,1a,3a"]
|===
| 属性名（ Attribute Name ） | コード | 説明 


 a| 
Lost Objects 数をリセットします
 a| 
RCOR
 a| 
このサービス上にある損失オブジェクト数のカウンタをリセットします。

|===


== LDR > Storage の順にクリックします

[cols="2a,1a,3a"]
|===
| 属性名（ Attribute Name ） | コード | 説明 


 a| 
ストレージの状態 -- 望ましい
 a| 
SSD
 a| 
ストレージコンポーネントに求める状態をユーザが設定できます。LDR サービスはこの値を読み取り、指定されたステータスに一致するように試みます。この値は、再起動後も維持されます。

たとえば、この設定を使用すると、使用可能なストレージスペースが十分にある場合でも、ストレージを強制的に読み取り専用にすることができます。これはトラブルシューティングに役立ちます。

この属性には次のいずれかの値を指定できます。

* Offline ：目的の状態が Offline の場合、 LDR サービスは * LDR * > * Storage * コンポーネントをオフラインにします。
* Read-only：LDRサービスはストレージの状態をRead-onlyに移行し、新しいコンテンツの受け入れを停止します。ただし、LDRサービスは引き続きS3またはILMベースのパージ要求と削除要求を受け入れます。開いているセッションが閉じられるまでの短時間の間、コンテンツが引き続きストレージノードに保存される可能性があります。
* Online ：通常のシステム運用中は、値を Online のままにします。ストレージの状態 -- ストレージコンポーネントの現在の状態は ' 使用可能なオブジェクトストレージ容量などの LDR サービスの状態に基づいてサービスによって動的に設定されますスペースが少ない場合、コンポーネントは読み取り専用になります。




 a| 
ヘルスチェックタイムアウト
 a| 
SHCT
 a| 
ストレージボリュームが正常であるとみなされるために、ヘルスチェックテストが完了する必要のある秒数。この値は、サポートから指示があった場合にのみ変更してください。

|===


== LDR > Verification の順に選択します

[cols="2a,1a,3a"]
|===
| 属性名（ Attribute Name ） | コード | 説明 


 a| 
欠落オブジェクト数のリセット
 a| 
VCMI
 a| 
OMIS （ Missing Objects Detected ）の数をリセットします。オブジェクトの存在チェックが完了した後にのみ使用します。欠落しているレプリケートオブジェクトデータは、 StorageGRID システムによって自動的にリストアされます。



 a| 
検証レート
 a| 
VPRI （ VPRI ）
 a| 
バックグラウンド検証を実行する際のレートを設定します。バックグラウンド検証レートの設定に関する情報を参照してください。



 a| 
破損オブジェクト数のリセット
 a| 
VCCR
 a| 
バックグラウンド検証中に見つかった、破損しているレプリケートされたオブジェクトデータのカウンタをリセットします。このオプションを使用すると、 OCOR （ Corrupt Objects Detected ）アラームの状態をクリアできます。



 a| 
隔離オブジェクトを削除します
 a| 
OQRT の場合
 a| 
破損したオブジェクトを隔離ディレクトリから削除し、隔離されたオブジェクトの数をゼロにリセットして、 Quarantined Objects Detected （ OQRT ）アラームをクリアします。このオプションは、破損したオブジェクトが StorageGRID システムによって自動的にリストアされたあとに使用します。

Lost Objects アラームがトリガーされた場合、テクニカルサポートが隔離されたオブジェクトにアクセスを試みる可能性があります。隔離されたオブジェクトが、データのリカバリや、オブジェクトコピーの破損の原因となった根本的な問題のデバッグに役立つ場合があります。

|===


== LDR> イレイジャーコーディング

[cols="2a,1a,3a"]
|===
| 属性名（ Attribute Name ） | コード | 説明 


 a| 
書き込みエラー数をリセットします
 a| 
RSWF
 a| 
イレイジャーコーディングオブジェクトデータのストレージノードへの書き込みエラーのカウンタをリセットします。



 a| 
読み取りエラー数をリセットします
 a| 
RSRF
 a| 
イレイジャーコーディングオブジェクトデータのストレージノードからの読み取りエラーのカウンタをリセットします。



 a| 
Reset Deletes Failure Count （エラーカウントをリセット）
 a| 
自衛隊
 a| 
イレイジャーコーディングオブジェクトデータのストレージノードからの削除エラーのカウンタをリセットします。



 a| 
破損コピーのリセット検出数
 a| 
RSCC
 a| 
ストレージノード上にあるイレイジャーコーディングオブジェクトデータの破損コピー数のカウンタをリセットします。



 a| 
破損フラグメントのリセット検出数
 a| 
RSCD
 a| 
ストレージノード上にあるイレイジャーコーディングオブジェクトデータの破損フラグメントのカウンタをリセットします。



 a| 
欠落フラグメントの検出数をリセットします
 a| 
RSMD
 a| 
ストレージノード上にあるイレイジャーコーディングオブジェクトデータの欠落フラグメントのカウンタをリセットします。オブジェクトの存在チェックが完了した後にのみ使用します。

|===


== LDR > Replication の順に選択します

[cols="2a,1a,3a"]
|===
| 属性名（ Attribute Name ） | コード | 説明 


 a| 
インバウンドレプリケーションエラー数をリセットします
 a| 
RICR
 a| 
インバウンドレプリケーションエラーのカウンタをリセットします。これを使用すると、 RIRF （ Inbound Replication - - Failed ）アラームをクリアできます。



 a| 
アウトバウンドレプリケーションのエラー数をリセットします
 a| 
ROCR
 a| 
アウトバウンドレプリケーションエラーのカウンタをリセットします。これを使用すると、 RORF （ Outbound Replications - - Failed ）アラームをクリアできます。



 a| 
インバウンドレプリケーションを無効にします
 a| 
DSIR
 a| 
メンテナンスまたは手順 のテストの一環としてインバウンドレプリケーションを無効にする場合に選択します。通常の運用中はオフのままにします。

インバウンドレプリケーションを無効にすると、オブジェクトをストレージノードから読み出してStorageGRID システム内の別の場所にコピーすることはできますが、他の場所からこのストレージノードにオブジェクトをコピーすることはできません。つまり、LDRサービスは読み取り専用です。



 a| 
アウトバウンドレプリケーションを無効にします
 a| 
DSOR
 a| 
メンテナンスまたは手順 のテストの一環としてアウトバウンドレプリケーション（ HTTP 読み出し用のコンテンツ要求を含む）を無効にする場合に選択します。通常の運用中はオフのままにします。

アウトバウンドレプリケーションを無効にすると、このストレージノードにオブジェクトをコピーすることはできますが、ストレージノードからオブジェクトを読み出してStorageGRID システム内の別の場所にコピーすることはできません。LDR サービスは書き込み専用です。

|===