---
permalink: monitor/alarms-reference.html 
sidebar: sidebar 
keywords: alarms, alarms reference 
summary: 次の表に、これらの従来のデフォルトアラームをすべて示します。アラームがトリガーされた場合は、この表のアラームコードを参照して、推奨される対処方法を確認できます。 
---
= アラーム一覧（従来のシステム）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、これらの従来のデフォルトアラームをすべて示します。アラームがトリガーされた場合は、この表のアラームコードを参照して、推奨される対処方法を確認できます。


NOTE: 従来のアラームシステムは引き続きサポートされますが、アラートシステムには大きなメリットがあり、使いやすくなっています。

[cols="1a,1a,1a,3a"]
|===
| コード | 名前 | サービス | 推奨される対処方法 


 a| 
ABRL
 a| 
使用可能な属性リレー
 a| 
BADC 、 BAMS 、 BARC 、 BCLB 、 BCMN 、 BCMN 、 BLDR 、 BNMS 、 BSSM 、 BDDS
 a| 
Attribute Relay Service を実行しているサービス（ ADC サービス）への接続をできるだけ早くリストアします。属性リレーが接続されていないと、グリッドノードからNMSサービスに属性の値を報告できません。そのため、 NMS サービスでサービスのステータスの監視やサービスの属性の更新を行うことができなくなります。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
ACMS
 a| 
使用可能なメタデータサービス
 a| 
BARC 、 BLDR 、 BCMN
 a| 
LDR サービスまたは ARC サービスからの DDS サービスへの接続が失われた場合にアラームがトリガーされます。この場合、取り込みまたは読み出しのトランザクションを処理できません。DDS サービスを使用できない状態が短時間の一時問題 のみである場合は、トランザクションが遅延する可能性があります。

このアラームを解除し、サービスのすべての機能を復旧するには、 DDS サービスへの接続を確認してリストアします。



 a| 
ACTS
 a| 
クラウドの階層化サービスのステータス
 a| 
円弧（ Arc ）
 a| 
ターゲットタイプが「 Cloud Tiering - Simple Storage Service （ S3 ）」のアーカイブノードにのみ適用されます。

アーカイブノードの ACTS 属性が「 Read-Only Enabled 」または「 Read-Write Disabled 」に設定されている場合、「 Read-Write Enabled 」に設定する必要があります。

認証エラーによって Major アラームがトリガーされた場合は、デスティネーションバケットに関連付けられているクレデンシャルを確認し、必要に応じて値を更新します。

それ以外の理由で Major アラームがトリガーされた場合は、テクニカルサポートに連絡してください。



 a| 
ADCA
 a| 
ADC ステータス
 a| 
ADC
 a| 
アラームがトリガーされた場合は、 * support * > * Tools * > * Grid topology * を選択します。次に、 * _site _ * > * _ grid node_* > * ADC * > * Overview * > * Main * and * ADC * > * Alarms * > * Main * を選択して、アラームの原因 を確認します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
ADCE
 a| 
ADC State のことです
 a| 
ADC
 a| 
「 ADC State 」の値が「 Standby 」の場合は、しばらくサービスを監視し、問題が解決しなければテクニカルサポートに連絡します。

「 ADC State 」の値が「 Offline 」の場合は、サービスを再起動します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
AITE
 a| 
読み出し状態
 a| 
BARC
 a| 
ターゲットタイプが「 Tivoli Storage Manager （ TSM ）」のアーカイブノードにのみ適用されます。

「 Retrieve State 」の値が「 Waiting for Target 」の場合は、 TSM ミドルウェアサーバを調べ、正常に動作していることを確認します。アーカイブノードを StorageGRID システムに追加したばかりの場合は、アーカイブノードから対象の外部アーカイブストレージシステムへの接続が正しく設定されていることを確認します。

「 Archive Retrieve State 」の値が「 Offline 」の場合は、状態を「 Online 」に更新できるか試します。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * ARC * > * Retrieve * > * Configuration * > * Main * を選択し、 * Archive Retrieve State * > * Online * を選択して、 * Apply Changes * をクリックします。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
AITU
 a| 
ステータスを取得します
 a| 
BARC
 a| 
「 Retrieve Status 」の値が「 Target Error 」の場合は、対象の外部アーカイブストレージシステムにエラーがないかを確認します。

「 Archive Retrieve Status 」の値が「 Session Lost 」の場合は、対象の外部アーカイブストレージシステムがオンラインで正常に動作していることを確認します。ターゲットとのネットワーク接続を確認します。

「 Archive Retrieve Status 」の値が「 Unknown Error 」の場合は、テクニカルサポートに連絡してください。



 a| 
ALIS
 a| 
インバウンド属性セッション
 a| 
ADC
 a| 
属性リレーのインバウンド属性セッション数が大幅に増加している場合、 StorageGRID システムのバランスが悪くなっている可能性があります。通常の状態であれば、属性セッションは ADC サービスに均等に分散されます。バランスが悪い状態が続くと、パフォーマンスの問題につながる可能性があり

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
ALOS
 a| 
アウトバウンド属性セッション
 a| 
ADC
 a| 
ADC サービスの属性セッションが多く、過負荷状態になっています。このアラームがトリガーされた場合は、テクニカルサポートに連絡してください。



 a| 
ALUR
 a| 
到達不能な属性リポジトリ
 a| 
ADC
 a| 
NMS サービスとのネットワーク接続を調べ、属性リポジトリに接続できることを確認します。

このアラームがトリガーされ、ネットワーク接続に問題がない場合は、テクニカルサポートに連絡してください。



 a| 
AMQS （ AMQS ）
 a| 
キューに登録された監査メッセージ
 a| 
BADC 、 BAMS 、 BARC 、 BCLB 、 BCMN 、 BCMN 、 BLDR 、 BNMS 、 BDDS
 a| 
監査メッセージを監査リレーまたは監査リポジトリにすぐに転送できない場合、メッセージはディスクキューに格納されます。ディスクキューがいっぱいになると、システムが停止する可能性があります。

時間内に対応して停止を回避できるように、ディスクキュー内のメッセージ数が次のしきい値に達すると AMQS アラームがトリガーされます。

* Notice ： 10 万件を超えるメッセージ
* Minor ： 50 万件以上のメッセージ
* Major ： 200 万件以上のメッセージ
* Critical ： 500 万件以上のメッセージ


AMQS アラームがトリガーされた場合は、システムの負荷を確認します。大量のトランザクションが発生していた場合は、時間が経つとアラームは自然に解消されます。この場合、このアラームは無視してかまいません。

アラームが解除されず重大度が上がった場合は、キューサイズのグラフを確認します。数時間から数日にわたって数値が増え続けている場合は、監査の負荷がシステムの監査キャパシティを超えている可能性があります。クライアントの処理率を下げるか、監査レベルを「 Error 」または「 Off 」に変更して、ログに記録される監査メッセージの数を減らしてください。を参照してください link:../monitor/configure-audit-messages.html["監査メッセージとログの送信先を設定します"]。



 a| 
AOTE
 a| 
ストアの状態
 a| 
BARC
 a| 
ターゲットタイプが「 Tivoli Storage Manager （ TSM ）」のアーカイブノードにのみ適用されます。

「 Store State 」の値が「 Waiting for Target 」の場合は、外部アーカイブストレージシステムを調べ、正常に動作していることを確認します。アーカイブノードを StorageGRID システムに追加したばかりの場合は、アーカイブノードから対象の外部アーカイブストレージシステムへの接続が正しく設定されていることを確認します。

「 Store State 」の値が「 Offline 」の場合は、「 Store Status 」の値を確認します。問題がある場合は解決してから、「 Store State 」を「 Online 」に戻します。



 a| 
AOTU
 a| 
ストアのステータス
 a| 
BARC
 a| 
「 Store Status 」の値が「 Session Lost 」の場合は、外部アーカイブストレージシステムが接続されてオンラインになっていることを確認します。

「 Target Error 」の値を入力して、外部アーカイブストレージシステムにエラーがないかを確認します。

「 Store Status 」の値が「 Unknown Error 」の場合は、テクニカルサポートに連絡してください。



 a| 
APMS
 a| 
ストレージマルチパス接続
 a| 
SSM のことです
 a| 
マルチパス状態アラームが「Degraded」と表示された場合は（* support *>* Tools *>* Grid topology *、*_site_*>*_grid node_*>* SSM *>* Events *を選択）、次の手順を実行します。

. インジケータライトが表示されていないケーブルを接続するか交換します。
. 1~5 分ほど待ちます。
+
最初のケーブルを接続してから少なくとも5分後までは、もう一方のケーブルを抜かないでください。それよりも早くケーブルを取り外すと原因 、ルートボリュームが読み取り専用になり、ハードウェアの再起動が必要になります。

. SSM *>* Resources *ページに戻り、[Storage Hardware]セクションでマルチパスのステータスが「Degraded」が「Nominal」に変わったことを確認します。




 a| 
ARCE
 a| 
アークの状態
 a| 
円弧（ Arc ）
 a| 
ARC サービスの状態は、 ARC のすべてのコンポーネント（ Replication 、 Store 、 Retrieve 、 Target ）が起動されるまでは「 Standby 」となり、その後、 Online に移行します。

「 ARC State 」の値が「 Standby 」から「 Online 」に切り替わらない場合は、 ARC のコンポーネントのステータスを確認します。

「ARC State」の値が「Offline」の場合は、サービスを再起動します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
AROQ
 a| 
Objects Queued （オブジェクトのキュー
 a| 
円弧（ Arc ）
 a| 
このアラームは、対象の外部アーカイブストレージシステムの問題が原因でリムーバブルストレージデバイスが低速になっている場合や、複数の読み取りエラーが発生している場合にトリガーされることがあります。外部アーカイブストレージシステムにエラーがないかどうかを確認し、正常に動作していることを確認します。

このエラーは、データ要求の割合が高いことが原因で発生することがあります。この場合は、システムアクティビティが少なくなるとキューに登録されたオブジェクトの数も少なくなります



 a| 
ARRF
 a| 
要求の失敗
 a| 
円弧（ Arc ）
 a| 
対象の外部アーカイブストレージシステムからの読み出しに失敗した場合、一時的な問題 が原因である可能性があるため、アーカイブノードで読み出しが再試行されます。ただし、オブジェクトデータが破損している場合や完全に使用できないものとしてマークされている場合は、読み出しが失敗することはありません。この場合、アーカイブノードで読み出しの再試行が繰り返され、「 Request Failures 」の値が増え続けることになります。

このアラームは、要求されたデータを格納するストレージメディアが破損していることを示している可能性があります。外部アーカイブストレージシステムを調べて問題を詳しく診断します。

オブジェクトデータがアーカイブにないことが判明した場合は、オブジェクトを StorageGRID システムから削除する必要があります。詳細については、テクニカルサポートにお問い合わせください。

このアラームをトリガーした問題が解消されたら、障害数をリセットします。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * ARC * > * Retrieve * > * Configuration * > * Main * を選択し、 * Reset Request Failure Count * を選択して、 * Apply Changes * をクリックします。



 a| 
ARRV
 a| 
検証エラー
 a| 
円弧（ Arc ）
 a| 
この問題の診断と修正については、テクニカルサポートにお問い合わせください。

このアラームをトリガーした問題を解決したら、障害数をリセットします。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * ARC * > * Retrieve * > * Configuration * > * Main * を選択し、 * Reset Verification Failure Count * を選択して * Apply Changes * をクリックします。



 a| 
ARVF
 a| 
Store Failures （ストア障害）
 a| 
円弧（ Arc ）
 a| 
このアラームは、対象の外部アーカイブストレージシステムのエラーが原因で発生することがあります。外部アーカイブストレージシステムにエラーがないかどうかを確認し、正常に動作していることを確認します。

このアラームをトリガーした問題が解消されたら、障害数をリセットします。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * ARC * > * Retrieve * > * Configuration * > * Main * を選択し、 * Reset Store Failure Count * を選択して、 * Apply Changes * をクリックします。



 a| 
ASXP
 a| 
監査共有
 a| 
AMS
 a| 
「 Audit Shares 」の値が「 Unknown 」の場合にアラームがトリガーされます。このアラームは、管理ノードのインストールまたは設定に問題があることを示している可能性があります。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
AUMA
 a| 
AMSステータス
 a| 
AMS
 a| 
「 AMS Status 」の値が「 DB Connectivity Error 」の場合は、グリッドノードを再起動します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
AUME
 a| 
AMSの状態
 a| 
AMS
 a| 
「 AMS State 」の値が「 Standby 」の場合は、しばらく StorageGRID システムを監視し、問題が解決しない場合は、テクニカルサポートにお問い合わせください。

「AMS State」の値が「Offline」の場合は、サービスを再起動します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
補助
 a| 
監査エクスポートのステータス
 a| 
AMS
 a| 
アラームがトリガーされた場合は、原因となっている問題を修正し、 AMS サービスを再起動します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
BADD
 a| 
ストレージコントローラ障害ドライブ数
 a| 
SSM のことです
 a| 
このアラームは、 StorageGRID アプライアンスの 1 つ以上のドライブが故障したか、または最適な状態でない場合にトリガーされます。必要に応じてドライブを交換します。



 a| 
BASF
 a| 
使用可能なオブジェクト ID
 a| 
CMN
 a| 
StorageGRID システムのプロビジョニング時、 CMN サービスに決まった数のオブジェクト ID が割り当てられます。このアラームは、 StorageGRID システムでオブジェクト ID が不足し始めるとトリガーされます。

ID の割り当てを増やすには、テクニカルサポートにお問い合わせください。



 a| 
低音
 a| 
ID ブロック割り当てステータス
 a| 
CMN
 a| 
デフォルトでは、ADCのクォーラムに到達できないためにオブジェクトIDを割り当てることができない場合にアラームがトリガーされます。

CMN サービスでの ID ブロックの割り当てには、オンラインで接続されている ADC サービスがクォーラム（過半数）に達している必要があります。クォーラムが使用できない場合、ADCクォーラムが再確立されるまでCMNサービスは新しい識別子ブロックを割り当てることができません。ADC のクォーラムが失われても、グリッドのどこかに約 1 カ月分の ID がキャッシュされているため、通常は StorageGRID システムにすぐに影響が及ぶことはありません（クライアントによるコンテンツの取り込みと読み出しは引き続き可能です）。 ただし、この状態が続くと、 StorageGRID システムは新しいコンテンツを取り込むことができなくなります。

アラームがトリガーされた場合は、 ADC のクォーラムが失われた理由（ネットワークやストレージノードの障害など）を調べて適切に対処します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
BRDT
 a| 
コンピューティングコントローラシャーシの温度
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの温度が公称のしきい値を超えるとアラームがトリガーされます。

過熱の原因となっているハードウェアコンポーネントや環境の問題を確認します。必要に応じて、コンポーネントを交換します。



 a| 
BTOF
 a| 
オフセット（ Offset ）
 a| 
BADC 、 BLDR 、 BNMS 、 BAMS 、 BCLB 、 BCMN 、 BARC
 a| 
サービスの時間（秒）とオペレーティングシステムの時間が大きく異なる場合にアラームがトリガーされます。通常の状態であれば、サービスは自動的に再同期されます。サービスの時間とオペレーティングシステムの時間のずれが大きくなると、システムの運用に影響を及ぼすことがあります。StorageGRID システムの時間ソースが正しいことを確認します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
BTSE
 a| 
クロックの状態
 a| 
BADC 、 BLDR 、 BNMS 、 BAMS 、 BCLB 、 BCMN 、 BARC
 a| 
サービスの時間がオペレーティングシステムで追跡された時間と同期されていない場合にアラームがトリガーされます。通常の状態であれば、サービスは自動的に再同期されます。オペレーティングシステムの時間とのずれが大きくなると、システムの運用に影響を及ぼすことがあります。StorageGRID システムの時間ソースが正しいことを確認します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
CAHP
 a| 
Java ヒープ使用率
 a| 
DDS
 a| 
Java のガベージコレクションが追いつかず、システムの正常な動作に必要なヒープスペースを確保できなくなった場合にアラームがトリガーされます。アラームは、 DDS のメタデータストアに対するユーザのワークロードがシステム全体で利用できるリソースを超えていることを示している可能性があります。ダッシュボードでILMのアクティビティを確認するか、* support *>* Tools *>* Grid topology *を選択し、*_site_*>*_grid node_*>* DDS *>* Resources *>* Overview *>* Main *を選択します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
カーサ
 a| 
データストアのステータス
 a| 
DDS
 a| 
Cassandra のメタデータストアが使用できなくなるとアラームが生成されます。

Cassandra のステータスを確認します。

. ストレージノードで、adminおよびとしてログインします `su` Passwords.txtファイルに記載されているパスワードを使用してrootに変更します。
. 入力するコマンド `service cassandra status`
. Cassandraが実行されていない場合は再起動します。 `service cassandra restart`


このアラームは、ストレージノードに対するメタデータストア（ Cassandra データベース）のリビルドが必要なことを示している可能性もあります。

の Services ： Status - Cassandra （ SVST ）アラームのトラブルシューティングに関する情報を参照してください link:../troubleshoot/troubleshooting-metadata-issues.html["メタデータに関する問題のトラブルシューティング"]。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
ケース
 a| 
データストアの状態
 a| 
DDS
 a| 
このアラームは、インストール時または拡張時にトリガーされ、新しいデータストアがグリッドに追加されていることを示します。



 a| 
CCNA
 a| 
コンピューティングハードウェア
 a| 
SSM のことです
 a| 
このアラームは、 StorageGRID アプライアンスのコンピューティングコントローラハードウェアのステータスが「 Needs Attention 」になるとトリガーされます。



 a| 
CDLP
 a| 
Metadata Used Space （ Percent ）
 a| 
DDS
 a| 
このアラームは、「 Metadata Effective Space （ CEMS ）」が 70% 使用済み（ Minor アラーム）、 90% 使用済み（ Major アラーム）、 100% 使用済み（ Critical アラーム）に達した場合に、それぞれトリガーされます。

このアラームが90%のしきい値に達すると、Grid Managerのダッシュボードに警告が表示されます。できるだけ早く拡張手順 を実行して新しいストレージノードを追加する必要があります。を参照してください link:../expand/index.html["グリッドを展開する"]。

このアラームが 100% のしきい値に達した場合は、オブジェクトの取り込みを停止し、すぐにストレージノードを追加する必要があります。Cassandra は、コンパクションや修復などの必須処理を実行するために一定量のスペースを必要とします。オブジェクトメタデータの使用スペースが使用可能なスペースの 100% を超えると、これらの処理に影響します。望ましくない結果が生じる可能性があります。

* 注：ストレージノードを追加できない場合は、テクニカルサポートにお問い合わせください。

新しいストレージノードが追加されると、すべてのストレージノード間でオブジェクトメタデータが自動的にリバランシングされ、アラームが解除されます。

の Low metadata storage アラートのトラブルシューティングに関する情報も参照してください link:../troubleshoot/troubleshooting-metadata-issues.html["メタデータに関する問題のトラブルシューティング"]。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
CMNA
 a| 
CMNステータス
 a| 
CMN
 a| 
CMN Status の値が Error の場合は、 * support * > * Tools * > * Grid topology * を選択し、 * _site _ * > * _ grid node_name * > * CMN * > * Overview * > * Main * and * CMN * > * Alarms * > * Main * を選択してエラーの原因 を確認し、問題のトラブルシューティングを行います。

プライマリ管理ノードのハードウェアの更新時に CMN の状態が切り替わると（「 CMN State 」の値が「 Standby 」から「 Online 」に変わると）、アラームがトリガーされ、「 CMN Status 」の値が「 No Online CMN 」になります。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
CPRC
 a| 
残り容量
 a| 
NMS
 a| 
残り容量（ NMS データベースに対して確立できる接続の数）が設定されたアラームの重大度を下回るとアラームがトリガーされます。

アラームがトリガーされた場合は、テクニカルサポートに連絡してください。



 a| 
cPSA
 a| 
コンピューティングコントローラの電源装置 A
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスのコンピューティングコントローラに電源装置 A を搭載した問題 がある場合にアラームがトリガーされます。

必要に応じて、コンポーネントを交換します。



 a| 
cPSB
 a| 
コンピューティングコントローラの電源装置 B
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスのコンピューティングコントローラに電源装置 B を搭載した問題 があると、アラームがトリガーされます。

必要に応じて、コンポーネントを交換します。



 a| 
CPUT
 a| 
コンピューティングコントローラの CPU 温度
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスのコンピューティングコントローラの CPU の温度が公称のしきい値を超えるとアラームがトリガーされます。

ストレージノードが StorageGRID アプライアンスである場合は、 StorageGRID システムのコントローラを調査する必要があります。

過熱の原因となっているハードウェアコンポーネントや環境の問題を確認します。必要に応じて、コンポーネントを交換します。



 a| 
DNST
 a| 
DNSステータス
 a| 
SSM のことです
 a| 
インストールが完了すると、 SSM サービスで DNST アラームがトリガーされます。DNS の設定が完了し、新しいサーバの情報がすべてのグリッドノードに送られると、アラームはキャンセルされます。



 a| 
ECCD
 a| 
破損フラグメントが検出されました
 a| 
LDR
 a| 
バックグラウンド検証プロセスでイレイジャーコーディングフラグメントの破損が検出されるとアラームがトリガーされます。破損したフラグメントが検出された場合、フラグメントの再構築が試行されます。「 Corrupt Fragments Detected 」属性と「 Copies Lost 」属性を 0 にリセットし、それらのカウントが再び増えるかどうかを確認します。カウントが増える場合は、ストレージノードの基盤となるストレージに問題がある可能性があります。イレイジャーコーディングオブジェクトデータのコピーは、失われたフラグメントまたは破損したフラグメントの数がイレイジャーコーディングのフォールトトレランスを超えないかぎり欠落とはみなされません。そのため、破損したフラグメントがあってもオブジェクトの読み出しは引き続き可能です。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
ECST
 a| 
検証ステータス
 a| 
LDR
 a| 
このアラームは、このストレージノード上のイレイジャーコーディングオブジェクトデータに対するバックグラウンド検証プロセスの現在のステータスを示します。

バックグラウンド検証プロセスでエラーが発生すると、 Major アラームがトリガーされます。



 a| 
FOPN
 a| 
オープンファイル記述子
 a| 
BADC 、 BAMS 、 BARC 、 BCLB 、 BCMN 、 BCMN 、 BLDR 、 BNMS 、 BSSM 、 BDDS
 a| 
アクティビティのピーク時に FOPN が大きくなることがあります。アクティビティが少ない時間帯も低下しない場合は、テクニカルサポートにお問い合わせください。



 a| 
HSTE
 a| 
HTTPの状態
 a| 
BLDR
 a| 
HSTU の推奨処置を参照してください。



 a| 
ステュディオ
 a| 
HTTPステータス
 a| 
BLDR
 a| 
HSTEとHSTUは、S3、Swift、およびその他の内部StorageGRID トラフィックを含むすべてのLDRトラフィックのHTTPに関連しています。アラームは、次のいずれかの状況が発生したことを示します。

* HTTPが手動でオフラインになっています。
* Auto-Start HTTP 属性が無効になりました。
* LDR サービスがシャットダウン中である。


Auto-Start HTTP 属性はデフォルトで有効になっています。この設定を変更すると、再起動後も HTTP がオフラインのままになる可能性があります。

必要に応じて、 LDR サービスが再起動するまで待ちます。

サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、「 * _ ストレージ・ノード _ * > * LDR * > * Configuration * 」を選択します。HTTPがオフラインの場合は、オンラインにします。Auto-Start HTTP 属性が有効になっていることを確認します。

HTTPがオフラインのままの場合は、テクニカルサポートにお問い合わせください。



 a| 
HTAS
 a| 
HTTP を自動起動します
 a| 
LDR
 a| 
起動時に HTTP サービスを自動的に開始するかどうかを指定します。これはユーザ指定の設定オプションです。



 a| 
IRSU
 a| 
インバウンドレプリケーションステータス
 a| 
BLDR 、 BARC
 a| 
インバウンドレプリケーションが無効になっていることを示します。構成設定を確認します。 * support * > * Tools * > * Grid topology * を選択します。次に、 * _site _ * > * _ grid node_name > * LDR * > * Replication * > * Configuration * > * Main * を選択します。



 a| 
LATA （ LATA
 a| 
平均レイテンシ
 a| 
NMS
 a| 
接続に問題がないかを確認します。

システムアクティビティを調べ、システムアクティビティが増えていることを確認します。システムアクティビティが増えれば、属性データアクティビティも増えます。このアクティビティが増加すると、属性データの処理に遅延が生じます。これは正常なシステムアクティビティであり、自然に解消されます。

複数のアラームがないか確認します。トリガーされたアラームの数が多すぎると、平均レイテンシが高くなることがあります。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
LDRE
 a| 
LDRの状態
 a| 
LDR
 a| 
「LDR State」の値が「Standby」の場合は、引き続き状況を監視し、問題が解決しない場合はテクニカルサポートに連絡してください。

「LDR State」の値が「Offline」の場合は、サービスを再起動します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
失われました
 a| 
Lost Objects
 a| 
DDS 、 LDR
 a| 
要求されたオブジェクトのコピーを StorageGRID システム内のいずれの場所からも読み出せない場合にトリガーされます。LOST （ Lost Objects ）アラームがトリガーされる前に、欠落オブジェクトをシステム内の他の場所から読み出して置き換えることができます。

損失オブジェクトとは、データが失われたことを表します。Lost Objects 属性の値は、 ILM ポリシーを満たすためにコンテンツが DDS サービスで意図的にパージされた場合を除き、オブジェクトの場所の数が 0 になるたびに増えていきます。

LOST （ Lost Object ）アラームはすぐに調査する必要があります。問題が解決しない場合は、テクニカルサポートにお問い合わせください。

link:../troubleshoot/troubleshooting-lost-and-missing-object-data.html["失われたオブジェクトデータと欠落しているオブジェクトデータのトラブルシューティング"]



 a| 
MCEP
 a| 
管理インターフェイス証明書の有効期限
 a| 
CMN
 a| 
管理インターフェイスへのアクセスに使用される証明書の有効期限が近づくとトリガーされます。

. Grid Manager から、 * configuration * > * Security * > * Certificates * を選択します。
. [* グローバル * ] タブで、 [* 管理インターフェイス証明書 * ] を選択します。
. link:../admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html#add-a-custom-management-interface-certificate["新しい管理インターフェイス証明書をアップロードします。"]




 a| 
MINQ
 a| 
キューに登録された電子メール通知
 a| 
NMS
 a| 
NMS サービスをホストするサーバと外部のメールサーバのネットワーク接続を確認します。また、 E メールサーバの設定が正しいことを確認します。

link:managing-alarms.html["アラーム用 E メールサーバの設定（従来型システム）"]



 a| 
分
 a| 
電子メール通知のステータス
 a| 
BNMS
 a| 
NMS サービスでメールサーバに接続できない場合に Minor アラームがトリガーされます。NMS サービスをホストするサーバと外部のメールサーバのネットワーク接続を確認します。また、 E メールサーバの設定が正しいことを確認します。

link:managing-alarms.html["アラーム用 E メールサーバの設定（従来型システム）"]



 a| 
お見逃しなく
 a| 
NMS インターフェイスエンジンステータス
 a| 
BNMS
 a| 
インターフェイスコンテンツを収集および生成する管理ノードの NMS インターフェイスエンジンがシステムから切断されている場合にアラームがトリガーされます。Server Manager で、サーバの個々のアプリケーションが停止しているかどうかを確認します。



 a| 
ナン
 a| 
ネットワーク自動ネゴシエーション設定
 a| 
SSM のことです
 a| 
ネットワークアダプタの設定を確認します。設定は、ネットワークのルータとスイッチの設定と一致する必要があります。

設定が正しくないと、システムのパフォーマンスに重大な影響を及ぼす可能性があります。



 a| 
NDUP （ NDUP ）
 a| 
ネットワークのデュプレックス設定
 a| 
SSM のことです
 a| 
ネットワークアダプタの設定を確認します。設定は、ネットワークのルータとスイッチの設定と一致する必要があります。

設定が正しくないと、システムのパフォーマンスに重大な影響を及ぼす可能性があります。



 a| 
NLNK
 a| 
ネットワークリンク検出
 a| 
SSM のことです
 a| 
ポートとスイッチのネットワークケーブル接続を確認します。

ネットワークルータ、スイッチ、およびアダプタの設定を確認します。

サーバを再起動します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
NRER
 a| 
受信エラー
 a| 
SSM のことです
 a| 
NRER アラームの原因としては、次のようなものが考えられます。

* Forward Error Correction （ FEC; 前方誤り訂正）の不一致
* スイッチポートと NIC の MTU が一致しません
* リンクエラー率が高くなっています
* NIC リングバッファオーバーラン


の Network Receive Error （ NRER ）アラームのトラブルシューティングに関する情報を参照してください link:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["ネットワーク、ハードウェア、およびプラットフォームの問題をトラブルシューティングする"]。



 a| 
NRLY の場合
 a| 
使用可能な監査リレー
 a| 
BADC 、 BARC 、 BCLB 、 BCMN 、 BLDR 、 BNMS 、 BDDS
 a| 
監査リレーがADCサービスに接続されていないと、監査イベントを報告できません。接続がリストアされるまではキューに登録され、ユーザには提供されません。

できるだけ早く ADC サービスへの接続をリストアします。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
NSCA
 a| 
NMSステータス
 a| 
NMS
 a| 
「 NMS Status 」の値が「 DB Connectivity Error 」の場合は、サービスを再起動します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
NSCE
 a| 
NMS State （ NMS 状態）
 a| 
NMS
 a| 
「 NMS State 」の値が「 Standby 」の場合は、しばらく状況を監視し、問題が解決しなければテクニカルサポートに連絡します。

「NMS State」の値が「Offline」の場合は、サービスを再起動します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
NSPD
 a| 
スピード
 a| 
SSM のことです
 a| 
ネットワーク接続またはドライバの互換性の問題が原因である可能性があります。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
NTBR
 a| 
空きテーブルスペース
 a| 
NMS
 a| 
アラームがトリガーされた場合は、データベースの使用量がどのくらいのペースで変化しているかを確認します。時間とともに徐々に変化するのではなく、急激に低下した場合は、エラー状態を示します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。

アラームのしきい値を調整することで、追加のストレージの割り当てが必要になったときにプロアクティブに管理できます。

使用可能なスペースがしきい値の下限（アラームのしきい値を参照）に達した場合は、テクニカルサポートに連絡してデータベースの割り当てを変更します。



 a| 
入力します
 a| 
送信エラー
 a| 
SSM のことです
 a| 
これらのエラーは、手動でリセットしなくても解消されます。クリアされない場合は、ネットワークハードウェアを確認してください。アダプタのハードウェアとドライバが正しくインストールされ、ネットワークのルータやスイッチと連携するように設定されていることを確認します。

原因となっている問題を解決したら、カウンタをリセットします。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * SSM * > * Resources * > * Configuration * > * Main * を選択し、 * Reset Transmit Error Count * を選択して、 * Apply Changes * をクリックします。



 a| 
NTFQ
 a| 
NTP 周波数オフセット
 a| 
SSM のことです
 a| 
周波数オフセットが設定されたしきい値を超えている場合は、ハードウェアのローカルクロックに問題がある可能性があります。問題が解決しない場合は、テクニカルサポートに連絡して交換を手配してください。



 a| 
NTLK
 a| 
NTP ロック
 a| 
SSM のことです
 a| 
NTP デーモンが外部の時間ソースにロックされていない場合は、指定された外部時間ソースへのネットワーク接続とそれらの可用性および安定性を確認します。



 a| 
NTOF
 a| 
NTP 時間オフセット
 a| 
SSM のことです
 a| 
時間オフセットが設定されたしきい値を超えている場合は、ハードウェアのローカルクロックのオシレーターに問題がある可能性があります。問題が解決しない場合は、テクニカルサポートに連絡して交換を手配してください。



 a| 
NTSJ
 a| 
選択された時間ソースジッタ
 a| 
SSM のことです
 a| 
この値は、ローカルサーバ上の NTP が参照として使用している時間ソースの信頼性と安定性を示します。

アラームがトリガーされた場合は、時間ソースのオシレーターが故障しているか、時間ソースへの WAN リンクに問題がある可能性があります。



 a| 
NTSU
 a| 
NTPステータス
 a| 
SSM のことです
 a| 
「 NTP Status 」の値が「 Not Running 」の場合は、テクニカルサポートに連絡してください。



 a| 
OPST の場合
 a| 
全体的な電源ステータス
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスの電源が推奨される動作電圧と大きく異なる場合にアラームがトリガーされます。

電源装置 A と B のステータスを調べ、どちらの電源装置に異常があるかを確認します。

必要に応じて、電源装置を交換します。



 a| 
OQRT の場合
 a| 
隔離されたオブジェクト
 a| 
LDR
 a| 
StorageGRID システムでオブジェクトが自動的にリストアされたあと、隔離されたオブジェクトを隔離ディレクトリから削除できます。

. サポート * > * ツール * > * グリッドトポロジ * を選択します。
. サイト * > * ストレージノード * > * LDR * > * Verification * > * Configuration * > * Main * の順に選択します。
. ［ * 隔離オブジェクトの削除 * ］ を選択します。
. [ 変更の適用 *] をクリックします。


隔離されたオブジェクトが削除され、数がゼロにリセットされます。



 a| 
ORSU
 a| 
アウトバウンドレプリケーションステータス
 a| 
BLDR 、 BARC
 a| 
アウトバウンドレプリケーションを実行できず、ストレージがオブジェクトを読み出せない状態になっていることを示します。アウトバウンドレプリケーションが手動で無効になった場合にアラームがトリガーされます。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_name > * LDR * > * Replication * > * Configuration * を選択します。

LDR サービスでレプリケーションを実行できない場合にもアラームがトリガーされます。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _grid node_name * > * ldr * > * Storage * を選択します。



 a| 
OSLF
 a| 
シェルフステータス
 a| 
SSM のことです
 a| 
ストレージアプライアンスのストレージシェルフのいずれかのコンポーネントのステータスがデグレードになると、アラームがトリガーされます。ストレージシェルフコンポーネントには、 IOM 、ファン、電源装置、ドライブドロワーが含まれます。このアラームがトリガーされた場合は、アプライアンスのメンテナンス手順を参照してください。



 a| 
PMEM
 a| 
サービスメモリ使用率（パーセント）
 a| 
BADC 、 BAMS 、 BARC 、 BCLB 、 BCMN 、 BCMN 、 BLDR 、 BNMS 、 BSSM 、 BDDS
 a| 
には、 Over Y% RAM の値を指定できます。 Y は、サーバで使用されているメモリの割合を表します。

80% 未満であれば問題ありません。90% を超える場合は問題があると考えられます。

1 つのサービスのメモリ使用率が高い場合は、状況を監視して調査します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
PSAS
 a| 
Power Supply A Status の順に選択します
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスの電源装置 A が推奨される動作電圧と大きく異なる場合にアラームがトリガーされます。

必要に応じて、電源装置 A を交換します



 a| 
PSBS
 a| 
電源装置 B のステータス
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスの電源装置 B が推奨される動作電圧と大きく異なる場合にアラームがトリガーされます。

必要に応じて、電源装置 B を交換します



 a| 
RDTE
 a| 
Tivoli Storage Manager の状態
 a| 
BARC
 a| 
ターゲットタイプが「 Tivoli Storage Manager （ TSM ）」のアーカイブノードにのみ適用されます。

「 Tivoli Storage Manager State 」の値が「 Offline 」の場合は、「 Tivoli Storage Manager Status 」を確認して問題を解決します。

コンポーネントをオンラインに戻します。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * ARC * > * Target * > * Configuration * > * Main * を選択し、 * Tivoli Storage Manager State * > * Online * を選択して、 * Apply Changes * をクリックします。



 a| 
RDTU
 a| 
Tivoli Storage Manager のステータス
 a| 
BARC
 a| 
ターゲットタイプが「 Tivoli Storage Manager （ TSM ）」のアーカイブノードにのみ適用されます。

「 Tivoli Storage Manager Status 」の値が「 Configuration Error 」で、アーカイブノードを StorageGRID システムに追加したばかりの場合は、 TSM ミドルウェアサーバが正しく設定されていることを確認します。

「 Tivoli Storage Manager Status 」の値が「 Connection Failure 」または「 Connection Failure 、 Retrying 」の場合は、 TSM ミドルウェアサーバのネットワーク設定、および TSM ミドルウェアサーバと StorageGRID システムの間のネットワーク接続を確認します。

「Tivoli Storage Manager Status」の値が「Authentication Failure」または「Authentication Failure、Reconnecting」の場合、StorageGRID システムはTSMミドルウェアサーバに接続できますが、接続を認証できません。TSM ミドルウェアサーバでユーザ、パスワード、および権限が正しく設定されていることを確認し、サービスを再起動します。

「 Tivoli Storage Manager Status 」の値が「 Session Failure 」の場合は、確立されたセッションが予期せずに切断されています。TSM ミドルウェアサーバと StorageGRID システムの間のネットワーク接続を確認します。ミドルウェアサーバにエラーがないかを確認します。

「 Tivoli Storage Manager Status 」の値が「 Unknown Error 」の場合は、テクニカルサポートに連絡してください。



 a| 
RIRF
 a| 
インバウンドレプリケーション -- 失敗
 a| 
BLDR 、 BARC
 a| 
このアラームは、負荷が高いときやネットワークが一時的に停止しているときに発生する可能性があります。このアラームは、システムアクティビティが減ると解除されます。レプリケーションの失敗回数が増え続ける場合は、ネットワークに問題がないかを調べ、ソースとデスティネーションの LDR サービスおよび ARC サービスがオンラインで使用可能な状態になっていることを確認します。

カウントをリセットするには、 * support * > * Tools * > * Grid topology * を選択し、 * _site _ * > * _grid node_name > * ldr * > * Replication * > * Configuration * > * Main * を選択します。「 * インバウンド複製エラー数のリセット * 」を選択し、「 * 変更を適用 * 」をクリックします。



 a| 
RIRQ
 a| 
Inbound Replications -- Queued （インバウンドレプリケーション -- キューイング済み
 a| 
BLDR 、 BARC
 a| 
負荷が高いときやネットワークが一時的に停止しているときにアラームが発生することがあります。このアラームは、システムアクティビティが減ると解除されます。レプリケーションのキューが増え続ける場合は、ネットワークに問題がないかを調べ、ソースとデスティネーションの LDR サービスおよび ARC サービスがオンラインで使用可能な状態になっていることを確認します。



 a| 
RORQ
 a| 
Outbound Replications - Queued （アウトバウンドレプリケーション - キューイング済み
 a| 
BLDR 、 BARC
 a| 
アウトバウンドレプリケーションのキューには、 ILM ルールを満たすためにコピーされるオブジェクトデータと、クライアントから要求されたオブジェクトが含まれます。

システムが過負荷になると、アラームが発生することがあります。このアラームはシステムアクティビティが減ると解除されるため、しばらく状況を監視します。アラームが繰り返し発生する場合は、ストレージノードを追加して容量を増やします。



 a| 
SAVP の
 a| 
使用可能な合計スペース（割合）
 a| 
LDR
 a| 
使用可能なスペースがしきい値の下限に達した場合は、 StorageGRID システムを拡張するか、オブジェクトデータをアーカイブノード経由でアーカイブに移動します。



 a| 
SCAS
 a| 
ステータス
 a| 
CMN
 a| 
アクティブなグリッドタスクの「 Status 」の値が「 Error 」の場合は、グリッドタスクのメッセージを検索します。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_name * > * CMN * > * Grid Tasks * > * Overview * > * Main * の順に選択します。グリッドタスクのメッセージにエラーに関する情報が表示されます（「check failed on node 12130011」など）。

問題の調査と修正が完了したら、グリッドタスクを再起動します。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_name * > * CMN * > * Grid Tasks * > * Configuration * > * Main * を選択し、 * Actions * > * Run * を選択します。

「Stopped」中のグリッドタスクの「Status」の値が「Error」の場合は、グリッドタスクをもう一度終了します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
SCEP （ SCEP ）
 a| 
ストレージ API サービスエンドポイントの証明書有効期限
 a| 
CMN
 a| 
ストレージ API エンドポイントへのアクセスに使用される証明書の有効期限が近づくとトリガーされます。

. [ * configuration * > * Security * > * Certificates * ] を選択します。
. Global * タブで、 * S3 および Swift API 証明書 * を選択します。
. link:../admin/configuring-custom-server-certificate-for-storage-node.html#add-a-custom-s3-and-swift-api-certificate["新しい S3 および Swift API 証明書をアップロードします。"]




 a| 
SCHR
 a| 
ステータス
 a| 
CMN
 a| 
過去のグリッドタスクの「 Status 」の値が「 Aborted 」の場合は、原因を調べ、必要に応じてもう一度タスクを実行します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
SCSA
 a| 
ストレージコントローラ A
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスにストレージコントローラ A を搭載した問題 があると、アラームがトリガーされます。

必要に応じて、コンポーネントを交換します。



 a| 
SCSB
 a| 
ストレージコントローラ B
 a| 
SSM のことです
 a| 
StorageGRID アプライアンスにストレージコントローラ B を搭載した問題 がある場合にアラームがトリガーされます。

必要に応じて、コンポーネントを交換します。

一部のアプライアンスモデルには、ストレージコントローラBが搭載されていません



 a| 
SHLH
 a| 
健常性
 a| 
LDR
 a| 
オブジェクトストアの「 Health 」の値が「 Error 」の場合は、以下を確認して修正します。

* マウントされているボリュームの問題
* ファイルシステムエラー




 a| 
slsa
 a| 
CPU Load Average （ CPU 負荷平均）
 a| 
SSM のことです
 a| 
この値が大きいほど、システムはビジーになります。

「 CPU Load Average 」の値が高いまま推移している場合は、システムのトランザクション数を調べ、一時的な負荷の増加によるものかどうかを確認する必要があります。CPU 負荷の平均値のグラフを表示します。サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_name > * SSM * > * Resources * > * Reports * > * Charts * を選択します。

システムの負荷が高くない状況でも問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
SMST
 a| 
Log Monitor State の略
 a| 
SSM のことです
 a| 
「 Log Monitor State 」の値が「 Connected 」にならない状態が続く場合は、テクニカルサポートに連絡してください。



 a| 
SMTT
 a| 
合計イベント数
 a| 
SSM のことです
 a| 
「 Total Events 」の値が 0 より大きい場合は、原因 となる既知のイベント（ネットワーク障害など）がないかを確認します。これらのエラーが解消されていない（カウントが 0 にリセットされていない）と、 Total Events アラームがトリガーされることがあります。

問題 が解決したら、カウンタをリセットしてアラームを解除します。ノード * > * _site * > * _grid node_name > * Events * > * Reset event counts * を選択します。


NOTE: イベント数をリセットするには、Gridトポロジページの設定権限が必要です。

「 Total Events 」の値が 0 の場合や数が増えて問題が解決しない場合は、テクニカルサポートに連絡してください。



 a| 
SNST
 a| 
ステータス
 a| 
CMN
 a| 
グリッドタスクバンドルの格納に問題があることを示します。「 Status 」の値が「 Checkpoint Error 」または「 Quorum Not Reached 」の場合は、半数を超える ADC サービスが StorageGRID システムに接続されていることを確認し、そのまま数分待ちます。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
SOSS
 a| 
ストレージオペレーティングシステムのステータス
 a| 
SSM のことです
 a| 
SANtricity OSでStorageGRIDアプライアンスのコンポーネントを含む問題「Needs Attention」が報告されるとアラームがトリガーされます。

[* nodes （ノード） ] を選択します次に、 * アプライアンス・ストレージ・ノード * > * ハードウェア * を選択します。下にスクロールして各コンポーネントのステータスを確認します。SANtricity OSでは、他のアプライアンスコンポーネントをチェックして問題 を分離します。



 a| 
SSMA
 a| 
SSMステータス
 a| 
SSM のことです
 a| 
「 SSM Status 」の値が「 Error 」の場合は、「 * support * > * Tools * > * Grid topology * 」を選択し、「 * _site _ * > * _ grid node_* > * SSM * > * Main * and * SSM * > * Overview * > * Alarms * 」を選択して、アラームの原因 を判断します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
SSME
 a| 
SSMの状態
 a| 
SSM のことです
 a| 
「 SSM State 」の値が「 Standby 」の場合は、しばらく状況を監視し、問題が解決しなければテクニカルサポートに連絡します。

「SSM State」の値が「Offline」の場合は、サービスを再起動します。問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
SSTS のコマンドです
 a| 
ストレージステータス
 a| 
BLDR
 a| 
「 Storage Status 」の値が「 Insufficient Usable Space 」の場合は、ストレージノードの使用可能なストレージがなくなり、データの取り込みが他の使用可能なストレージノードにリダイレクトされています。このグリッドノードからの読み出し要求は引き続き可能です。

ストレージを追加する必要があります。エンドユーザの作業には影響しませんが、ストレージを追加しないかぎりアラームは解除されません。

「 Storage Status 」の値が「 Volume （ s ） Unavailable 」の場合は、ストレージの一部が使用できない状態になっています。これらのボリュームでは格納も読み出しも実行できません。ボリュームの健全性を確認して詳細を確認します。 * support * > * Tools * > * Grid topology * を選択します。次に、 * _site _ * > * _ grid node_* > * LDR * > * Storage * > * Overview * > * Main * を選択します。ボリュームの健全性がオブジェクトストアのリストに表示されます。

「 Storage Status 」の値が「 Error 」の場合は、テクニカルサポートに連絡してください。

link:../troubleshoot/troubleshooting-storage-status-alarm.html["Storage Status （ SSTS ）アラームをトラブルシューティングします"]



 a| 
SVST
 a| 
ステータス
 a| 
SSM のことです
 a| 
このアラームは、サービスの実行の問題に関する他のアラームが解決されると解除されます。ソース側のサービスのアラームを追跡してリストアします。

サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * SSM * > * Services * > * Overview * > * Main * の順に選択します。サービスのステータスが「 Not Running 」と表示される場合は、状態が「 Administratively Down 」です。サービスのステータスが「 Not Running 」と表示される状況は次のとおりです。

* サービスが手動で停止されました (`/etc/init.d/<service\> stop`）。
* MySQL データベースを持つ問題 があり 'Server Manager によって MI サービスがシャットダウンされます
* グリッドノードが追加されたが開始されていない。
* インストール時にグリッドノードが管理ノードに接続されていない。


サービスが「Not Running」と表示される場合は、サービスを再起動します (`/etc/init.d/<service\> restart`）。

このアラームは、ストレージノードに対するメタデータストア（ Cassandra データベース）のリビルドが必要なことを示している可能性もあります。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。

link:../troubleshoot/troubleshooting-metadata-issues.html["Services ： Status - Cassandra （ SVST ）アラームのトラブルシューティングを行います"]



 a| 
TMEM
 a| 
メモリを取り付けた
 a| 
SSM のことです
 a| 
ノードの搭載メモリが 24GiB 未満の場合、パフォーマンスの問題が発生し、システムが不安定になることがあります。システムの搭載メモリを 24GiB 以上に増やす必要があります。



 a| 
TPOP
 a| 
保留中の処理です
 a| 
ADC
 a| 
メッセージのキューが形成されている場合、 ADC サービスが過負荷状態になっている可能性があります。StorageGRID システムに接続されている ADC サービスの数が少なすぎることが考えられます。大規模な環境では、 ADC サービスのコンピューティングリソースを増やすか、システムに ADC サービスを追加することが必要になる可能性があります。



 a| 
UMEM
 a| 
使用可能なメモリ
 a| 
SSM のことです
 a| 
使用可能な RAM が少なくなった場合は、ハードウェア問題 とソフトウェア RAM のどちらであるかを確認します。ハードウェア問題 以外の場合、または使用可能なメモリが 50MB （デフォルトのアラームのしきい値）を下回った場合は、テクニカルサポートに連絡してください。



 a| 
VMFI
 a| 
エントリが使用可能です
 a| 
SSM のことです
 a| 
追加のストレージが必要なことを示しています。テクニカルサポートにお問い合わせください。



 a| 
VMFR
 a| 
使用可能なスペース
 a| 
SSM のことです
 a| 
「 Space Available 」の値が低すぎる（アラームのしきい値を参照）場合は、大きくなりすぎているログファイルや大量のディスクスペースを消費しているオブジェクト（アラームのしきい値を参照）がないかどうかを調べ、必要に応じてそれらを減らすか削除します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
VMST
 a| 
ステータス
 a| 
SSM のことです
 a| 
マウントされたボリュームの「 Status 」の値が「 Unknown 」の場合にアラームがトリガーされます。値が「Unknown」または「Offline」の場合は、基盤となるストレージデバイスの問題が原因でボリュームをマウントまたはアクセスできないことを示している可能性があります。



 a| 
VPRI （ VPRI ）
 a| 
検証の優先順位
 a| 
BLDR 、 BARC
 a| 
「 Verification Priority 」のデフォルトの値は「 Adaptive 」です。「 Verification Priority 」が「 High 」に設定されている場合、ストレージの検証が優先されてサービスの通常の運用に影響する可能性があるため、アラームがトリガーされます。



 a| 
VSTU
 a| 
オブジェクトの検証ステータス
 a| 
BLDR
 a| 
サポート * > * ツール * > * グリッドトポロジ * を選択します。次に、 * _site _ * > * _ grid node_* > * LDR * > * Storage * > * Overview * > * Main * を選択します。

オペレーティングシステムで、ブロックデバイスやファイルシステムのエラーの兆候がないかどうかを確認します。

「 Object Verification Status 」の値が「 Unknown Error 」の場合は、通常、下位レベルのファイルシステムやハードウェアの問題（ I/O エラー）が原因で、ストレージ検証タスクが格納されたコンテンツにアクセスできないことを示します。テクニカルサポートにお問い合わせください。



 a| 
XAMS の場合
 a| 
到達不能な監査リポジトリ
 a| 
BADC 、 BARC 、 BCLB 、 BCMN 、 BLDR 、 BNMS
 a| 
管理ノードをホストするサーバへのネットワーク接続を確認します。

問題が解決しない場合は、テクニカルサポートにお問い合わせください。

|===