---
permalink: monitor/logs-files-reference.html 
sidebar: sidebar 
keywords: log, logs, log files 
summary: StorageGRID には、イベント、診断メッセージ、およびエラー状態をキャプチャするために使用されるログが用意されています。テクニカルサポートにトラブルシューティングを依頼すると、ログファイルを収集して転送するように求められることがあります。 
---
= ログファイルリファレンス：概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID には、イベント、診断メッセージ、およびエラー状態をキャプチャするために使用されるログが用意されています。テクニカルサポートにトラブルシューティングを依頼すると、ログファイルを収集して転送するように求められることがあります。

ログは次のように分類されます。

* link:storagegrid-software-logs.html["StorageGRID ソフトウェアのログ"]
* link:deployment-and-maintenance-logs.html["導入とメンテナンスのログ"]
* link:logs-for-third-party-software.html["サードパーティソフトウェアのログ"]
* link:about-bycast-log.html["bycast.log について"]



NOTE: 各ログタイプの詳細情報は参考用です。これらのログは、テクニカルサポートが高度なトラブルシューティングに使用することを目的としています。監査ログやアプリケーションログファイルを使用して問題の履歴を再構築する高度な手法については、この手順では説明していません。



== ログにアクセスします

ログにアクセスするには、次の手順を実行します link:collecting-log-files-and-system-data.html["ログファイルとシステムデータを収集します"] 1つ以上のノードから単一のログファイルアーカイブとしてアーカイブ。または、プライマリ管理ノードを使用できない場合や特定のノードに到達できない場合は、次の手順で各グリッドノードの個別のログファイルにアクセスできます。

. 次のコマンドを入力します。 `ssh admin@grid_node_IP`
. に記載されているパスワードを入力します `Passwords.txt` ファイル。
. 次のコマンドを入力してrootに切り替えます。 `su -`
. に記載されているパスワードを入力します `Passwords.txt` ファイル。




== ログファイルのカテゴリ

StorageGRID ログファイルアーカイブには、カテゴリごとに説明されているログ、およびメトリックと debug コマンドの出力が含まれている追加ファイルが含まれています。

[cols="1a,3a"]
|===
| アーカイブの場所 | 説明 


| 監査  a| 
通常のシステム動作中に生成される監査メッセージです。



| base-os-logs  a| 
StorageGRID イメージのバージョンなど、ベースとなるオペレーティングシステムの情報。



| バンドル  a| 
グローバル構成情報（バンドル）。



| Cassandra  a| 
Cassandra データベース情報と Reaper 修復ログ。



| EC  a| 
現在のノードに関するVCS情報と、プロファイルIDによるECグループ情報。



| グリッド（ Grid ）  a| 
デバッグを含む一般的なグリッドログ (`bycast.log`）および `servermanager` ログ。



| grid.xml  a| 
グリッド構成ファイルをすべてのノードで共有



| シュラウド  a| 
ハイアベイラビリティグループの指標とログ。



| をインストールします  a| 
`Gdu-server` インストールログを確認します。



| lumberjack.log  a| 
ログ収集に関連するデバッグメッセージ。



| Lambda - アービトレータ  a| 
S3 Select プロキシ要求に関連するログです。



| 指標  a| 
Grafana 、 Jaeger 、ノードエクスポータ、および Prometheus のサービスログ。



| 計算ミス  a| 
Miscd アクセスログとエラーログ。



| MySQL  a| 
MariaDB データベースの設定と関連ログ。



| ネット  a| 
ネットワーク関連のスクリプトおよび Dyip サービスによって生成されるログ。



| nginx  a| 
ロードバランサとグリッドフェデレーションの設定ファイルとログ。Grid Manager と Tenant Manager のトラフィックログも含まれます。



| nginx-gw と入力します  a| 
ロードバランサとグリッドフェデレーションの設定ファイルとログ。



| NTP  a| 
NTP 構成ファイルとログ：



| OS  a| 
ノードとグリッドの状態ファイル（サービスを含む） `pid`。



| その他  a| 
にログファイルがあります `/var/local/log` 他のフォルダには収集されていません。



| パフォーマンス  a| 
CPU 、ネットワーク、ディスク I/O のパフォーマンス情報



| prometheus-data  a| 
ログ収集に Prometheus データが含まれている場合、現在の Prometheus 指標。



| プロビジョニング  a| 
グリッドのプロビジョニングプロセスに関連するログです。



| ラフト  a| 
プラットフォームサービスで使用される Raft クラスタのログ。



| SSH  a| 
SSHの設定およびサービスに関連するログ。



| SNMP  a| 
SNMP エージェント設定およびアラーム許可 / 拒否リストは、 SNMP 通知の送信に使用されます。



| ソケット - データ  a| 
ネットワークデバッグ用のソケットデータ。



| system-commands.txt  a| 
StorageGRID コンテナコマンドの出力。ネットワークやディスクの使用状況などのシステム情報が含まれます。

|===