---
permalink: monitor/managing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: how to manage alerts, what are alerts, what are alarms 
summary: StorageGRID アラートシステムは、注意が必要な運用上の問題について通知するように設計されています。従来のアラームシステムは廃止されました。 
---
= アラートとアラームの管理：概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アラートシステムは、注意が必要な運用上の問題について通知するように設計されています。従来のアラームシステムは廃止されました。



== アラートシステム

アラートシステムは、 StorageGRID システムで発生する可能性のある問題を監視する主要なツールです。アラートシステムは、問題を検出、評価、解決するための使いやすいインターフェイスを提供します。

アラートルールの条件が true と評価されると、特定の重大度レベルでアラートがトリガーされます。アラートがトリガーされると、次の処理が行われます。

* Grid Managerのダッシュボードにアラートの重大度アイコンが表示され、現在のアラートの数が増分されます。
* このアラートはノード * の概要ページおよび * ノード * > * _node_name > * Overview * タブに表示されます。
* SMTP サーバを設定し、受信者に E メールアドレスを提供している場合は、 E メール通知が送信されます。
* StorageGRID SNMP エージェントが設定されている場合は、簡易ネットワーク管理プロトコル（ SNMP ）通知が送信されます。




== レガシーアラームシステム

アラートと同様に、属性が定義されたしきい値に達すると、特定の重大度レベルでアラームがトリガーされます。ただし、アラートとは異なり、無視しても問題なくアラートがトリガーされるアラームが多数あるため、 E メールや SNMP 通知が大量に送信されることがあります。


NOTE: アラームシステムは廃止され、今後のリリースで削除される予定です。引き続き古いアラームを使用する場合は、できるだけ早くアラートシステムに完全に移行してください。

アラームがトリガーされると、次の処理が行われます。

* このアラームは、 *support*>* Alarms （レガシー） *>* Current alarms * ページに表示されます。
* SMTP サーバを設定して 1 つ以上のメーリングリストを設定している場合は、 E メール通知が送信されます。
* StorageGRID SNMP エージェントを設定している場合は、 SNMP 通知が送信されることがあります。（SNMP通知は、すべてのアラームまたは重大度について送信されるわけではありません）。

