---
permalink: maintain/downloading-hotfix-file.html 
sidebar: sidebar 
keywords: storagegrid, hotfix, download 
summary: ホットフィックスを適用する前に、ホットフィックスファイルをダウンロードする必要があります。 
---
= ホットフィックスファイルをダウンロードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットフィックスを適用する前に、ホットフィックスファイルをダウンロードする必要があります。

.手順
. に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップのダウンロード： StorageGRID"^]。
. [ 利用可能なソフトウェア ] の下にある下矢印をクリックすると、ダウンロード可能なホットフィックスのリストが表示されます。
+

NOTE: ホットフィックスファイルのバージョンの形式は 11.4_.x.y__ です。

. 更新に含まれている変更を確認します。
+

NOTE: あなたがちょうど持っているなら link:configuring-replacement-primary-admin-node.html["プライマリ管理ノードをリカバリしました"] また、ホットフィックスを適用する必要がある場合は、他のグリッドノードにインストールされている同じバージョンのホットフィックスを選択します。

+
.. ダウンロードするホットフィックスのバージョンを選択し、 * Go * を選択します。
.. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
.. エンドユーザライセンス契約を読んで同意します。
+
選択したバージョンのダウンロードページが表示されます。

.. ホットフィックスをダウンロードします `readme.txt` ファイルをクリックして、ホットフィックスに含まれる変更の概要を確認します。


. ホットフィックスのダウンロードボタンを選択してファイルを保存します。
+

NOTE: このファイルの名前は変更しないでください。

+

NOTE: macOSデバイスを使用している場合、ホットフィックスファイルは自動的にとして保存されます `.txt` ファイル。その場合は、を使用せずにファイルの名前を変更する必要があります `.txt` 内線番号。

. ダウンロードする場所を選択し、「 * 保存 * 」を選択します。

