---
permalink: maintain/powering-down-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: ホストの電源をオフにする前に、そのホスト上のすべてのグリッドノードのサービスを停止する必要があります。 
---
= ホストの電源をオフにします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストの電源をオフにする前に、そのホスト上のすべてのグリッドノードのサービスを停止する必要があります。

.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。


+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。

. ノードで実行中のすべてのサービスを停止します。 `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。

. ホストの各ノードについて、手順 1 と 2 を繰り返します。
. Linux ホストの場合：
+
.. ホストオペレーティングシステムにログインします。
.. ノードを停止します。 `storagegrid node stop`
.. ホストオペレーティングシステムをシャットダウンします。


. VMware仮想マシンで実行さ問題 れているノード、またはアプライアンスノードの場合、shutdownコマンドを使用します。 `shutdown -h now`
+
この手順は、の結果に関係なく実行します `service servermanager stop` コマンドを実行します

+

NOTE: 問題 を実行した後 `shutdown -h now` アプライアンスノードでコマンドを実行するには、アプライアンスの電源を再投入してノードを再起動する必要があります。

+
アプライアンスの場合、このコマンドはコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードの電源をオフにする場合は、アプライアンスの手順に従います。
+
[role="tabbed-block"]
====
.SGF6112を参照してください
--
.. アプライアンスの電源をオフにします。
.. 青色の電源 LED が消灯するまで待ちます。


--
.SG6000を使用します
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


--
.SG5700
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。


--
.SG100またはSG1000
--
.. アプライアンスの電源をオフにします。
.. 青色の電源 LED が消灯するまで待ちます。


--
====
. コマンドシェルからログアウトします。 `exit`


.関連情報
https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112ストレージアプライアンス"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000 ストレージアプライアンス"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700ストレージアプライアンス"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100 および SG1000 サービスアプライアンス"^]
