---
permalink: maintain/preparing-appliance-for-reinstallation-platform-replacement-only.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: サービスアプライアンスでホストされていたグリッドノードをリカバリする場合は、最初に StorageGRID ソフトウェアを再インストールするアプライアンスを準備する必要があります。 
---
= 再インストールのためのアプライアンスの準備（プラットフォームの交換のみ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスアプライアンスでホストされていたグリッドノードをリカバリする場合は、最初に StorageGRID ソフトウェアを再インストールするアプライアンスを準備する必要があります。

この手順 は、サービスアプライアンスでホストされていた障害ノードを交換する場合にのみ実行してください。障害ノードが元 々 VMwareまたはLinuxホストでホストされていた場合は、次の手順を実行しないでください。

.手順
. 障害が発生したグリッドノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。


+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。

. StorageGRID ソフトウェアをアプライアンスにインストールする準備をします。入力するコマンド `sgareinstall`
. 続行するかどうかを尋ねられたら、と入力します。 `y`
+
アプライアンスがリブートされ、 SSH セッションが終了します。通常は 5 分程度で StorageGRID アプライアンスインストーラが使用可能になりますが、場合によっては最大で 30 分待つ必要があります。

+
サービスアプライアンスがリセットされ、グリッドノード上のデータにアクセスできなくなります。元のインストールプロセスで設定した IP アドレスはそのまま使用する必要がありますが、手順 の完了時に確認しておくことを推奨します。

+
を実行したあとに `sgareinstall` コマンドを実行すると、StorageGRIDでプロビジョニングされたすべてのアカウント、パスワード、およびSSHキーが削除され、新しいホストキーが生成されます。


