---
permalink: maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html 
sidebar: sidebar 
keywords: storagegrid, recover, maintenance, maintain, failed storage volumes, failed volumes, cassandra, cassandra rebuild, rebuild cassandra, cassandra database 
summary: 障害が発生したストレージボリュームでストレージを再フォーマットして再マウントするスクリプトを実行し、システムが必要であると判断した場合にはストレージノードの Cassandra データベースを再構築する必要があります。 
---
= 障害ストレージボリュームをリカバリし、 Cassandra データベースを再構築します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したストレージボリュームでストレージを再フォーマットして再マウントするスクリプトを実行し、システムが必要であると判断した場合にはストレージノードの Cassandra データベースを再構築する必要があります。

.作業を開始する前に
* を使用することができます `Passwords.txt` ファイル。
* サーバ上のシステムドライブに損傷はありません。
* 障害の原因 が特定され、必要に応じて交換用ストレージハードウェアがすでに入手されている。
* 交換用ストレージの合計サイズは、元のストレージと同じです。
* ストレージノードの運用停止処理が進行中でないこと、またはノードの手順 の運用停止処理が一時停止されていることを確認しておきます（ Grid Manager で、 * maintenance * > * Tasks * > * Decommission * を選択します）。
* 拡張が進行中でないことを確認しておきます（ Grid Manager で、 * maintenance * > * Tasks * > * Expansion * を選択します。）
* これで完了です link:reviewing-warnings-about-storage-volume-recovery.html["ストレージボリュームのリカバリに関する警告を確認"]。


.手順
. 必要に応じて、前述の手順で特定してアンマウントした障害ストレージボリュームに関連付けられた、障害が発生した物理または仮想ストレージを交換します。
+
この手順ではボリュームを再マウントしないでください。ストレージが再マウントされてに追加されます `/etc/fstab` 後の手順で実行します。

. Grid Managerで、* nodes *>に移動します `*appliance Storage Node*` >*ハードウェア*。ページの[RAID Appliance]セクションで、ストレージStorageGRID モードが正常であることを確認します。
. 障害が発生したストレージノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. テキストエディタ（viまたはvim）を使用して、から障害ボリュームを削除します `/etc/fstab` ファイルを選択し、ファイルを保存します。
+

NOTE: で障害ボリュームをコメントアウトします `/etc/fstab` ファイルが不十分です。ボリュームをから削除する必要があります `fstab` を使用してリカバリ処理を実行すると、のすべての行が検証されます `fstab` マウントされたファイルシステムとファイルが一致している。

. 障害ストレージボリュームを再フォーマットし、必要に応じて Cassandra データベースを再構築します。入力するコマンド `reformat_storage_block_devices.rb`
+
** ストレージボリューム0がアンマウントされると、Cassandraサービスが停止していることを示すプロンプトとメッセージが表示されます。
** 必要に応じて Cassandra データベースを再構築するよう求められます。
+
*** 警告を確認します。いずれの状況も該当しない場合は、 Cassandra データベースを再構築します。「 * y * 」と入力します
*** 複数のストレージノードがオフラインの場合、または別のストレージノードが 15 日以内に再構築されている場合は、「 * n * 」と入力します
+
スクリプトは Cassandra を再構築せずに終了します。テクニカルサポートにお問い合わせください。



** ストレージノード上の各rangedbドライブについて尋ねられたときは、次のようになります。 `Reformat the rangedb drive _<name>_ (device _<major number>:<minor number>_)? [y/n]?`で、次のいずれかの応答を入力します。
+
*** * y * ：エラーが発生したドライブを再フォーマットします。ストレージボリュームが再フォーマットされ、にストレージボリュームが追加されます `/etc/fstab` ファイル。
*** *n*ドライブにエラーがなく、ドライブを再フォーマットしない場合。
+

NOTE: *n * を選択すると、スクリプトが終了します。ドライブをマウントするか（ドライブ上のデータを保持する必要があり、ドライブが誤ってアンマウントされた場合）、ドライブを取り外します。次に、を実行します `reformat_storage_block_devices.rb` コマンドをもう一度実行します。

+

NOTE: 一部の StorageGRID リカバリ手順では、 Reaper を使用して Cassandra の修復を処理します。関連サービスまたは必要なサービスが開始されるとすぐに修理が自動的に行われます。スクリプトの出力に「reaper」または「cassandra repair」と記載されていることがあります。 修復が失敗したことを示すエラーメッセージが表示された場合は、エラーメッセージに示されているコマンドを実行します。

+
次の出力例では、ドライブが表示されています `/dev/sdf` 再フォーマットが必要で、Cassandraを再構築する必要はありませんでした。

+
[listing]
----
root@DC1-S1:~ # reformat_storage_block_devices.rb
Formatting devices that are not in use...
Skipping in use device /dev/sdc
Skipping in use device /dev/sdd
Skipping in use device /dev/sde
Reformat the rangedb drive /dev/sdf (device 8:64)? [Y/n]? y
Successfully formatted /dev/sdf with UUID b951bfcb-4804-41ad-b490-805dfd8df16c
All devices processed
Running: /usr/local/ldr/setup_rangedb.sh 12368435
Cassandra does not need rebuilding.
Starting services.
Informing storage services of new volume

Reformatting done.  Now do manual steps to
restore copies of data.
----






ストレージボリュームの再フォーマットと再マウントが完了し、必要なCassandra処理が完了したら、次のことを実行できます link:../maintain/restoring-volume.html["Grid Managerを使用してオブジェクトデータをリストアする"]。
