---
permalink: maintain/restoring-audit-log-on-recovered-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore audit log, primary admin node 
summary: 障害が発生したプライマリ管理ノードから監査ログを保存できた場合は、リカバリするプライマリ管理ノードにそのログをコピーできます。 
---
= リカバリされたプライマリ管理ノードで監査ログをリストアする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したプライマリ管理ノードから監査ログを保存できた場合は、リカバリするプライマリ管理ノードにそのログをコピーできます。

.作業を開始する前に
* リカバリした管理ノードがインストールされて実行されている。
* 元の管理ノードで障害が発生したあとに、監査ログを別の場所にコピーしておきます。


.このタスクについて
管理ノードで障害が発生すると、その管理ノードに保存された監査ログが失われる可能性があります。障害が発生した管理ノードから監査ログをコピーし、リカバリされた管理ノードにリストアすることで、データを損失から守ることができる場合があります。障害によっては、障害が発生した管理ノードから監査ログをコピーできない場合があります。その場合、管理ノードが複数ある環境ではすべての管理ノードに監査ログがレプリケートされるため、別の管理ノードから監査ログをリカバリできます。

管理ノードが1つしかなく、障害ノードから監査ログをコピーできない場合は、リカバリされた管理ノードで、新規インストールの場合と同様に監査ログへのイベントの記録が開始されます。

ロギング機能を復旧させるために、管理ノードはできるだけ早くリカバリする必要があります。

[NOTE]
====
デフォルトでは、監査情報は管理ノードの監査ログに送信されます。次のいずれかに該当する場合は、これらの手順をスキップしてかまいません。

* 外部 syslog サーバを設定し、管理ノードではなく syslog サーバに監査ログを送信するようになりました。
* 監査メッセージを生成したローカルノードにのみ保存するように明示的に指定します。


を参照してください link:../monitor/configure-audit-messages.html["監査メッセージとログの送信先を設定します"] を参照してください。

====
.手順
. リカバリした管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@recovery_Admin_Node_IP`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。


+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。

. 保持されている監査ファイルを確認します。 `cd /var/local/log`
. 保持されている監査ログファイルをリカバリされた管理ノードにコピーします。 `scp admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs/YYYY* .`
+
プロンプトが表示されたら、 admin のパスワードを入力します。

. セキュリティ上の理由により、監査ログがリカバリされた管理ノードにコピーされたことを確認したら、監査ログを障害グリッドノードから削除します。
. リカバリされた管理ノードで、監査ログファイルのユーザとグループの設定を更新します。 `chown ams-user: bycast *`
. rootとしてログアウトします。 `exit`


監査共有への既存のクライアントアクセスもリストアする必要があります。詳細については、を参照してください link:../admin/configuring-audit-client-access.html["監査クライアントアクセスを設定します"]。
