---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: グリッドノードは、ノードのコマンドシェルからシャットダウンできます。 
---
= グリッドノードをシャットダウンします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードは、ノードのコマンドシェルからシャットダウンできます。

.作業を開始する前に
* を使用することができます `Passwords.txt` ファイル。


.このタスクについて
この手順 を実行する前に、次の考慮事項を確認してください。

* 通常は、業務の中断を避けるために、一度に複数のノードをシャットダウンすることは避けてください。
* ドキュメントまたはテクニカルサポートから明示的に指示がないかぎり、メンテナンス手順 の実行中はノードをシャットダウンしないでください。
* シャットダウンプロセスは、ノードがインストールされている場所によって次のように異なります。
+
** VMware ノードをシャットダウンすると、仮想マシンがシャットダウンされます。
** Linux ノードをシャットダウンすると、コンテナがシャットダウンされます。
** StorageGRID アプライアンスノードをシャットダウンすると、コンピューティングコントローラがシャットダウンされます。


* サイトで複数のストレージノードをシャットダウンする場合は、ノードをシャットダウンする前に、そのサイトでのオブジェクトの取り込みを約1時間停止します。
+
いずれかのILMルールで* Dual commit *取り込みオプションが使用されている場合（またはルールで* Balanced *オプションが使用されていて必要なすべてのコピーをすぐに作成できない場合）、StorageGRID は新たに取り込まれたオブジェクトを同じサイトの2つのストレージノードにただちにコミットし、あとでILMを評価します。サイトで複数のストレージノードがシャットダウンされている場合は、シャットダウン中に新たに取り込んだオブジェクトにアクセスできない可能性があります。使用可能なストレージノードがサイトで少なすぎる場合も、書き込み処理が失敗する可能性があります。を参照してください link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]。



.手順
. グリッドノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。


+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。

. すべてのサービスを停止します。 `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。

. VMware仮想マシンで実行さ問題 れているノード、またはアプライアンスノードの場合、shutdownコマンドを使用します。 `shutdown -h now`
+
この手順は、の結果に関係なく実行します `service servermanager stop` コマンドを実行します

+

NOTE: 問題 を実行した後 `shutdown -h now` アプライアンスノードでコマンドを実行するには、アプライアンスの電源を再投入してノードを再起動する必要があります。

+
アプライアンスの場合、このコマンドはコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードの電源をオフにする場合は、アプライアンスの手順に従います。
+
[role="tabbed-block"]
====
.SG6160
--
.. SG6100-CNストレージコントローラの電源をオフにします。
.. SG6100-CNストレージコントローラの青色の電源LEDが消灯するまで待ちます。


--
.SGF6112を参照してください
--
.. アプライアンスの電源をオフにします。
.. 青色の電源 LED が消灯するまで待ちます。


--
.SG6000を使用します
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


--
.SG5800
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. SANtricity システムマネージャのホームページで、「 * 進行中の処理を表示」を選択します。
.. すべての処理が完了したことを確認してから、次の手順に進みます。
.. コントローラシェルフの両方の電源スイッチをオフにし、コントローラシェルフのすべてのLEDが消灯するまで待ちます。


--
.SG5700
--
.. ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

.. アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。


--
.SG100またはSG1000
--
.. アプライアンスの電源をオフにします。
.. 青色の電源 LED が消灯するまで待ちます。


--
====

