---
permalink: maintain/stopping-services-and-shutting-down-grid-nodes.html 
sidebar: sidebar 
keywords: recover, stop services, shut down nodes, node shutdown 
summary: StorageGRID システムの電源をオフにするには、各グリッドノードで実行されているすべてのサービスを停止してから、すべての VMware 仮想マシン、コンテナエンジン、および StorageGRID アプライアンスをシャットダウンする必要があります。 
---
= サービスを停止し、グリッドノードをシャットダウンします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムの電源をオフにするには、各グリッドノードで実行されているすべてのサービスを停止してから、すべての VMware 仮想マシン、コンテナエンジン、および StorageGRID アプライアンスをシャットダウンする必要があります。

.このタスクについて
最初に管理ノードとゲートウェイノードのサービスを停止してから、ストレージノードのサービスを停止します。

この方法なら、プライマリ管理ノードを使用して他のグリッドノードのステータスをできるだけ長く監視できます。


NOTE: 単一のホストに複数のグリッドノードが含まれている場合は、そのホスト上のすべてのノードを停止するまでホストをシャットダウンしないでください。ホストにプライマリ管理ノードが含まれている場合は、そのホストを最後にシャットダウンします。


NOTE: 必要に応じて、を実行できます link:linux-migrating-grid-node-to-new-host.html["Linux ホスト間でのノードの移行"] グリッドの機能や可用性に影響を与えずにホストのメンテナンスを実行するため。

.手順
. すべてのクライアントアプリケーションからグリッドへのアクセスを停止します。
. [[log_in_on_gn] ][ 各ゲートウェイノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. [[stop_all_services]ノード上で実行されているすべてのサービスを停止します。 `service servermanager stop`
+
サービスのシャットダウンには最大 15 分かかる場合があります。リモートからシステムにログインしてシャットダウンプロセスを監視することもできます。



. 上記の 2 つの手順を繰り返して、すべてのストレージノード、アーカイブノード、非プライマリ管理ノードのサービスを停止します。
+
これらのノードのサービスは、どの順序で停止してもかまいません。

+

NOTE: 問題 を実行する場合は、を参照して `service servermanager stop` コマンド：アプライアンスストレージノードのサービスを停止するには、アプライアンスの電源を再投入してノードを再起動する必要があります。

. プライマリ管理ノードについて、の手順を繰り返します <<log_in_to_gn,ノードにログインします>> および <<stop_all_services,ノードのすべてのサービスを停止しています>>。
. Linux ホストで実行されているノードの場合：
+
.. ホストオペレーティングシステムにログインします。
.. ノードを停止します。 `storagegrid node stop`
.. ホストオペレーティングシステムをシャットダウンします。


. VMware仮想マシンで実行されているノードおよびアプライアンスストレージノードの場合問題 は、shutdownコマンドを使用します。 `shutdown -h now`
+
この手順は、の結果に関係なく実行します `service servermanager stop` コマンドを実行します

+
アプライアンスの場合、このコマンドはコンピューティングコントローラをシャットダウンしますが、アプライアンスの電源はオンになったままです。次の手順を実行する必要があります。

. アプライアンスノードがある場合：
+
** サービスアプライアンスまたはSGF6112アプライアンスの場合
+
... アプライアンスの電源をオフにします。
... 青色の電源 LED が消灯するまで待ちます。


** SG6000 アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、青色の電源 LED が消灯するまで待ちます。


** SG5700アプライアンスの場合
+
... ストレージコントローラの背面にある緑のキャッシュアクティブ LED が消灯するまで待ちます。
+
この LED は、キャッシュデータをドライブに書き込む必要があるときに点灯します。この LED が消灯するのを待ってから、電源をオフにする必要があります。

... アプライアンスの電源をオフにし、すべての LED とデジタル表示ディスプレイの動作が停止するまで待ちます。




. 必要に応じて、コマンドシェルからログアウトします。 `exit`
+
これで、 StorageGRID グリッドのシャットダウンは完了です。



.関連情報
https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112ストレージアプライアンス"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000 ストレージアプライアンス"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700ストレージアプライアンス"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110およびSG1100サービスアプライアンス"^]

https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100 および SG1000 サービスアプライアンス"^]
