---
permalink: maintain/troubleshooting-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, recover, decommission, troubleshoot 
summary: エラーが原因でノードの手順 の運用が停止した場合は、特定の手順に従って問題のトラブルシューティングを実施できます。 
---
= ノードの運用停止をトラブルシューティングする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
エラーが原因でノードの手順 の運用が停止した場合は、特定の手順に従って問題のトラブルシューティングを実施できます。

.作業を開始する前に
を使用して Grid Manager にサインインします link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。

.このタスクについて
運用停止処理中のグリッドノードをシャットダウンすると、グリッドノードが再起動されるまでタスクが停止します。グリッドノードはオンラインである必要があります。

.手順
. サポート * > * ツール * > * グリッドトポロジ * を選択します。
. グリッドトポロジツリーで各ストレージノードエントリを展開し、 DDS サービスと LDR サービスがオンラインになっていることを確認します。
+
ストレージノードの運用停止を実行するには、オンラインのノード / サイトの運用停止処理の開始時にすべてのノードおよびすべてのサービスが正常な状態である必要があります。

. アクティブなグリッドタスクを表示するには、「 * primary Admin Node * > * CMN * > * Grid Tasks * > * Overview * 」を選択します。
. グリッドタスクの運用停止のステータスを確認します。
+
.. グリッドタスクの運用停止ステータスがグリッドタスクバンドルの保存に問題があることを示している場合は、*プライマリ管理ノード*>* CMN *>* Events *>* Overview *を選択します。
.. 使用可能な監査リレーの数を確認します。
+
Available Audit Relay 属性が 1 つ以上の場合、 CMN サービスは少なくとも 1 つの ADC サービスに接続されています。ADC サービスは監査リレーとして機能します。

+
グリッドタスクで運用停止処理をあるステージから別のステージに進めて終了させるには、 CMN サービスが少なくとも 1 つの ADC サービスに接続され、かつ StorageGRID システムの ADC サービスの過半数（ 50%+1 ）が使用可能である必要があります。

.. CMN サービスが十分な数の ADC サービスに接続されていない場合は、ストレージノードがオンラインであることを確認し、プライマリ管理ノードとストレージノードの間のネットワーク接続を確認します。



