---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: ストレージノードは、オブジェクトデータとメタデータを管理および格納します。ストレージノードには、ディスク上のオブジェクトデータとメタデータを格納、移動、検証、読み出すために必要なサービスとプロセスが含まれています。 
---
= ストレージノードとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードは、オブジェクトデータとメタデータを管理および格納します。ストレージノードには、ディスク上のオブジェクトデータとメタデータを格納、移動、検証、読み出すために必要なサービスとプロセスが含まれています。

StorageGRIDシステムの各サイトには、少なくとも3つのストレージノードが必要です。



== ストレージノードのタイプ

StorageGRID 11.8より前にインストールされていたすべてのストレージノードに、オブジェクトとそれらのオブジェクトのメタデータの両方が格納されます。StorageGRID 11.8以降では、新しいソフトウェアベースのストレージノードのストレージノードタイプを選択できます。

オブジェクトストレージノードとメタデータストレージノード:: StorageGRID 11.8に新しくインストールしたすべてのストレージノードには、デフォルトでオブジェクトとメタデータの両方が格納されます。
メタデータ専用ストレージノード（ソフトウェアベースのノードのみ）:: メタデータのみの格納に新しいソフトウェアベースのストレージノードを使用するように指定できます。また、StorageGRIDシステムの拡張時に、メタデータのみのソフトウェアベースのストレージノードをStorageGRIDシステムに追加することもできます。
+
--

NOTE: ストレージノードタイプは、ソフトウェアベースのノードを最初にインストールするとき、またはStorageGRIDシステムの拡張時にソフトウェアベースのノードをインストールするときにのみ選択できます。ノードのインストールの完了後にタイプを変更することはできません。

--


通常、メタデータ専用ノードのインストールは必要ありません。ただし、非常に多数の小さなオブジェクトがグリッドに格納されている場合は、メタデータ専用のストレージノードを使用すると効果的です。専用のメタデータ容量をインストールすると、非常に多数の小さなオブジェクトに必要なスペースと、それらのすべてのオブジェクトのメタデータに必要なスペースのバランスが向上します。

ソフトウェアベースのメタデータのみのノードリソースは、既存のストレージノードリソースと一致している必要があります。例：

* 既存のStorageGRIDサイトでSG6000またはSG6100アプライアンスを使用している場合は、ソフトウェアベースのメタデータのみのノードが次の最小要件を満たしている必要があります。
+
** 128GBのRAM
** 8コアCPU
** 8TB SSDまたはCassandraデータベース用同等のストレージ（rangedb/0）


* 既存のStorageGRIDサイトで、24GBのRAM、8コアCPU、3TBまたは4TBのメタデータストレージを搭載した仮想ストレージノードを使用している場合は、ソフトウェアベースのメタデータ専用ノードで同様のリソース（24GBのRAM、8コアCPU、4TBのメタデータストレージ（rangedb/0）を使用する必要があります。


新しいStorageGRIDサイトを追加するときは、新しいサイトの総メタデータ容量が少なくとも既存のStorageGRIDサイトと一致し、新しいサイトのリソースが既存のStorageGRIDサイトのストレージノードと一致している必要があります。

ソフトウェアベースのメタデータのみのノードで構成されるグリッドをインストールする場合は、オブジェクトストレージ用のノードの最小数もグリッドに含まれている必要があります。

* 単一サイトのグリッドの場合は、オブジェクトとメタデータ用に少なくとも2つのストレージノードが設定されます。
* マルチサイトグリッドの場合は、サイトごとに少なくとも1つのストレージノードがオブジェクトとメタデータ用に設定されます。


ソフトウェアベースのストレージノードでは、ストレージノードタイプが表示されるすべてのページで、メタデータのみの各ノードについてメタデータのみの情報が表示されます。



== ストレージノードのプライマリサービス

次の表は、ストレージノードのプライマリサービスを示しています。ただし、この表にはすべてのノードサービスが含まれているわけではありません。


NOTE: ADC サービスや RSM サービスのように、通常は各サイトの 3 つのストレージノードにしか存在しないサービスもあります。

[cols="1a,3a"]
|===
| サービス | キー機能 


 a| 
アカウント（ acct ）
 a| 
テナントアカウントを管理します。



 a| 
Administrative Domain Controller （ ADC ；管理ドメインコントローラ）
 a| 
トポロジとグリッド全体の構成を管理します。

.詳細
[%collapsible]
====
Administrative Domain Controller （ ADC ）サービスは、グリッドノードとその相互接続を認証します。ADCサービスは、サイトにある少なくとも3つのストレージノードでホストされます。

ADC サービスは、サービスの場所や可用性などのトポロジ情報を管理します。あるグリッドノードが別のグリッドノードからの情報を必要とする場合や、別のグリッドノードによる処理を必要とする場合、そのグリッドノードは ADC サービスにアクセスして要求に最適なグリッドノードを見つけます。また、ADCサービスはStorageGRID環境の設定バンドルのコピーを保持し、すべてのグリッドノードが現在の設定情報を取得できるようにします。

分散された処理および孤立した処理に対応するため、各 ADC サービスは、証明書、設定バンドル、およびサービスやトポロジに関する情報を、 StorageGRID システム内の他の ADC サービスと同期します。

一般に、すべてのグリッドノードは少なくとも 1 つの ADC サービスへの接続を維持し、これにより、グリッドノードは常に最新情報にアクセスします。グリッドノードに接続すると、他のグリッドノードの証明書がキャッシュされるため、ADCサービスを使用できない場合でも既知のグリッドノードで引き続き機能できます。新しいグリッドノードが接続を確立するためには、 ADC サービスを使用する必要があります。

ADC サービスは接続された各グリッドノードからトポロジ情報を収集します。このグリッドノード情報には、 CPU 負荷、使用可能なディスクスペース（ストレージがある場合）、サポートされているサービス、およびグリッドノードのサイト ID が含まれます。その他のサービスは、トポロジクエリを介して ADC サービスにトポロジ情報を要求します。ADC サービスは、 StorageGRID システムから受信した最新情報で各クエリに応答します。

====


 a| 
Cassandra
 a| 
オブジェクトメタデータを格納し、保護します。



 a| 
Cassandra Reaper
 a| 
オブジェクトメタデータの自動修復を実行します。



 a| 
チャンク
 a| 
イレイジャーコーディングされたデータフラグメントとパリティフラグメントを管理します。



 a| 
Data Mover （ DMV ）
 a| 
クラウドストレージプールにデータを移動します。



 a| 
Distributed Data Store （ DDS ）
 a| 
オブジェクトメタデータストレージを監視します。

.詳細
[%collapsible]
====
各ストレージノードにはDistributed Data Store（DDS）サービスが含まれています。このサービスは、Cassandraデータベースと連携して、StorageGRIDシステムに格納されているオブジェクトメタデータに対してバックグラウンドタスクを実行します。

DDS サービスは、 StorageGRID システムに取り込まれたオブジェクトの合計数と、システムでサポートされている各インターフェイス（ S3 または Swift ）を使用して取り込まれたオブジェクトの合計数を追跡します。

====


 a| 
ID （ idnt ）
 a| 
LDAP および Active Directory から取得したユーザ ID を統合する



 a| 
Local Distribution Router （ LDR ）（ローカル分散ルータ（ LDR ）
 a| 
オブジェクトストレージプロトコル要求を処理し、ディスク上のオブジェクトデータを管理します。

.詳細
[%collapsible]
====
各ストレージノードには、Local Distribution Router（LDR；ローカル分散ルータ）サービスが含まれています。このサービスは、データストレージ、ルーティング、要求処理などのコンテンツ転送機能を処理します。LDRサービスは、データ転送の負荷とデータトラフィック機能を処理することで、StorageGRID システムのハードワークのほとんどを実行します。

LDR サービスは次のタスクを処理します。

* クエリ
* 情報ライフサイクル管理（ ILM ）のアクティビティ
* オブジェクトの削除
* オブジェクトデータのストレージ
* 別の LDR サービス（ストレージノード）からのオブジェクトデータの転送
* データストレージ管理
* プロトコルインターフェイス（ S3 および Swift ）


また、LDRサービスは、各S3およびSwiftオブジェクトを一意のUUIDにマッピングします。

オブジェクトストア:: LDR サービスの基盤となるデータストレージは、一定数のオブジェクトストア（ストレージボリュームとも呼ばれます）に分割されます。各オブジェクトストアは個別のマウントポイントです。
+
--
ストレージノード内のオブジェクトストアは、ボリューム ID と呼ばれる 0000 ~ 002F の 16 進数で識別されます。最初のオブジェクトストア（ボリューム 0 ）では、 Cassandra データベースのオブジェクトメタデータ用にスペースがリザーブされます。このボリュームの残りのスペースはオブジェクトデータに使用されます。他のすべてのオブジェクトストアはオブジェクトデータ専用です。オブジェクトデータにはレプリケートコピーとイレイジャーコーディングフラグメントがあります。

レプリケートコピーのスペース使用量を均等にするために、特定のオブジェクトのオブジェクトデータは、使用可能なストレージスペースに基づいて 1 つのオブジェクトストアに格納されます。オブジェクトストアの容量がいっぱいになると、ストレージノード上のスペースがなくなるまで、残りのオブジェクトストアに引き続きオブジェクトが格納されます。

--
メタデータの保護:: StorageGRID は Cassandra データベースにオブジェクトメタデータを格納します。 Cassandra データベースは LDR サービスと連携します。
+
--
冗長性を確保してオブジェクトメタデータを損失から保護するために、各サイトでオブジェクトメタデータのコピーが 3 つ保持されます。このレプリケーションは設定できず、自動的に実行されます。詳細については、を参照してください link:../admin/managing-object-metadata-storage.html["オブジェクトメタデータストレージを管理する"]。

--


====


 a| 
Replicated State Machine （ RSM ）
 a| 
S3プラットフォームサービス要求がそれぞれのエンドポイントに送信されるようにします。



 a| 
SSM （サーバステータスモニタ）
 a| 
オペレーティングシステムと基盤のハードウェアを監視します。

|===