---
permalink: expand/gather-required-materials.html 
sidebar: sidebar 
keywords: expand, expansion, planning, storagrid files 
summary: 拡張処理を実行する前に、機器を揃え、新しいハードウェアとネットワークの設置と設定を行ってください。 
---
= 必要なデータや機器を揃えます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拡張処理を実行する前に、機器を揃え、新しいハードウェアとネットワークの設置と設定を行ってください。

[cols="1a,2a"]
|===
| 項目 | 注： 


 a| 
StorageGRID インストールアーカイブ
 a| 
新しいグリッドノードや新しいサイトを追加する場合は、 StorageGRID インストールアーカイブをダウンロードして展開する必要があります。グリッドで現在実行されているバージョンと同じバージョンを使用する必要があります。

詳細については、の手順を参照してください <<download-and-extract-install-files,StorageGRID インストールファイルのダウンロードと展開>>。

*注：*既存のストレージノードに新しいストレージボリュームを追加する場合や新しいStorageGRID アプライアンスをインストールする場合は、ファイルをダウンロードする必要はありません。



 a| 
サービスラップトップ
 a| 
サービスラップトップには次のものがあります。

* ネットワークポート
* SSH クライアント（ PuTTY など）
* link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]




 a| 
`Passwords.txt` ファイル。
 a| 
コマンドラインでグリッドノードにアクセスするために必要なパスワードが含まれています。リカバリパッケージに含まれています。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズはに含まれていません `Passwords.txt` ファイル。



 a| 
StorageGRID のドキュメント
 a| 
* link:../admin/index.html["StorageGRID の管理"]
* link:../release-notes/index.html["リリースノート"]
* 使用しているプラットフォームに対応したインストール手順
+
** link:../rhel/index.html["Red Hat Enterprise LinuxへのStorageGRIDのインストール"]
** link:../ubuntu/index.html["UbuntuまたはDebianへのStorageGRIDのインストール"]
** link:../vmware/index.html["VMwareへのStorageGRIDのインストール"]






 a| 
ご使用のプラットフォームの最新ドキュメント
 a| 
サポートされるバージョンについては、を参照してください https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool （ IMT ）"^]。

|===


== StorageGRID インストールファイルをダウンロードして展開します

.[[download-dextract-install-files]]
新しいグリッドノードや新しいサイトを追加する前に、適切な StorageGRID インストールアーカイブをダウンロードし、ファイルを展開する必要があります。

.このタスクについて
拡張処理は、グリッドで現在実行されているバージョンの StorageGRID を使用して実行する必要があります。

.手順
. に進みます https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["ネットアップのダウンロード： StorageGRID"^]。
. グリッドで現在実行されている StorageGRID のバージョンを選択します。
. ネットアップアカウントのユーザ名とパスワードを使用してサインインします。
. [End User License Agreement]を読み、チェックボックスをオンにして、*[Accept & Continue]*を選択します。
. ダウンロードページの「* Install StorageGRID *」列で、を選択します `.tgz` または `.zip` ご使用のプラットフォームに対応するファイルです。
+
インストールアーカイブファイルに表示されるバージョンは、現在インストールされているソフトウェアのバージョンと一致している必要があります。

+
を使用します `.zip` ファイルサービスラップトップでWindowsを実行している場合。

+
[cols="1a,2a"]
|===
| プラットフォーム | インストールアーカイブ 


 a| 
Red Hat Enterprise Linux の場合
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu 、 Debian 、またはアプライアンス
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip`

`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 


 a| 
OpenStack / その他のハイパーバイザー
 a| 
OpenStack の既存の環境を拡張する場合は、上記のサポートされている Linux ディストリビューションのいずれかを実行する仮想マシンを導入し、 Linux に関する適切な手順に従う必要があります。

|===
. アーカイブファイルをダウンロードして展開します。
. プラットフォームに応じた手順に従って、プラットフォーム、計画したグリッドトポロジ、および StorageGRID システムの拡張方法に基づいて、必要なファイルを選択します。
+
各プラットフォームの手順に記載されているパスは、アーカイブファイルによってインストールされた最上位ディレクトリに対する相対パスです。

. Red Hat Enterprise Linuxシステムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./rps/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./rps/NLF000000.txt  a| 
製品サポートのない無償ライセンス。



| ./rps/StorageGRID-Webscale-Images-_version_-SHA.rpm  a| 
RHELホストにStorageGRIDノードイメージをインストールするためのRPMパッケージ。



| ./rps/StorageGRID-Webscale-Service-_version_-SHA.rpm  a| 
RHELホストにStorageGRIDホストサービスをインストールするためのRPMパッケージ。



| 導入スクリプトツール | 説明 


| ./rps/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./rps/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./rpms/configure -storagegrid-sample.json  a| 
で使用する構成ファイルの例 `configure-storagegrid.py` スクリプト：



| ./rps/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。このスクリプトは、Pingフェデレーションにも使用できます。



| ./rpms/configure -storagegridBlank.json （ StorageGRID を構成する  a| 
で使用する空の構成ファイル `configure-storagegrid.py` スクリプト：



| ./rps/extra/Ansible と入力します  a| 
StorageGRIDコンテナ導入用のRHELホストを設定するためのサンプルのAnsibleのロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./rpms/ storagegrid-ssoauth-azure.pyを参照してください  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./rpms/storagegrid-ssoauth-azure.js  a| 
仲間によって呼び出されたヘルパースクリプト `storagegrid-ssoauth-azure.py` AzureとのSSO対話を実行するPythonスクリプト。



| ./rpms/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===
. Ubuntu または Debian システムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./debs/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./debs/NLF000000.txt  a| 
テスト環境およびコンセプトの実証環境に使用できる、非本番環境のネットアップライセンスファイル。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイルのMD5チェックサム `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
Ubuntu ホストまたは Debian ホストに StorageGRID ホストサービスをインストールするための DEB パッケージ。



| 導入スクリプトツール | 説明 


| ./debs/configure-storagegrid.py  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./debs/configure-sga.py  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./debs/storagegrid-ssoauth.py  a| 
シングルサインオンが有効な場合にグリッド管理 API にサインインするために使用できる Python スクリプトの例。このスクリプトは、Pingフェデレーションにも使用できます。



| ./debs/configure -storagegrid-sample.json という形式で指定します  a| 
で使用する構成ファイルの例 `configure-storagegrid.py` スクリプト：



| ./debs/configure -storagegrid-bank.json という形式で実行します  a| 
で使用する空の構成ファイル `configure-storagegrid.py` スクリプト：



| ./debs/extras /Ansible を実行します  a| 
StorageGRID コンテナ導入用の Ubuntu ホストまたは Debian ホストを設定するためのサンプルの Ansible のロールとプレイブック。必要に応じて、ロールまたはプレイブックをカスタマイズできます。



| ./debs/ storagegrid-ssoauth-azure.py  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./debs/storagegrid-ssoauth-azure.js  a| 
仲間によって呼び出されたヘルパースクリプト `storagegrid-ssoauth-azure.py` AzureとのSSO対話を実行するPythonスクリプト。



| ./debs/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===
. VMware システムを拡張する場合は、適切なファイルを選択します。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./vsphere/README （ ./vsphere/README  a| 
StorageGRID ダウンロードファイルに含まれているすべてのファイルについて説明するテキストファイル。



| ./vsphere/NLF000000.txt にアクセスします  a| 
製品サポートのない無償ライセンス。



| ./vsphere/NetApp-SG-version-sha.vmdk  a| 
グリッドノード仮想マシンを作成するためのテンプレートとして使用される仮想マシンディスクファイル。



| ./vsphere/vsphere-primary-admin.ovf

./vsphere/vsphere-primary-admin.mf  a| 
Open Virtualization Formatテンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を使用してください。



| ./vsphere/vsphere-non-primary-admin.ovf

./vsphere/vsphere-non-primary-admin.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）。非プライマリ管理ノードを導入する場合に使用します。



| ./vsphere/vsphere-archive.ovf

./vsphere/vsphere-archive.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を使用してアーカイブノードを導入します。



| ./vsphere/vsphere-gateway.ovf

./vsphere/vsphere-gateway.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を選択します。



| ./vsphere/vsphere-storage.ovf

./vsphere/vsphere-storage.mf  a| 
テンプレートファイル (`.ovf`)とマニフェストファイル (`.mf`）を選択します。



| 導入スクリプトツール | 説明 


| ./vsphere/deploy-vsphere-ovftool.sh にアクセスします  a| 
仮想グリッドノードの導入を自動化するための Bash シェルスクリプト。



| ./vsphere/deploy-vsphere-ovftool-sample.ini にアクセスします  a| 
で使用する構成ファイルの例 `deploy-vsphere-ovftool.sh` スクリプト：



| ./vsphere/configure-storagegrid.py にアクセスします  a| 
StorageGRID システムの設定を自動化するための Python スクリプト。



| ./vsphere/configure-sga.py にアクセスします  a| 
StorageGRID アプライアンスの設定を自動化するための Python スクリプト。



| ./vsphere/storagegrid-ssoauth.py にアクセスします  a| 
シングルサインオン（SSO）が有効な場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。このスクリプトは、Pingフェデレーションにも使用できます。



| ./vsphere/configure -storagegrid-sample.json という形式で実行します  a| 
で使用する構成ファイルの例 `configure-storagegrid.py` スクリプト：



| ./vsphere/configure -storagegrid-bank.json （ページ構成  a| 
で使用する空の構成ファイル `configure-storagegrid.py` スクリプト：



| ./vsphere/storagegrid-ssoauth-azure.pyを参照してください  a| 
Active DirectoryまたはPingフェデレーションを使用してシングルサインオン（SSO）が有効になっている場合にグリッド管理APIにサインインするために使用できるPythonスクリプトの例。



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
仲間によって呼び出されたヘルパースクリプト `storagegrid-ssoauth-azure.py` AzureとのSSO対話を実行するPythonスクリプト。



| ./vsphere/extra/api-schemas  a| 
StorageGRID の API スキーマ

*注*：アップグレードを実行する前に、これらのスキーマを使用して、アップグレード互換性テスト用の非本番環境のStorageGRID 環境がない場合、StorageGRID 管理APIを使用するように記述したコードが新しいStorageGRID リリースと互換性があることを確認できます。

|===
. StorageGRID アプライアンスベースのシステムを拡張する場合は、該当するファイルを選択してください。


[cols="1a,1a"]
|===
| パスとファイル名 | 説明 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
アプライアンスに StorageGRID ノードイメージをインストールするための DEB パッケージ。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
ファイルのMD5チェックサム `/debs/storagegridwebscale-
images-version-SHA.deb`。

|===

NOTE: アプライアンスのインストールの場合、これらのファイルが必要になるのは、ネットワークトラフィックを回避する必要がある場合だけです。アプライアンスは、プライマリ管理ノードから必要なファイルをダウンロードできます。



== ハードウェアとネットワークの確認

StorageGRID システムの拡張を開始する前に、次の点を確認してください。

* 新しいグリッドノードまたは新しいサイトをサポートするために必要なハードウェアを設置して設定しておきます。
* すべての新しいノードに、既存および新規のすべてのノードへの双方向通信パスがある（グリッドネットワークの要件）。特に、拡張で追加する新しいノードとプライマリ管理ノードの間で次のTCPポートが開いていることを確認します。
+
** 1055
** 7443
** 8011だ
** 10342.


+
を参照してください link:../network/internal-grid-node-communications.html["内部でのグリッドノードの通信"]。

* プライマリ管理ノードは、 StorageGRID システムをホストするすべての拡張サーバと通信できます。
* 新しいノードのいずれかでグリッドネットワークの IP アドレスが使用されていないサブネットにある場合は、すでに完了している link:updating-subnets-for-grid-network.html["新しいサブネットが追加されました"] をクリックしてください。それ以外の場合は、拡張をキャンセルし、新しいサブネットを追加してから、手順 をもう一度開始する必要があります。
* グリッドノード間またはStorageGRID サイト間のグリッドネットワークでNetwork Address Translation（NAT；ネットワークアドレス変換）を使用していない。グリッドネットワークにプライベート IPv4 アドレスを使用する場合は、使用するアドレスに各サイトのすべてのグリッドノードから直接ルーティングできる必要があります。NATを使用したパブリックネットワークセグメント間のグリッドネットワークのブリッジは、すべてのユーザに対して透過的なトンネリングアプリケーションを使用している場合にのみサポートされます。
グリッド内のノード。つまり、グリッドノードがパブリックIPアドレスを認識する必要はありません。
+
この NAT の制限は、グリッドノードとグリッドネットワークに固有のものです。必要に応じて、ゲートウェイノードにパブリック IP アドレスを指定する場合など、外部クライアントとグリッドノードの間で NAT を使用できます。


