---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: クラウドストレージプールは、単一の外部Amazon S3バケットまたはその他のS3互換プロバイダ、またはAzure BLOBストレージコンテナを指定します。 
---
= クラウドストレージプールを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラウドストレージプールは、単一の外部Amazon S3バケットまたはその他のS3互換プロバイダ、またはAzure BLOBストレージコンテナを指定します。

クラウドストレージプールを作成するときは、StorageGRID がオブジェクトの格納に使用する外部バケットまたはコンテナの名前と場所、クラウドプロバイダのタイプ（Amazon S3 / GCPまたはAzure BLOBストレージ）、および外部バケットまたはコンテナにアクセスするためにStorageGRID が必要とする情報を指定します。

クラウドストレージプールは保存後すぐに StorageGRID で検証されます。そのため、クラウドストレージプールに指定されたバケットまたはコンテナが存在し、アクセス可能であることを確認しておく必要があります。

.作業を開始する前に
* を使用して Grid Manager にサインインします link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* を使用することができます link:../admin/admin-group-permissions.html["必要なアクセス権限"]。
* を確認しておきます link:considerations-for-cloud-storage-pools.html["クラウドストレージプールに関する考慮事項"]。
* クラウドストレージプールによって参照される外部のバケットまたはコンテナがすでに存在し、その名前と場所を確認しておきます。
* バケットまたはコンテナにアクセスするには、選択する認証タイプに関する次の情報が必要です。
+
[role="tabbed-block"]
====
.S3アクセスキー
--
外部S3バケットの_

** 外部バケットを所有するアカウントのアクセスキーID。
** 関連付けられているシークレットアクセスキー。


または、認証タイプとしてAnonymousを指定することもできます。

--
.C2Sアクセスポータル
--
_ Commercial Cloud Services（C2S）S3サービス_

次のものが必要です。

** StorageGRID がC2Sアクセスポータル（CAP）サーバから一時的なクレデンシャルを取得するために使用する完全なURL。これには、C2Sアカウントに割り当てられた必須およびオプションのAPIパラメータがすべて含まれます。
** 適切な政府認証局（CA）が発行したサーバCA証明書。StorageGRID は、この証明書を使用して CAP サーバの識別情報を確認します。サーバ CA 証明書は PEM エンコードを使用している必要があります。
** 適切な政府認証局（CA）が発行したクライアント証明書。StorageGRID は、この証明書を使用して CAP サーバに対して自身を識別します。クライアント証明書は PEM エンコードを使用し、 C2S アカウントへのアクセスが許可されている必要があります。
** クライアント証明書用のPEMでエンコードされた秘密鍵。
** クライアント証明書の秘密鍵を復号化するためのパスフレーズ（暗号化されている場合）。



NOTE: クライアント証明書が暗号化される場合は、暗号化に従来の形式を使用します。PKCS#8暗号化形式はサポートされていません。

--
.Azure BLOBストレージ
--
外部コンテナの_

** Blob Storageコンテナへのアクセスに使用するUniform Resource Identifier（URI）。
** ストレージアカウントの名前とアカウントキー。これらの値は Azure portal を使用して確認できます。


--
====


.手順
. ILM *>* Storage pools *>* Cloud Storage Pools *を選択します。
. [作成]*を選択し、次の情報を入力します。
+
[cols="1a,3a"]
|===
| フィールド | 説明 


 a| 
クラウドストレージプールの名前
 a| 
クラウドストレージプールとその目的を簡単に説明する名前。ILM ルールを設定するときに識別しやすい名前を使用してください。



 a| 
プロバイダタイプ
 a| 
このクラウドストレージプールに使用するクラウドプロバイダ：

** * Amazon S3 / GCP *：Amazon S3、Commercial Cloud Services（C2S）S3、Google Cloud Platform（GCP）、またはその他のS3互換プロバイダの場合は、このオプションを選択します。
** * Azure Blob Storage *




 a| 
バケットまたはコンテナ
 a| 
外部のS3バケットまたはAzureコンテナの名前。クラウドストレージプールの保存後にこの値を変更することはできません。

|===
. 選択したプロバイダタイプに基づいて、サービスエンドポイント情報を入力します。
+
[role="tabbed-block"]
====
.Amazon S3 / GCP
--
.. プロトコルに対して、[HTTPS]または[HTTP]を選択します。
+

NOTE: 機密データにHTTP接続を使用しないでください。

.. ホスト名を入力します。例
+
`s3-_aws-region_.amazonaws.com`

.. URLスタイルを選択します。
+
[cols="1a,3a"]
|===
| オプション | 説明 


 a| 
自動検出
 a| 
指定された情報に基づいて、使用する URL スタイルを自動的に検出します。たとえば、 IP アドレスを指定すると、 StorageGRID はパス形式の URL を使用します。使用するスタイルがわからない場合にのみ、このオプションを選択してください。



 a| 
virtual-hosted-styleの略
 a| 
仮想ホスト形式のURLを使用してバケットにアクセスします。仮想ホスト形式のURLでは、ドメイン名の一部にバケット名が含まれます。例 `+https://bucket-name.s3.company.com/key-name+`



 a| 
パス形式
 a| 
パス形式の URL を使用してバケットにアクセスします。パス形式のURLの末尾にはバケット名が含まれます例 `+https://s3.company.com/bucket-name/key-name+`

*注：*パス形式のURLオプションは推奨されておらず、StorageGRID の今後のリリースで廃止される予定です。

|===
.. 必要に応じて、ポート番号を入力するか、デフォルトのポート（HTTPSの場合は443、HTTPの場合は80）を使用します。


--
.Azure BLOBストレージ
--
.. 次のいずれかの形式を使用して、サービスエンドポイントのURIを入力します。
+
*** `+https://host:port+`
*** `+http://host:port+`




例 `https://_myaccount_.blob.core.windows.net:443`

ポートを指定しない場合、HTTPSにはデフォルトでポート443が使用され、HTTPにはポート80が使用されます。

--
====


. 「 * Continue * 」を選択します。次に、認証タイプを選択し、クラウドストレージプールエンドポイントに必要な情報を入力します。
+
[role="tabbed-block"]
====
.アクセスキー
--
Amazon S3 / GCPプロバイダタイプの場合のみ_

.. [Access key ID]*に、外部バケットを所有するアカウントのアクセスキーIDを入力します。
.. [Secret access key]*に、シークレットアクセスキーを入力します。


--
.CAP（C2Sアクセスポータル）
--
_ Commercial Cloud Services（C2S）S3サービス_

.. [Temporary credentials URL]に、StorageGRID がCAPサーバから一時的なクレデンシャルを取得するために使用する完全なURLを入力します。これには、C2Sアカウントに割り当てられている必須およびオプションのAPIパラメータがすべて含まれます。
.. [Server CA certificate]*で、[Browse]*を選択し、StorageGRID がCAPサーバの検証に使用するPEMでエンコードされたCA証明書をアップロードします。
.. [Client certificate]*で、[Browse]*を選択し、PEMでエンコードされた証明書をアップロードします。この証明書は、StorageGRID がCAPサーバに対して自身を識別するために使用します。
.. [クライアント秘密鍵]*で、*[参照]*を選択し、クライアント証明書用のPEMでエンコードされた秘密鍵をアップロードします。
.. クライアントの秘密鍵が暗号化されている場合は、クライアントの秘密鍵を復号化するためのパスフレーズを入力します。それ以外の場合は、* Client private key passphrase *フィールドを空白のままにします。


--
.Azure BLOBストレージ
--
.. [アカウント名]に、外部サービスコンテナを所有するBLOBストレージアカウントの名前を入力します。
.. [Account key]*に、BLOBストレージアカウントのシークレットキーを入力します。


--
.匿名
--
追加情報 は必要ありません。

--
====
. 「 * Continue * 」を選択します。次に、使用するサーバ検証のタイプを選択します。
+
[cols="1a,2a"]
|===
| オプション | 説明 


 a| 
ストレージノードOSでルートCA証明書を使用する
 a| 
オペレーティングシステムにインストールされているグリッド CA 証明書を使用して接続を保護します。



 a| 
カスタム CA 証明書を使用する
 a| 
カスタム CA 証明書を使用する。[参照]*を選択し、PEMでエンコードされた証明書をアップロードします。



 a| 
証明書を検証しないでください
 a| 
TLS 接続に使用される証明書は検証されません。

|===
. [ 保存（ Save ） ] を選択します。
+
クラウドストレージプールを保存すると、 StorageGRID では次の処理が実行されます。

+
** バケットまたはコンテナとサービスエンドポイントが存在し、指定したクレデンシャルを使用してアクセスできることを検証します。
** クラウドストレージプールとして識別するために、バケットまたはコンテナにマーカーファイルを書き込みます。このファイルは削除しないでください `x-ntap-sgws-cloud-pool-uuid`。
+
クラウドストレージプールの検証に失敗すると、その理由を記載したエラーメッセージが表示されます。たとえば、証明書エラーが発生した場合や、指定したバケットまたはコンテナが存在しない場合にエラーが報告されることがあります。



. エラーが発生した場合は、を参照してください link:troubleshooting-cloud-storage-pools.html["クラウドストレージプールのトラブルシューティング手順"]をクリックし、問題を解決してから、クラウドストレージプールをもう一度保存してください。

