---
permalink: ilm/how-objects-are-deleted.html 
sidebar: sidebar 
keywords: ILM deletion, how objects are deleted 
summary: StorageGRID は、クライアント要求に直接応答してオブジェクトを削除するか、 S3 バケットライフサイクルの終了または ILM ポリシーの要件に応じて自動的にオブジェクトを削除します。オブジェクトのさまざまな削除方法と StorageGRID による削除要求の処理方法を理解しておくと、オブジェクトをより効率的に管理できるようになります。 
---
= オブジェクトの削除方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID は、クライアント要求に直接応答してオブジェクトを削除するか、 S3 バケットライフサイクルの終了または ILM ポリシーの要件に応じて自動的にオブジェクトを削除します。オブジェクトのさまざまな削除方法と StorageGRID による削除要求の処理方法を理解しておくと、オブジェクトをより効率的に管理できるようになります。

StorageGRID では、次のいずれかの方法でオブジェクトを削除できます。

* 同期削除： StorageGRID がクライアントの削除要求を受け取ると、すべてのオブジェクトコピーがただちに削除されます。コピーが削除されると、削除が成功したことがクライアントに通知されます。
* オブジェクトは削除キューに登録されます。 StorageGRID が削除要求を受け取ると、オブジェクトは削除キューに登録され、削除が成功したことがクライアントにすぐに通知されます。オブジェクトコピーは、あとでバックグラウンド ILM 処理によって削除されます。


StorageGRID では、オブジェクトを削除する際に、削除のパフォーマンスを最適化し、削除のバックログを最小限に抑え、スペースを最も早く解放する方法を使用します。

次の表は、 StorageGRID がどのような場合に各メソッドを使用するかを

[cols="1a,3a"]
|===
| 削除方法 | 使用時 


 a| 
オブジェクトは削除キューに登録されます
 a| 
次の条件のいずれか * が当てはまる場合：

* 次のいずれかのイベントによってオブジェクトの自動削除がトリガーされた：
+
** S3 バケットのライフサイクル設定の有効期限または日数に達した。
** ILM ルールに指定された最後の期間が経過した。


+
*注：* S3オブジェクトロックが有効になっているバケット内のオブジェクトは、リーガルホールドの対象である場合、またはretain-until-dateが指定されていてもまだ満たされていない場合は削除できません。

* S3 / Swift クライアントが削除を要求し、次の条件を 1 つ以上満たしている：
+
** オブジェクトの場所が一時的に使用できない場合など、30秒以内にコピーを削除することはできません。
** バックグラウンド削除キューがアイドル状態である。






 a| 
オブジェクトをただちに削除（同期削除）
 a| 
S3 / Swift クライアントが削除要求を行い、次の * すべての条件が満たされている場合：

* すべてのコピーを 30 秒以内に削除できる。
* バックグラウンド削除キューには処理するオブジェクトが含まれています。


|===
S3またはSwiftクライアントが削除要求を行うと、StorageGRID はまずオブジェクトを削除キューに追加します。その後、同期削除の実行に切り替えます。処理対象となるオブジェクトがバックグラウンド削除キューに含まれていることを確認することで、 StorageGRID は、クライアントによる削除のバックログが発生しないようにしつつ、特に同時実行性の低いクライアントに対してより効率的に削除を処理できます。



== オブジェクトの削除に必要な時間

StorageGRID によるオブジェクトの削除方法は、システムの動作に影響を及ぼす可能性があります。

* StorageGRID StorageGRID で同期削除が実行されると、結果がクライアントに返されるまでに最大 30 秒かかることがあります。つまり、実際には StorageGRID がオブジェクトを削除キューに登録する場合よりも短時間でコピーが削除されるにもかかわらず、より長くかかっているという印象をクライアントに与える可能性があります。
* 一括削除の実行中に削除のパフォーマンスを綿密に監視している場合、一定数のオブジェクトが削除されたあとに削除速度が低下しているように見えることがあります。この変更は、 StorageGRID がオブジェクトを削除キューへ登録する方法から同期削除に切り替えたときに発生します。削除速度が低下したように見えても、オブジェクトコピーの削除速度が遅くなったわけではありません。一方で、スペースの開放にかかる時間は、平均すると短くなっています。


大量のオブジェクトを削除する場合に、スペースを短時間で解放することが優先されるのであれば、 ILM などの方法を使用してオブジェクトを削除するのではなく、クライアント要求を使用することを検討してください。一般に、クライアントによって削除が実行された場合、 StorageGRID は同期削除を使用できるため、スペースはより短時間で解放されます。

オブジェクトの削除後にスペースを解放するために必要な時間は、いくつかの要因によって異なります。

* オブジェクトコピーが同期的に削除されるか、またはキューに登録されたあとで削除されるか（クライアントの削除要求の場合）。
* グリッド内のオブジェクトの数や、オブジェクトコピーが削除対象キューに登録される場合のグリッドリソースの可用性などのその他の要因（クライアントによる削除およびその他の方法の場合）。




== S3 バージョン管理オブジェクトの削除方法

S3 バケットでバージョン管理が有効になっている場合、 StorageGRID は、削除要求に応答する際、要求が S3 クライアント、 S3 バケットライフサイクルの終了、 ILM ポリシーの要件のいずれによるものであるかにかかわらず、 Amazon S3 の動作に従います。

オブジェクトがバージョン管理されている場合、オブジェクトの削除要求ではオブジェクトの現在のバージョンは削除されず、スペースも解放されません。代わりに、オブジェクトの削除要求では、オブジェクトの現在のバージョンとしてゼロバイトの削除マーカーが作成され、以前のバージョンのオブジェクトが「noncurrent」になります。 オブジェクト削除マーカーが最新バージョンであり、最新でないバージョンがない場合、オブジェクト削除マーカーは期限切れのオブジェクト削除マーカーになります。

オブジェクトが削除されていなくても、 StorageGRID は現在のバージョンのオブジェクトが使用できなくなったかのように動作します。そのオブジェクトに対する要求は 404 NotFound を返します。ただし、最新でないオブジェクトデータは削除されていないため、最新でないバージョンのオブジェクトを指定する要求は成功します。

バージョン管理オブジェクトを削除するときに領域を解放したり、削除マーカーを削除したりするには、次のいずれかを使用します。

* * S3クライアント要求*：S3 DELETE Object要求にオブジェクトのバージョンIDを指定します (`DELETE /object?versionId=ID`）。この要求は、指定したバージョンのオブジェクトコピーだけを削除します（他のバージョンは引き続きスペースを消費します）。
* *バケットライフサイクル*：を使用します `NoncurrentVersionExpiration` をクリックします。NoncurrentDays で指定した日数に達すると、 StorageGRID は最新でないオブジェクトバージョンのコピーをすべて完全に削除します。これらのオブジェクトバージョンはリカバリできません。
+
。 `NewerNoncurrentVersions` バケットライフサイクル設定の処理は、バージョン管理されたS3バケットで保持する最新でないバージョンの数を指定します。最新でないバージョンの数がより多い場合 `NewerNoncurrentVersions` NoncurrentDaysの値が経過すると、StorageGRIDは古いバージョンを削除します。。 `NewerNoncurrentVersions` しきい値は、ILMが提供するライフサイクルルール（内のバージョンが最新でないオブジェクト）よりも優先されます `NewerNoncurrentVersions` しきい値は、ILMが削除を要求した場合に保持されます。

+
期限切れのオブジェクト削除マーカーを削除するには、 `Expiration` 次のいずれかのタグを使用したアクション： `ExpiredObjectDeleteMarker`、 `Days`または `Date`。

* * ILM * ： link:creating-ilm-policy.html["アクティブポリシーのクローンを作成する"] 次の2つのILMルールを新しいポリシーに追加します。
+
** 最初のルール：[Reference Time]に「noncurrent time」を使用して最新でないバージョンのオブジェクトを照合します。インチ link:create-ilm-rule-enter-details.html["ILMルールの作成ウィザードの手順1（詳細を入力）"]で、「Apply this rule to older object versions only（S3バケットでバージョン管理が有効になっている場合）？」という質問に対して* Yes *を選択します。
** 2つ目のルール：*取り込み時間*を使用して現在のバージョンと一致させます。「noncurrent time」ルールは、ポリシーの「取り込み時間」ルールの上に表示する必要があります。
+

NOTE: ILMを使用して現在のオブジェクト削除マーカーを削除することはできません。S3クライアント要求またはS3バケットライフサイクルを使用して、現在のオブジェクト削除マーカーを削除します。



* *バケット内のオブジェクトを削除*：テナントマネージャを使用して、 link:../tenant/deleting-s3-bucket-objects.html["すべてのオブジェクトバージョンを削除"]バケットから削除マーカーを含む。
+
バージョン管理オブジェクトが削除されると、StorageGRIDはオブジェクトの現在のバージョンとしてゼロバイトの削除マーカーを作成します。バージョン管理されたバケットを削除する前に、すべてのオブジェクトと削除マーカーを削除する必要があります。

+
** StorageGRID 11.7以前で作成された削除マーカーは、S3クライアント要求でのみ削除できます。ILM、バケットライフサイクルルール、またはバケット処理のDeleteオブジェクトでは削除されません。
** StorageGRID 11.8以降で作成されたバケットの削除マーカーは、ILM、バケットライフサイクルルール、バケット処理のオブジェクトの削除、またはS3クライアントの明示的な削除によって削除できます。StorageGRID 11.8以降で期限切れの削除マーカーを削除するには、バケットライフサイクルルールまたはバージョンIDを指定した明示的なS3クライアント要求で削除する必要があります。




.関連情報
* link:../s3/index.html["S3 REST APIを使用する"]
* link:example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["例 4 ： S3 バージョン管理オブジェクトの ILM ルールとポリシー"]

