---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: StorageGRID には、グリッド管理者と個々のテナントユーザが、オブジェクトを格納する期間を指定するためのオプションがあります。通常、テナントユーザが指定した保持手順は、グリッド管理者が指定した保持手順よりも優先されます。 
---
= オブジェクト保持期間の決定方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID には、グリッド管理者と個々のテナントユーザが、オブジェクトを格納する期間を指定するためのオプションがあります。通常、テナントユーザが指定した保持手順は、グリッド管理者が指定した保持手順よりも優先されます。



== テナントユーザによるオブジェクト保持期間の制御方法

テナントユーザは、主に次の 3 つの方法でオブジェクトを StorageGRID に格納する期間を制御できます。

* グリッドでグローバルな S3 オブジェクトのロック設定が有効になっている場合、 S3 テナントユーザは S3 オブジェクトのロックを有効にしたバケットを作成し、 S3 REST API を使用して、そのバケットに追加された各オブジェクトバージョンの最新の保持設定とリーガルホールド設定を指定できます。
+
** リーガルホールドの対象となっているオブジェクトバージョンは、どの方法でも削除できません。
** オブジェクトバージョンのretain-until-dateに達する前は、どの方法でもそのバージョンを削除できません。
** S3オブジェクトロックが有効になっているバケット内のオブジェクトは、ILMによって「無期限」に保持されます。 ただし、retain-until-dateに達すると、クライアント要求またはバケットライフサイクルの終了によってオブジェクトバージョンを削除できます。を参照してください link:managing-objects-with-s3-object-lock.html["S3 オブジェクトロックでオブジェクトを管理します"]。


* S3 テナントユーザは、 Expiration アクションを指定するライフサイクル設定をバケットに追加できます。バケットライフサイクルが存在する場合、クライアントがオブジェクトを削除しないかぎり、 StorageGRID は Expiration アクションで指定された日付または日数が経過するまでオブジェクトを格納します。を参照してください link:../s3/create-s3-lifecycle-configuration.html["S3 ライフサイクル設定を作成する"]。
* S3 / Swift クライアントは、オブジェクトの削除要求を問題 に送信できます。StorageGRID は、オブジェクトを削除するか保持するかを決定する際に、常に S3 バケットライフサイクルまたは ILM よりもクライアントの削除要求を優先します。




== グリッド管理者によるオブジェクト保持期間の制御方法

グリッド管理者は、 ILM の配置手順を使用してオブジェクトの格納期間を制御します。オブジェクトが ILM ルールに一致した場合、 StorageGRID は ILM ルールの最後の期間が経過するまでそのオブジェクトを格納します。配置手順に「forever」が指定されている場合、オブジェクトは無期限に保持されます。

オブジェクトの保持期間を誰が制御するかに関係なく、格納するオブジェクトコピーのタイプ（レプリケートまたはイレイジャーコーディング）とコピーの場所（ストレージノード、クラウドストレージプール、またはアーカイブノード）はILM設定によって制御されます。



== S3 バケットライフサイクルと ILM の相互作用

S3バケットライフサイクルが設定されている場合は、ライフサイクルフィルタに一致するオブジェクトのILMポリシーがライフサイクル有効期限のアクションで上書きされます。その結果、 ILM のオブジェクト配置手順がすべて終了したあとも、オブジェクトがグリッドに保持されることがあります。



== オブジェクト保持の例

S3 オブジェクトロック、バケットライフサイクル設定、クライアントの削除要求、 ILM の相互作用について、より深く理解するために次の例を検討してください。



=== 例 1 ： S3 バケットライフサイクルのオブジェクト保持期間が ILM よりも長い

ILM:: 2 つのコピーを 1 年間保存（ 365 日）
バケットライフサイクル:: 2 年（ 730 日）でオブジェクトが期限切れになる
結果:: StorageGRID はオブジェクトを 730 日間格納します。StorageGRID は、バケットライフサイクル設定を使用して、オブジェクトを削除するか保持するかを決定します。



NOTE: ILM よりもバケットライフサイクルのオブジェクト保持期間の方が長い場合でも、格納するコピーの数とタイプを決定する際には引き続き StorageGRID の配置手順が使用されます。この例では、 366 日目から 730 日目までの間、オブジェクトの 2 つのコピーが StorageGRID に引き続き格納されます。



=== 例 2 ： S3 バケットライフサイクルのオブジェクト保持期間よりも短い

ILM:: 2 つのコピーを 2 年間（ 730 日）格納する
バケットライフサイクル:: 1 年（ 365 日）でオブジェクトを期限切れにする
結果:: StorageGRID は 365 日目にオブジェクトのコピーを両方削除します。




=== 例 3 ：クライアントによる削除は、バケットライフサイクルと ILM よりも優先されます

ILM:: 2つのコピーをストレージノードに「無期限」で格納
バケットライフサイクル:: 2 年（ 730 日）でオブジェクトが期限切れになる
クライアントの削除要求:: 発行日： 400 日目
結果:: StorageGRID は、クライアントの削除要求に応じて 400 日目にオブジェクトのコピーを両方削除します。




=== 例 4 ： S3 オブジェクトロックはクライアントの削除要求を上書きします

S3 オブジェクトのロック:: オブジェクトバージョンの retain-until は、 2026-03-31 です。リーガルホールドは有効ではありません。
準拠 ILM ルール:: 2つのコピーをストレージノードに「無期限」で格納
クライアントの削除要求:: 発行日2024-03-31
結果:: retain-until はまだ 2 年前の時点であるため、 StorageGRID はオブジェクトバージョンを削除しません。

