---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: ストレージプールは、ストレージノードまたはアーカイブノードを論理的にグループ化したものです。 
---
= ストレージプールとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージプールは、ストレージノードまたはアーカイブノードを論理的にグループ化したものです。

StorageGRID をインストールすると、サイトごとに1つのストレージプールが自動的に作成されます。ストレージ要件に応じて、追加のストレージプールを設定できます。


NOTE: ストレージノードは、インストール時にオブジェクトデータとオブジェクトメタデータ、またはオブジェクトメタデータのみを格納するように設定できます。メタデータのみのストレージノードをストレージプールで使用することはできません。詳細については、を参照してください link:../primer/what-storage-node-is.html#types-of-storage-nodes["ストレージノードのタイプ"]。


NOTE: アーカイブノードのサポートは廃止され、今後のリリースで削除される予定です。S3 API を使用してアーカイブノードから外部のアーカイブストレージシステムにオブジェクトを移動する処理は、より多くの機能を提供する ILM Cloud Storage Pools に置き換えられました。

ストレージプールには 2 つの属性があります。

* * ストレージグレード * ：ストレージノードの場合は、バッキングストレージの相対的なパフォーマンス。
* * サイト * ：オブジェクトを格納するデータセンター。


ストレージプールは、オブジェクトデータの格納場所と使用するストレージのタイプを決定するためにILMルールで使用されます。レプリケーションのための ILM ルールを設定する際は、ストレージノードまたはアーカイブノードを含むストレージプールを 1 つ以上選択します。イレイジャーコーディングプロファイルを作成するときは、ストレージノードを含むストレージプールを選択します。
